package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.AgtEmpInfoLog;
import com.dlfc.zfgj.entity.AgtEmpInfoLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.dlfc.admin.common.persistence.MyMapper;

@MyBatisDao
public interface AgtEmpInfoLogMapper extends MyMapper<AgtEmpInfoLog> {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table agt_emp_info_log
     * @mbggenerated  Mon Dec 14 13:22:34 CST 2015
     */
    int countByExample(AgtEmpInfoLogExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table agt_emp_info_log
     * @mbggenerated  Mon Dec 14 13:22:34 CST 2015
     */
    int deleteByExample(AgtEmpInfoLogExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table agt_emp_info_log
     * @mbggenerated  Mon Dec 14 13:22:34 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table agt_emp_info_log
     * @mbggenerated  Mon Dec 14 13:22:34 CST 2015
     */
    int insert(AgtEmpInfoLog record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table agt_emp_info_log
     * @mbggenerated  Mon Dec 14 13:22:34 CST 2015
     */
    int insertSelective(AgtEmpInfoLog record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table agt_emp_info_log
     * @mbggenerated  Mon Dec 14 13:22:34 CST 2015
     */
    List<AgtEmpInfoLog> selectByExample(AgtEmpInfoLogExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table agt_emp_info_log
     * @mbggenerated  Mon Dec 14 13:22:34 CST 2015
     */
    AgtEmpInfoLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table agt_emp_info_log
     * @mbggenerated  Mon Dec 14 13:22:34 CST 2015
     */
    int updateByExampleSelective(@Param("record") AgtEmpInfoLog record, @Param("example") AgtEmpInfoLogExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table agt_emp_info_log
     * @mbggenerated  Mon Dec 14 13:22:34 CST 2015
     */
    int updateByExample(@Param("record") AgtEmpInfoLog record, @Param("example") AgtEmpInfoLogExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table agt_emp_info_log
     * @mbggenerated  Mon Dec 14 13:22:34 CST 2015
     */
    int updateByPrimaryKeySelective(AgtEmpInfoLog record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table agt_emp_info_log
     * @mbggenerated  Mon Dec 14 13:22:34 CST 2015
     */
    int updateByPrimaryKey(AgtEmpInfoLog record);
}