package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.AgtEmpDeptLink;
import com.dlfc.zfgj.entity.AgtEmpDeptLinkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@MyBatisDao
public interface AgtEmpDeptLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_emp_dept_link
     *
     * @mbggenerated Mon Nov 16 14:21:39 CST 2015
     */
    int countByExample(AgtEmpDeptLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_emp_dept_link
     *
     * @mbggenerated Mon Nov 16 14:21:39 CST 2015
     */
    int deleteByExample(AgtEmpDeptLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_emp_dept_link
     *
     * @mbggenerated Mon Nov 16 14:21:39 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_emp_dept_link
     *
     * @mbggenerated Mon Nov 16 14:21:39 CST 2015
     */
    int insert(AgtEmpDeptLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_emp_dept_link
     *
     * @mbggenerated Mon Nov 16 14:21:39 CST 2015
     */
    int insertSelective(AgtEmpDeptLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_emp_dept_link
     *
     * @mbggenerated Mon Nov 16 14:21:39 CST 2015
     */
    List<AgtEmpDeptLink> selectByExample(AgtEmpDeptLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_emp_dept_link
     *
     * @mbggenerated Mon Nov 16 14:21:39 CST 2015
     */
    AgtEmpDeptLink selectByPrimaryKey(String id);
    
    List<AgtEmpDeptLink> selectByStatus(int status);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_emp_dept_link
     *
     * @mbggenerated Mon Nov 16 14:21:39 CST 2015
     */
    int updateByExampleSelective(@Param("record") AgtEmpDeptLink record, @Param("example") AgtEmpDeptLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_emp_dept_link
     *
     * @mbggenerated Mon Nov 16 14:21:39 CST 2015
     */
    int updateByExample(@Param("record") AgtEmpDeptLink record, @Param("example") AgtEmpDeptLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_emp_dept_link
     *
     * @mbggenerated Mon Nov 16 14:21:39 CST 2015
     */
    int updateByPrimaryKeySelective(AgtEmpDeptLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_emp_dept_link
     *
     * @mbggenerated Mon Nov 16 14:21:39 CST 2015
     */
    int updateByPrimaryKey(AgtEmpDeptLink record);
}