package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.CmsSite;
import com.dlfc.zfgj.entity.CmsSiteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@MyBatisDao
public interface CmsSiteMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_site
	 * @mbggenerated  Mon Dec 05 17:27:54 CST 2016
	 */
	int countByExample(CmsSiteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_site
	 * @mbggenerated  Mon Dec 05 17:27:54 CST 2016
	 */
	int deleteByExample(CmsSiteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_site
	 * @mbggenerated  Mon Dec 05 17:27:54 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_site
	 * @mbggenerated  Mon Dec 05 17:27:54 CST 2016
	 */
	int insert(CmsSite record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_site
	 * @mbggenerated  Mon Dec 05 17:27:54 CST 2016
	 */
	int insertSelective(CmsSite record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_site
	 * @mbggenerated  Mon Dec 05 17:27:54 CST 2016
	 */
	List<CmsSite> selectByExampleWithBLOBs(CmsSiteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_site
	 * @mbggenerated  Mon Dec 05 17:27:54 CST 2016
	 */
	List<CmsSite> selectByExample(CmsSiteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_site
	 * @mbggenerated  Mon Dec 05 17:27:54 CST 2016
	 */
	CmsSite selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_site
	 * @mbggenerated  Mon Dec 05 17:27:54 CST 2016
	 */
	int updateByExampleSelective(@Param("record") CmsSite record, @Param("example") CmsSiteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_site
	 * @mbggenerated  Mon Dec 05 17:27:54 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") CmsSite record, @Param("example") CmsSiteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_site
	 * @mbggenerated  Mon Dec 05 17:27:54 CST 2016
	 */
	int updateByExample(@Param("record") CmsSite record, @Param("example") CmsSiteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_site
	 * @mbggenerated  Mon Dec 05 17:27:54 CST 2016
	 */
	int updateByPrimaryKeySelective(CmsSite record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_site
	 * @mbggenerated  Mon Dec 05 17:27:54 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(CmsSite record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_site
	 * @mbggenerated  Mon Dec 05 17:27:54 CST 2016
	 */
	int updateByPrimaryKey(CmsSite record);
}