package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.MyMapper;
import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.ConContract;
import com.dlfc.zfgj.entity.ConContractTp;
import com.dlfc.zfgj.entity.ConContractTpExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
@MyBatisDao
public interface ConContractTpMapper extends MyMapper<ConContractTp>{
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_contract_tp
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	int countByExample(ConContractTpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_contract_tp
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	int deleteByExample(ConContractTpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_contract_tp
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_contract_tp
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	int insert(ConContractTp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_contract_tp
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	int insertSelective(ConContractTp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_contract_tp
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	List<ConContractTp> selectByExample(ConContractTpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_contract_tp
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	ConContractTp selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_contract_tp
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	int updateByExampleSelective(@Param("record") ConContractTp record,
			@Param("example") ConContractTpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_contract_tp
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	int updateByExample(@Param("record") ConContractTp record,
			@Param("example") ConContractTpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_contract_tp
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	int updateByPrimaryKeySelective(ConContractTp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_contract_tp
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	int updateByPrimaryKey(ConContractTp record);

	ConContractTp findDissById(String cid);

	List<ConContractTp> findByList(ConContractTp con);

	List<ConContractTp> getConInPeriod(ConContractTp con);

	double getAreaInPeriod(ConContractTp con);

	ConContractTp findById(String cid);

	ConContractTp findOne(ConContractTp con);

	void update(ConContractTp contract);
	
	List<ConContractTp> getEndTime(ConContractTp con);
}