package com.dlfc.zfgj.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dlfc.admin.common.persistence.MyMapper;
import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.ConHouseItemsLog;
import com.dlfc.zfgj.entity.ConHouseItemsLogExample;
@MyBatisDao
public interface ConHouseItemsLogMapper extends MyMapper<ConHouseItemsLog> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_items_log
	 * @mbggenerated  Thu May 12 13:26:45 CST 2016
	 */
	int countByExample(ConHouseItemsLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_items_log
	 * @mbggenerated  Thu May 12 13:26:45 CST 2016
	 */
	int deleteByExample(ConHouseItemsLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_items_log
	 * @mbggenerated  Thu May 12 13:26:45 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_items_log
	 * @mbggenerated  Thu May 12 13:26:45 CST 2016
	 */
	int insert(ConHouseItemsLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_items_log
	 * @mbggenerated  Thu May 12 13:26:45 CST 2016
	 */
	int insertSelective(ConHouseItemsLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_items_log
	 * @mbggenerated  Thu May 12 13:26:45 CST 2016
	 */
	List<ConHouseItemsLog> selectByExample(ConHouseItemsLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_items_log
	 * @mbggenerated  Thu May 12 13:26:45 CST 2016
	 */
	ConHouseItemsLog selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_items_log
	 * @mbggenerated  Thu May 12 13:26:45 CST 2016
	 */
	int updateByExampleSelective(@Param("record") ConHouseItemsLog record,
			@Param("example") ConHouseItemsLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_items_log
	 * @mbggenerated  Thu May 12 13:26:45 CST 2016
	 */
	int updateByExample(@Param("record") ConHouseItemsLog record, @Param("example") ConHouseItemsLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_items_log
	 * @mbggenerated  Thu May 12 13:26:45 CST 2016
	 */
	int updateByPrimaryKeySelective(ConHouseItemsLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_items_log
	 * @mbggenerated  Thu May 12 13:26:45 CST 2016
	 */
	int updateByPrimaryKey(ConHouseItemsLog record);
}