package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.MyMapper;
import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.ConHouseItems;
import com.dlfc.zfgj.entity.ConHouseItemsExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;
@MyBatisDao
public interface ConHouseItemsMapper extends MyMapper<ConHouseItems> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_items
	 * @mbggenerated  Thu May 12 13:26:45 CST 2016
	 */
	int countByExample(ConHouseItemsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_items
	 * @mbggenerated  Thu May 12 13:26:45 CST 2016
	 */
	int deleteByExample(ConHouseItemsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_items
	 * @mbggenerated  Thu May 12 13:26:45 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_items
	 * @mbggenerated  Thu May 12 13:26:45 CST 2016
	 */
	int insert(ConHouseItems record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_items
	 * @mbggenerated  Thu May 12 13:26:45 CST 2016
	 */
	int insertSelective(ConHouseItems record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_items
	 * @mbggenerated  Thu May 12 13:26:45 CST 2016
	 */
	List<ConHouseItems> selectByExample(ConHouseItemsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_items
	 * @mbggenerated  Thu May 12 13:26:45 CST 2016
	 */
	ConHouseItems selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_items
	 * @mbggenerated  Thu May 12 13:26:45 CST 2016
	 */
	int updateByExampleSelective(@Param("record") ConHouseItems record, @Param("example") ConHouseItemsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_items
	 * @mbggenerated  Thu May 12 13:26:45 CST 2016
	 */
	int updateByExample(@Param("record") ConHouseItems record, @Param("example") ConHouseItemsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_items
	 * @mbggenerated  Thu May 12 13:26:45 CST 2016
	 */
	int updateByPrimaryKeySelective(ConHouseItems record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_items
	 * @mbggenerated  Thu May 12 13:26:45 CST 2016
	 */
	int updateByPrimaryKey(ConHouseItems record);
}