package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.MyMapper;
import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.HouCoOwner;
import com.dlfc.zfgj.entity.HouCoOwnerExample;
import com.dlfc.zfgj.entity.HouCoOwnerLog;

import java.util.List;

import org.apache.ibatis.annotations.Param;
@MyBatisDao
public interface HouCoOwnerMapper extends MyMapper<HouCoOwner>{
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_co_owner
	 * @mbggenerated  Tue Jul 26 19:55:07 CST 2016
	 */
	int countByExample(HouCoOwnerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_co_owner
	 * @mbggenerated  Tue Jul 26 19:55:07 CST 2016
	 */
	int deleteByExample(HouCoOwnerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_co_owner
	 * @mbggenerated  Tue Jul 26 19:55:07 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_co_owner
	 * @mbggenerated  Tue Jul 26 19:55:07 CST 2016
	 */
	int insert(HouCoOwner record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_co_owner
	 * @mbggenerated  Tue Jul 26 19:55:07 CST 2016
	 */
	int insertSelective(HouCoOwner record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_co_owner
	 * @mbggenerated  Tue Jul 26 19:55:07 CST 2016
	 */
	List<HouCoOwner> selectByExample(HouCoOwnerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_co_owner
	 * @mbggenerated  Tue Jul 26 19:55:07 CST 2016
	 */
	HouCoOwner selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_co_owner
	 * @mbggenerated  Tue Jul 26 19:55:07 CST 2016
	 */
	int updateByExampleSelective(@Param("record") HouCoOwner record,
			@Param("example") HouCoOwnerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_co_owner
	 * @mbggenerated  Tue Jul 26 19:55:07 CST 2016
	 */
	int updateByExample(@Param("record") HouCoOwner record,
			@Param("example") HouCoOwnerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_co_owner
	 * @mbggenerated  Tue Jul 26 19:55:07 CST 2016
	 */
	int updateByPrimaryKeySelective(HouCoOwner record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_co_owner
	 * @mbggenerated  Tue Jul 26 19:55:07 CST 2016
	 */
	int updateByPrimaryKey(HouCoOwner record);

	void saveCoOwnerLog(HouCoOwnerLog record);
	
	List<HouCoOwner> findCoOwner(HouCoOwner coOwner);
}