package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.SysOfficeAreaLink;
import com.dlfc.zfgj.entity.SysOfficeAreaLinkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@MyBatisDao
public interface SysOfficeAreaLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_office_area_link
     *
     * @mbggenerated Tue Dec 01 13:18:21 CST 2015
     */
    int countByExample(SysOfficeAreaLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_office_area_link
     *
     * @mbggenerated Tue Dec 01 13:18:21 CST 2015
     */
    int deleteByExample(SysOfficeAreaLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_office_area_link
     *
     * @mbggenerated Tue Dec 01 13:18:21 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_office_area_link
     *
     * @mbggenerated Tue Dec 01 13:18:21 CST 2015
     */
    int insert(SysOfficeAreaLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_office_area_link
     *
     * @mbggenerated Tue Dec 01 13:18:21 CST 2015
     */
    int insertSelective(SysOfficeAreaLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_office_area_link
     *
     * @mbggenerated Tue Dec 01 13:18:21 CST 2015
     */
    List<SysOfficeAreaLink> selectByExample(SysOfficeAreaLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_office_area_link
     *
     * @mbggenerated Tue Dec 01 13:18:21 CST 2015
     */
    SysOfficeAreaLink selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_office_area_link
     *
     * @mbggenerated Tue Dec 01 13:18:21 CST 2015
     */
    int updateByExampleSelective(@Param("record") SysOfficeAreaLink record, @Param("example") SysOfficeAreaLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_office_area_link
     *
     * @mbggenerated Tue Dec 01 13:18:21 CST 2015
     */
    int updateByExample(@Param("record") SysOfficeAreaLink record, @Param("example") SysOfficeAreaLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_office_area_link
     *
     * @mbggenerated Tue Dec 01 13:18:21 CST 2015
     */
    int updateByPrimaryKeySelective(SysOfficeAreaLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_office_area_link
     *
     * @mbggenerated Tue Dec 01 13:18:21 CST 2015
     */
    int updateByPrimaryKey(SysOfficeAreaLink record);
    
    List<SysOfficeAreaLink> selectByOfficeId(SysOfficeAreaLink sysOfficeAreaLink);
}