package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.MyMapper;
import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.AgtCusComment;
import com.dlfc.zfgj.entity.AgtCusCommentExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
@MyBatisDao
public interface AgtCusCommentMapper extends MyMapper<AgtCusComment>{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_cus_comment
	 * @mbggenerated  Wed Nov 18 16:55:17 CST 2015
	 */
	int countByExample(AgtCusCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_cus_comment
	 * @mbggenerated  Wed Nov 18 16:55:17 CST 2015
	 */
	int deleteByExample(AgtCusCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_cus_comment
	 * @mbggenerated  Wed Nov 18 16:55:17 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_cus_comment
	 * @mbggenerated  Wed Nov 18 16:55:17 CST 2015
	 */
	int insert(AgtCusComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_cus_comment
	 * @mbggenerated  Wed Nov 18 16:55:17 CST 2015
	 */
	int insertSelective(AgtCusComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_cus_comment
	 * @mbggenerated  Wed Nov 18 16:55:17 CST 2015
	 */
	List<AgtCusComment> selectByExample(AgtCusCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_cus_comment
	 * @mbggenerated  Wed Nov 18 16:55:17 CST 2015
	 */
	AgtCusComment selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_cus_comment
	 * @mbggenerated  Wed Nov 18 16:55:17 CST 2015
	 */
	int updateByExampleSelective(@Param("record") AgtCusComment record,
                                 @Param("example") AgtCusCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_cus_comment
	 * @mbggenerated  Wed Nov 18 16:55:17 CST 2015
	 */
	int updateByExample(@Param("record") AgtCusComment record,
                        @Param("example") AgtCusCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_cus_comment
	 * @mbggenerated  Wed Nov 18 16:55:17 CST 2015
	 */
	int updateByPrimaryKeySelective(AgtCusComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_cus_comment
	 * @mbggenerated  Wed Nov 18 16:55:17 CST 2015
	 */
	int updateByPrimaryKey(AgtCusComment record);
}