package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.MyMapper;
import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.AgtUsrCompLogInfo;
import com.dlfc.zfgj.entity.AgtUsrCompLogInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@MyBatisDao
public interface AgtUsrCompLogInfoMapper extends MyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_usr_comp_log_info
	 * @mbggenerated  Fri Nov 20 11:42:44 CST 2015
	 */
	int countByExample(AgtUsrCompLogInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_usr_comp_log_info
	 * @mbggenerated  Fri Nov 20 11:42:44 CST 2015
	 */
	int deleteByExample(AgtUsrCompLogInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_usr_comp_log_info
	 * @mbggenerated  Fri Nov 20 11:42:44 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_usr_comp_log_info
	 * @mbggenerated  Fri Nov 20 11:42:44 CST 2015
	 */
	int insert(AgtUsrCompLogInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_usr_comp_log_info
	 * @mbggenerated  Fri Nov 20 11:42:44 CST 2015
	 */
	int insertSelective(AgtUsrCompLogInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_usr_comp_log_info
	 * @mbggenerated  Fri Nov 20 11:42:44 CST 2015
	 */
	List<AgtUsrCompLogInfo> selectByExample(AgtUsrCompLogInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_usr_comp_log_info
	 * @mbggenerated  Fri Nov 20 11:42:44 CST 2015
	 */
	AgtUsrCompLogInfo selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_usr_comp_log_info
	 * @mbggenerated  Fri Nov 20 11:42:44 CST 2015
	 */
	int updateByExampleSelective(@Param("record") AgtUsrCompLogInfo record,
                                 @Param("example") AgtUsrCompLogInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_usr_comp_log_info
	 * @mbggenerated  Fri Nov 20 11:42:44 CST 2015
	 */
	int updateByExample(@Param("record") AgtUsrCompLogInfo record,
                        @Param("example") AgtUsrCompLogInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_usr_comp_log_info
	 * @mbggenerated  Fri Nov 20 11:42:44 CST 2015
	 */
	int updateByPrimaryKeySelective(AgtUsrCompLogInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_usr_comp_log_info
	 * @mbggenerated  Fri Nov 20 11:42:44 CST 2015
	 */
	int updateByPrimaryKey(AgtUsrCompLogInfo record);
	
//	List<AgtUsrCompLogInfo> selectByExampleAll(AgtUsrCompLogInfoExample example);
//
//	/**
//	 * 查询信息 add by yuanjiwei 2015.11.23
//	 * @param agtUsrCompLogInfo
//	 * @return
//	 */
//	List<AgtUsrCompLogInfo> selectAgtUsrCompLogList(AgtUsrCompLogInfo agtUsrCompLogInfo);
//
//	String selectIdByUserId(AgtUsrCompLogInfo aucl);
//
//	void reJoinComp(String userId);
//
//	List<AgtUsrCompLogInfo> findAgtUsrCompLog(String uid);
}