package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.CmsAdMedia;
import com.dlfc.zfgj.entity.CmsAdMediaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@MyBatisDao
public interface CmsAdMediaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_ad_media
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	int countByExample(CmsAdMediaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_ad_media
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	int deleteByExample(CmsAdMediaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_ad_media
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_ad_media
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	int insert(CmsAdMedia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_ad_media
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	int insertSelective(CmsAdMedia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_ad_media
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	List<CmsAdMedia> selectByExample(CmsAdMediaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_ad_media
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	CmsAdMedia selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_ad_media
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	int updateByExampleSelective(@Param("record") CmsAdMedia record, @Param("example") CmsAdMediaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_ad_media
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	int updateByExample(@Param("record") CmsAdMedia record, @Param("example") CmsAdMediaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_ad_media
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	int updateByPrimaryKeySelective(CmsAdMedia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_ad_media
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	int updateByPrimaryKey(CmsAdMedia record);
}