package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.CmsArticle;
import com.dlfc.zfgj.entity.CmsArticleExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@MyBatisDao
public interface CmsArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbggenerated Wed Apr 27 19:51:59 CST 2016
     */
    int countByExample(CmsArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbggenerated Wed Apr 27 19:51:59 CST 2016
     */
    int deleteByExample(CmsArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbggenerated Wed Apr 27 19:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbggenerated Wed Apr 27 19:51:59 CST 2016
     */
    int insert(CmsArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbggenerated Wed Apr 27 19:51:59 CST 2016
     */
    int insertSelective(CmsArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbggenerated Wed Apr 27 19:51:59 CST 2016
     */
    List<CmsArticle> selectByExampleWithBLOBs(CmsArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbggenerated Wed Apr 27 19:51:59 CST 2016
     */
    List<CmsArticle> selectByExample(CmsArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbggenerated Wed Apr 27 19:51:59 CST 2016
     */
    CmsArticle selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbggenerated Wed Apr 27 19:51:59 CST 2016
     */
    int updateByExampleSelective(@Param("record") CmsArticle record, @Param("example") CmsArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbggenerated Wed Apr 27 19:51:59 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") CmsArticle record, @Param("example") CmsArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbggenerated Wed Apr 27 19:51:59 CST 2016
     */
    int updateByExample(@Param("record") CmsArticle record, @Param("example") CmsArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbggenerated Wed Apr 27 19:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(CmsArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbggenerated Wed Apr 27 19:51:59 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(CmsArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbggenerated Wed Apr 27 19:51:59 CST 2016
     */
    int updateByPrimaryKey(CmsArticle record);
    
//    //获取公告列表
//    List<CmsArticle> getNotice(CmsArticle record);
//
//    //获取公告列表详情
//    CmsArticle getNoticeDetail(CmsArticle record);
//
//    //获取列表
//    List<CmsArticle> getList(CmsArticle record);
//
//    //获取列表内容
//    List<CmsArticle> getInfoContent(String id);
}