package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.CmsCategory;
import com.dlfc.zfgj.entity.CmsCategoryExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MyBatisDao
public interface CmsCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbggenerated Tue May 24 15:49:21 CST 2016
     */
    int countByExample(CmsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbggenerated Tue May 24 15:49:21 CST 2016
     */
    int deleteByExample(CmsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbggenerated Tue May 24 15:49:21 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbggenerated Tue May 24 15:49:21 CST 2016
     */
    int insert(CmsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbggenerated Tue May 24 15:49:21 CST 2016
     */
    int insertSelective(CmsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbggenerated Tue May 24 15:49:21 CST 2016
     */
    List<CmsCategory> selectByExampleWithBLOBs(CmsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbggenerated Tue May 24 15:49:21 CST 2016
     */
    List<CmsCategory> selectByExample(CmsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbggenerated Tue May 24 15:49:21 CST 2016
     */
    CmsCategory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbggenerated Tue May 24 15:49:21 CST 2016
     */
    int updateByExampleSelective(@Param("record") CmsCategory record, @Param("example") CmsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbggenerated Tue May 24 15:49:21 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") CmsCategory record, @Param("example") CmsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbggenerated Tue May 24 15:49:21 CST 2016
     */
    int updateByExample(@Param("record") CmsCategory record, @Param("example") CmsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbggenerated Tue May 24 15:49:21 CST 2016
     */
    int updateByPrimaryKeySelective(CmsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbggenerated Tue May 24 15:49:21 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(CmsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbggenerated Tue May 24 15:49:21 CST 2016
     */
    int updateByPrimaryKey(CmsCategory record);
    
//    List<CmsCategory> getNameUrl(String id);
    
}