package com.dlfc.zfgj.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dlfc.admin.common.persistence.MyMapper;
import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.ConDepositDistLog;
import com.dlfc.zfgj.entity.ConDepositDistLogExample;
@MyBatisDao
public interface ConDepositDistLogMapper  extends MyMapper<ConDepositDistLog>{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_log
	 * @mbggenerated  Fri Dec 18 15:31:01 CST 2015
	 */
	int countByExample(ConDepositDistLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_log
	 * @mbggenerated  Fri Dec 18 15:31:01 CST 2015
	 */
	int deleteByExample(ConDepositDistLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_log
	 * @mbggenerated  Fri Dec 18 15:31:01 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_log
	 * @mbggenerated  Fri Dec 18 15:31:01 CST 2015
	 */
	int insert(ConDepositDistLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_log
	 * @mbggenerated  Fri Dec 18 15:31:01 CST 2015
	 */
	int insertSelective(ConDepositDistLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_log
	 * @mbggenerated  Fri Dec 18 15:31:01 CST 2015
	 */
	List<ConDepositDistLog> selectByExample(ConDepositDistLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_log
	 * @mbggenerated  Fri Dec 18 15:31:01 CST 2015
	 */
	ConDepositDistLog selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_log
	 * @mbggenerated  Fri Dec 18 15:31:01 CST 2015
	 */
	int updateByExampleSelective(@Param("record") ConDepositDistLog record,
                                 @Param("example") ConDepositDistLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_log
	 * @mbggenerated  Fri Dec 18 15:31:01 CST 2015
	 */
	int updateByExample(@Param("record") ConDepositDistLog record, @Param("example") ConDepositDistLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_log
	 * @mbggenerated  Fri Dec 18 15:31:01 CST 2015
	 */
	int updateByPrimaryKeySelective(ConDepositDistLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_log
	 * @mbggenerated  Fri Dec 18 15:31:01 CST 2015
	 */
	int updateByPrimaryKey(ConDepositDistLog record);
}