package com.dlfc.zfgj.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dlfc.admin.common.persistence.MyMapper;
import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.ConHouseUser;
import com.dlfc.zfgj.entity.ConHouseUserExample;
@MyBatisDao
public interface ConHouseUserMapper extends MyMapper<ConHouseUser> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user
     *
     * @mbggenerated Fri Nov 13 16:14:10 CST 2015
     */
    int countByExample(ConHouseUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user
     *
     * @mbggenerated Fri Nov 13 16:14:10 CST 2015
     */
    int deleteByExample(ConHouseUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user
     *
     * @mbggenerated Fri Nov 13 16:14:10 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user
     *
     * @mbggenerated Fri Nov 13 16:14:10 CST 2015
     */
    int insert(ConHouseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user
     *
     * @mbggenerated Fri Nov 13 16:14:10 CST 2015
     */
    int insertSelective(ConHouseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user
     *
     * @mbggenerated Fri Nov 13 16:14:10 CST 2015
     */
    List<ConHouseUser> selectByExample(ConHouseUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user
     *
     * @mbggenerated Fri Nov 13 16:14:10 CST 2015
     */
    ConHouseUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user
     *
     * @mbggenerated Fri Nov 13 16:14:10 CST 2015
     */
    int updateByExampleSelective(@Param("record") ConHouseUser record, @Param("example") ConHouseUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user
     *
     * @mbggenerated Fri Nov 13 16:14:10 CST 2015
     */
    int updateByExample(@Param("record") ConHouseUser record, @Param("example") ConHouseUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user
     *
     * @mbggenerated Fri Nov 13 16:14:10 CST 2015
     */
    int updateByPrimaryKeySelective(ConHouseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user
     *
     * @mbggenerated Fri Nov 13 16:14:10 CST 2015
     */
    int updateByPrimaryKey(ConHouseUser record);
}