package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.ConRentstagingLog;
import com.dlfc.zfgj.entity.ConRentstagingLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MyBatisDao
public interface ConRentstagingLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_rentstaging_log
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	int countByExample(ConRentstagingLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_rentstaging_log
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	int deleteByExample(ConRentstagingLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_rentstaging_log
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_rentstaging_log
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	int insert(ConRentstagingLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_rentstaging_log
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	int insertSelective(ConRentstagingLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_rentstaging_log
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	List<ConRentstagingLog> selectByExample(ConRentstagingLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_rentstaging_log
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	ConRentstagingLog selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_rentstaging_log
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	int updateByExampleSelective(@Param("record") ConRentstagingLog record,
                                 @Param("example") ConRentstagingLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_rentstaging_log
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	int updateByExample(@Param("record") ConRentstagingLog record, @Param("example") ConRentstagingLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_rentstaging_log
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	int updateByPrimaryKeySelective(ConRentstagingLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_rentstaging_log
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	int updateByPrimaryKey(ConRentstagingLog record);
}