package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.MyMapper;
import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.HouHouseInfo;
import com.dlfc.zfgj.entity.HouHouseInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MyBatisDao
public interface HouHouseInfoMapper extends MyMapper<HouHouseInfo> {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_house_info
	 * @mbggenerated  Tue Oct 18 13:50:33 CST 2016
	 */
	int countByExample(HouHouseInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_house_info
	 * @mbggenerated  Tue Oct 18 13:50:33 CST 2016
	 */
	int deleteByExample(HouHouseInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_house_info
	 * @mbggenerated  Tue Oct 18 13:50:33 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_house_info
	 * @mbggenerated  Tue Oct 18 13:50:33 CST 2016
	 */
	int insert(HouHouseInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_house_info
	 * @mbggenerated  Tue Oct 18 13:50:33 CST 2016
	 */
	int insertSelective(HouHouseInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_house_info
	 * @mbggenerated  Tue Oct 18 13:50:33 CST 2016
	 */
	List<HouHouseInfo> selectByExample(HouHouseInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_house_info
	 * @mbggenerated  Tue Oct 18 13:50:33 CST 2016
	 */
	HouHouseInfo selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_house_info
	 * @mbggenerated  Tue Oct 18 13:50:33 CST 2016
	 */
	int updateByExampleSelective(@Param("record") HouHouseInfo record, @Param("example") HouHouseInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_house_info
	 * @mbggenerated  Tue Oct 18 13:50:33 CST 2016
	 */
	int updateByExample(@Param("record") HouHouseInfo record, @Param("example") HouHouseInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_house_info
	 * @mbggenerated  Tue Oct 18 13:50:33 CST 2016
	 */
	int updateByPrimaryKeySelective(HouHouseInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_house_info
	 * @mbggenerated  Tue Oct 18 13:50:33 CST 2016
	 */
	int updateByPrimaryKey(HouHouseInfo record);

//	List<HouHouseInfo> selectHouseInfoList(HouHouseInfo record);
//
//	HouHouseInfo findHouOne(String id);
//
//	String selectCheckIdNo(HouHouseInfo record);
//
//	String selectCheckAddr(HouHouseInfo record);
//
//	HouHouseInfo delCheck(String record);
//
//	void saveHouseLog(HouHouseInfoLog record);
//
//	HouHouseInfo selectHouseInfo(HouHouseInfo record);
//
//	List<String> checkPerson(Map<String, String> map);
//
//	String checkVersion(HouHouseInfo record);
//
//	List<HouHouseInfo> findList(String beid);
//
//	HouHouseInfo getBaseInfoById(String beid);
//
//	List<String> findByBaseId(@Param("baseId") String baseId);
}