package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.MyMapper;
import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.HouLeaseInfoLog;
import com.dlfc.zfgj.entity.HouLeaseInfoLogExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
@MyBatisDao
public interface HouLeaseInfoLogMapper extends MyMapper<HouLeaseInfoLog>{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_lease_info_log
	 * @mbggenerated  Thu Jan 05 18:27:03 CST 2017
	 */
	int countByExample(HouLeaseInfoLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_lease_info_log
	 * @mbggenerated  Thu Jan 05 18:27:03 CST 2017
	 */
	int deleteByExample(HouLeaseInfoLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_lease_info_log
	 * @mbggenerated  Thu Jan 05 18:27:03 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_lease_info_log
	 * @mbggenerated  Thu Jan 05 18:27:03 CST 2017
	 */
	int insert(HouLeaseInfoLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_lease_info_log
	 * @mbggenerated  Thu Jan 05 18:27:03 CST 2017
	 */
	int insertSelective(HouLeaseInfoLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_lease_info_log
	 * @mbggenerated  Thu Jan 05 18:27:03 CST 2017
	 */
	List<HouLeaseInfoLog> selectByExampleWithBLOBs(
            HouLeaseInfoLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_lease_info_log
	 * @mbggenerated  Thu Jan 05 18:27:03 CST 2017
	 */
	List<HouLeaseInfoLog> selectByExample(HouLeaseInfoLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_lease_info_log
	 * @mbggenerated  Thu Jan 05 18:27:03 CST 2017
	 */
	HouLeaseInfoLog selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_lease_info_log
	 * @mbggenerated  Thu Jan 05 18:27:03 CST 2017
	 */
	int updateByExampleSelective(@Param("record") HouLeaseInfoLog record,
                                 @Param("example") HouLeaseInfoLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_lease_info_log
	 * @mbggenerated  Thu Jan 05 18:27:03 CST 2017
	 */
	int updateByExampleWithBLOBs(@Param("record") HouLeaseInfoLog record,
                                 @Param("example") HouLeaseInfoLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_lease_info_log
	 * @mbggenerated  Thu Jan 05 18:27:03 CST 2017
	 */
	int updateByExample(@Param("record") HouLeaseInfoLog record,
                        @Param("example") HouLeaseInfoLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_lease_info_log
	 * @mbggenerated  Thu Jan 05 18:27:03 CST 2017
	 */
	int updateByPrimaryKeySelective(HouLeaseInfoLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_lease_info_log
	 * @mbggenerated  Thu Jan 05 18:27:03 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(HouLeaseInfoLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_lease_info_log
	 * @mbggenerated  Thu Jan 05 18:27:03 CST 2017
	 */
	int updateByPrimaryKey(HouLeaseInfoLog record);
}