package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.MyMapper;
import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.SysMessage;
import com.dlfc.zfgj.entity.SysMessageExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MyBatisDao
public interface SysMessageMapper extends MyMapper<SysMessage> {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_message
     * @mbggenerated  Tue Dec 29 09:21:43 CST 2015
     */
    int countByExample(SysMessageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_message
     * @mbggenerated  Tue Dec 29 09:21:43 CST 2015
     */
    int deleteByExample(SysMessageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_message
     * @mbggenerated  Tue Dec 29 09:21:43 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_message
     * @mbggenerated  Tue Dec 29 09:21:43 CST 2015
     */
    int insert(SysMessage record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_message
     * @mbggenerated  Tue Dec 29 09:21:43 CST 2015
     */
    int insertSelective(SysMessage record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_message
     * @mbggenerated  Tue Dec 29 09:21:43 CST 2015
     */
    List<SysMessage> selectByExampleList(SysMessageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_message
     * @mbggenerated  Tue Dec 29 09:21:43 CST 2015
     */
    SysMessage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_message
     * @mbggenerated  Tue Dec 29 09:21:43 CST 2015
     */
    int updateByExampleSelective(@Param("record") SysMessage record, @Param("example") SysMessageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_message
     * @mbggenerated  Tue Dec 29 09:21:43 CST 2015
     */
    int updateByExample(@Param("record") SysMessage record, @Param("example") SysMessageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_message
     * @mbggenerated  Tue Dec 29 09:21:43 CST 2015
     */
    int updateByPrimaryKeySelective(SysMessage record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_message
     * @mbggenerated  Tue Dec 29 09:21:43 CST 2015
     */
    int updateByPrimaryKey(SysMessage record);
    
//    SysMessage selectUpMsg(SysMessage record);
//
//    SysMessage selectDownMsg(SysMessage record);
//
//    List<SysMessage> selectByReceiverIdAndStatus(@Param(value = "receiverId") String receiverId, @Param(value = "status") Short status);
}