package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.SysPaychannelBanks;
import com.dlfc.zfgj.entity.SysPaychannelBanksExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@MyBatisDao
public interface SysPaychannelBanksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_paychannel_banks
     *
     * @mbggenerated Sat Apr 23 11:20:58 CST 2016
     */
    int countByExample(SysPaychannelBanksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_paychannel_banks
     *
     * @mbggenerated Sat Apr 23 11:20:58 CST 2016
     */
    int deleteByExample(SysPaychannelBanksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_paychannel_banks
     *
     * @mbggenerated Sat Apr 23 11:20:58 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_paychannel_banks
     *
     * @mbggenerated Sat Apr 23 11:20:58 CST 2016
     */
    int insert(SysPaychannelBanks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_paychannel_banks
     *
     * @mbggenerated Sat Apr 23 11:20:58 CST 2016
     */
    int insertSelective(SysPaychannelBanks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_paychannel_banks
     *
     * @mbggenerated Sat Apr 23 11:20:58 CST 2016
     */
    List<SysPaychannelBanks> selectByExample(SysPaychannelBanksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_paychannel_banks
     *
     * @mbggenerated Sat Apr 23 11:20:58 CST 2016
     */
    SysPaychannelBanks selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_paychannel_banks
     *
     * @mbggenerated Sat Apr 23 11:20:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") SysPaychannelBanks record, @Param("example") SysPaychannelBanksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_paychannel_banks
     *
     * @mbggenerated Sat Apr 23 11:20:58 CST 2016
     */
    int updateByExample(@Param("record") SysPaychannelBanks record, @Param("example") SysPaychannelBanksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_paychannel_banks
     *
     * @mbggenerated Sat Apr 23 11:20:58 CST 2016
     */
    int updateByPrimaryKeySelective(SysPaychannelBanks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_paychannel_banks
     *
     * @mbggenerated Sat Apr 23 11:20:58 CST 2016
     */
    int updateByPrimaryKey(SysPaychannelBanks record);
//    /**
//     * 查询通联支持的银行列表，并将代码转换为明文
//     * @return
//     */
//	List<HashMap<String, Object>> selectBankList();
}