package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.SysTransportStation;
import com.dlfc.zfgj.entity.SysTransportStationExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@MyBatisDao
public interface SysTransportStationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_transport_station
     *
     * @mbggenerated Sat Apr 23 14:08:11 CST 2016
     */
    int countByExample(SysTransportStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_transport_station
     *
     * @mbggenerated Sat Apr 23 14:08:11 CST 2016
     */
    int deleteByExample(SysTransportStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_transport_station
     *
     * @mbggenerated Sat Apr 23 14:08:11 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_transport_station
     *
     * @mbggenerated Sat Apr 23 14:08:11 CST 2016
     */
    int insert(SysTransportStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_transport_station
     *
     * @mbggenerated Sat Apr 23 14:08:11 CST 2016
     */
    int insertSelective(SysTransportStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_transport_station
     *
     * @mbggenerated Sat Apr 23 14:08:11 CST 2016
     */
    List<SysTransportStation> selectByExample(SysTransportStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_transport_station
     *
     * @mbggenerated Sat Apr 23 14:08:11 CST 2016
     */
    SysTransportStation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_transport_station
     *
     * @mbggenerated Sat Apr 23 14:08:11 CST 2016
     */
    int updateByExampleSelective(@Param("record") SysTransportStation record, @Param("example") SysTransportStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_transport_station
     *
     * @mbggenerated Sat Apr 23 14:08:11 CST 2016
     */
    int updateByExample(@Param("record") SysTransportStation record, @Param("example") SysTransportStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_transport_station
     *
     * @mbggenerated Sat Apr 23 14:08:11 CST 2016
     */
    int updateByPrimaryKeySelective(SysTransportStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_transport_station
     *
     * @mbggenerated Sat Apr 23 14:08:11 CST 2016
     */
    int updateByPrimaryKey(SysTransportStation record);
    
//    List<SysTransportStation> selectStation(String id);
}