package com.dlfc.zfgj.security.mapper;

import com.dlfc.admin.common.persistence.MyMapper;
import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.security.entity.UsrUser;
import com.dlfc.zfgj.security.entity.UsrUserExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MyBatisDao
public interface UsrUserMapper extends MyMapper<UsrUser> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table usr_user
	 * 
	 * @mbggenerated Thu Nov 05 11:00:14 CST 2015
	 */
	int countByExample(UsrUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table usr_user
	 * 
	 * @mbggenerated Thu Nov 05 11:00:14 CST 2015
	 */
	int deleteByExample(UsrUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table usr_user
	 * 
	 * @mbggenerated Thu Nov 05 11:00:14 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table usr_user
	 * 
	 * @mbggenerated Thu Nov 05 11:00:14 CST 2015
	 */
	int insert(UsrUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table usr_user
	 * 
	 * @mbggenerated Thu Nov 05 11:00:14 CST 2015
	 */
	int insertSelective(UsrUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table usr_user
	 * 
	 * @mbggenerated Thu Nov 05 11:00:14 CST 2015
	 */
	List<UsrUser> selectByExample(UsrUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table usr_user
	 * 
	 * @mbggenerated Thu Nov 05 11:00:14 CST 2015
	 */
	UsrUser selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table usr_user
	 * 
	 * @mbggenerated Thu Nov 05 11:00:14 CST 2015
	 */
	int updateByExampleSelective(@Param("record") UsrUser record, @Param("example") UsrUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table usr_user
	 * 
	 * @mbggenerated Thu Nov 05 11:00:14 CST 2015
	 */
	int updateByExample(@Param("record") UsrUser record, @Param("example") UsrUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table usr_user
	 * 
	 * @mbggenerated Thu Nov 05 11:00:14 CST 2015
	 */
	int updateByPrimaryKeySelective(UsrUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table usr_user
	 * 
	 * @mbggenerated Thu Nov 05 11:00:14 CST 2015
	 */
	int updateByPrimaryKey(UsrUser record);

//	/**
//	 * ，联合查询usr_user,获取系统用户sys_user,以后重构
//	 *
//	 * @param user
//	 * @return
//	 */
//	User getByLoginName(User user);
//
//	int isMailBinded(String email);
//
//	int isMobileBinded(String mobile);
//
//	List<UsrUser> selectAllByExample(UsrUserExample example);
//
//	UsrUser findByPerId(String perId);
//
//	List<UsrUser> selectAllUserInfo(UsrUser UsrUser);
//
//	List<UsrUser> selectAllList(UsrUser usrUser);
//
//	// 根据id取得用户信息
//	UsrUser findById(String id);
//
//	// 通过公司和排序方式查询首页经纪人列表
//	List<UsrUser> getEmpUserList(UsrUser UsrUser);
//
//	// 条件查询获取经纪人列表
//	List<UsrUser> selectUserList(UsrUser UsrUser);
//
//	UsrUser getEmpUser(String eid);
//
//	String getUidByPid(String id);
//
//	String getPidByUid(String uid);
//
//	UsrUser selectUser(String id);
//
//	UsrUser findByUserName(String username);
}