package com.dlfc.zfgj.entity;

import com.dlfc.admin.common.persistence.MyDataEntity;
import java.io.Serializable;

public class AgtRequirementInfo extends MyDataEntity<AgtRequirementInfo> implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_requirement_info.PINDEX
     *
     * @mbggenerated Wed Nov 18 16:55:17 CST 2015
     */
    private Integer pindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_requirement_info.CUSTOMER_ID
     *
     * @mbggenerated Wed Nov 18 16:55:17 CST 2015
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_requirement_info.REQUIREMENT
     *
     * @mbggenerated Wed Nov 18 16:55:17 CST 2015
     */
    private String requirement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table agt_requirement_info
     *
     * @mbggenerated Wed Nov 18 16:55:17 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agt_requirement_info.PINDEX
     *
     * @return the value of agt_requirement_info.PINDEX
     *
     * @mbggenerated Wed Nov 18 16:55:17 CST 2015
     */
    public Integer getPindex() {
        return pindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agt_requirement_info.PINDEX
     *
     * @param pindex the value for agt_requirement_info.PINDEX
     *
     * @mbggenerated Wed Nov 18 16:55:17 CST 2015
     */
    public void setPindex(Integer pindex) {
        this.pindex = pindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agt_requirement_info.CUSTOMER_ID
     *
     * @return the value of agt_requirement_info.CUSTOMER_ID
     *
     * @mbggenerated Wed Nov 18 16:55:17 CST 2015
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agt_requirement_info.CUSTOMER_ID
     *
     * @param customerId the value for agt_requirement_info.CUSTOMER_ID
     *
     * @mbggenerated Wed Nov 18 16:55:17 CST 2015
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agt_requirement_info.REQUIREMENT
     *
     * @return the value of agt_requirement_info.REQUIREMENT
     *
     * @mbggenerated Wed Nov 18 16:55:17 CST 2015
     */
    public String getRequirement() {
        return requirement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agt_requirement_info.REQUIREMENT
     *
     * @param requirement the value for agt_requirement_info.REQUIREMENT
     *
     * @mbggenerated Wed Nov 18 16:55:17 CST 2015
     */
    public void setRequirement(String requirement) {
        this.requirement = requirement == null ? null : requirement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_requirement_info
     *
     * @mbggenerated Wed Nov 18 16:55:17 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pindex=").append(pindex);
        sb.append(", customerId=").append(customerId);
        sb.append(", requirement=").append(requirement);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}