package com.dlfc.zfgj.entity;

import com.dlfc.admin.common.persistence.MyDataEntity;

import java.io.Serializable;
import java.util.List;

public class SysAreaAreas extends MyDataEntity<SysAreaAreas> implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area_areas.ID
     *
     * @mbggenerated Mon Nov 09 16:25:17 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area_areas.AREA_ID
     *
     * @mbggenerated Mon Nov 09 16:25:17 CST 2015
     */
    private String areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area_areas.AREA
     *
     * @mbggenerated Mon Nov 09 16:25:17 CST 2015
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area_areas.CITY_ID
     *
     * @mbggenerated Mon Nov 09 16:25:17 CST 2015
     */
    private String cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area_areas.CREATE_USER
     *
     * @mbggenerated Mon Nov 09 16:25:17 CST 2015
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area_areas.MODIFY_USER
     *
     * @mbggenerated Mon Nov 09 16:25:17 CST 2015
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_area_areas
     *
     * @mbggenerated Mon Nov 09 16:25:17 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area_areas.ID
     *
     * @return the value of sys_area_areas.ID
     *
     * @mbggenerated Mon Nov 09 16:25:17 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area_areas.ID
     *
     * @param id the value for sys_area_areas.ID
     *
     * @mbggenerated Mon Nov 09 16:25:17 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area_areas.AREA_ID
     *
     * @return the value of sys_area_areas.AREA_ID
     *
     * @mbggenerated Mon Nov 09 16:25:17 CST 2015
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area_areas.AREA_ID
     *
     * @param areaId the value for sys_area_areas.AREA_ID
     *
     * @mbggenerated Mon Nov 09 16:25:17 CST 2015
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area_areas.AREA
     *
     * @return the value of sys_area_areas.AREA
     *
     * @mbggenerated Mon Nov 09 16:25:17 CST 2015
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area_areas.AREA
     *
     * @param area the value for sys_area_areas.AREA
     *
     * @mbggenerated Mon Nov 09 16:25:17 CST 2015
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area_areas.CITY_ID
     *
     * @return the value of sys_area_areas.CITY_ID
     *
     * @mbggenerated Mon Nov 09 16:25:17 CST 2015
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area_areas.CITY_ID
     *
     * @param cityId the value for sys_area_areas.CITY_ID
     *
     * @mbggenerated Mon Nov 09 16:25:17 CST 2015
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area_areas.CREATE_USER
     *
     * @return the value of sys_area_areas.CREATE_USER
     *
     * @mbggenerated Mon Nov 09 16:25:17 CST 2015
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area_areas.CREATE_USER
     *
     * @param createUser the value for sys_area_areas.CREATE_USER
     *
     * @mbggenerated Mon Nov 09 16:25:17 CST 2015
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area_areas.MODIFY_USER
     *
     * @return the value of sys_area_areas.MODIFY_USER
     *
     * @mbggenerated Mon Nov 09 16:25:17 CST 2015
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area_areas.MODIFY_USER
     *
     * @param modifyUser the value for sys_area_areas.MODIFY_USER
     *
     * @mbggenerated Mon Nov 09 16:25:17 CST 2015
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area_areas
     *
     * @mbggenerated Mon Nov 09 16:25:17 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", areaId=").append(areaId);
        sb.append(", area=").append(area);
        sb.append(", cityId=").append(cityId);
        sb.append(", createUser=").append(createUser);
        sb.append(", modifyUser=").append(modifyUser);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
    
    //商圈
    private List<SysTradeAreas> areas;

	public List<SysTradeAreas> getAreas() {
		return areas;
	}

	public void setAreas(List<SysTradeAreas> areas) {
		this.areas = areas;
	}
}