package com.dlfc.zfgj.entity;

import com.dlfc.admin.common.persistence.MyDataEntity;
import com.dlfc.zfgj.entity.CmsAdMedia;
import com.dlfc.zfgj.entity.CmsAdHouse;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class CmsAdposition extends MyDataEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adposition.ID
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adposition.PINDEX
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	private Integer pindex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adposition.ENNAME
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	private String enname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adposition.NAME
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adposition.CONTENT
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adposition.DISPLAY_NUMBER
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	private Integer displayNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adposition.STATUS
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adposition.TYPE
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adposition.CREATE_USER
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adposition.CREATE_USER_IDENTITY
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	private Short createUserIdentity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adposition.CREATE_TIME
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adposition.MODIFY_USER
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	private String modifyUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adposition.MODIFY_USER_IDENTITY
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	private Short modifyUserIdentity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adposition.MODIFY_TIME
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	private Date modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adposition.DELETE_FLG
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	private Short deleteFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adposition.VERSION
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cms_adposition
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_adposition.ID
	 * @return  the value of cms_adposition.ID
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_adposition.ID
	 * @param id  the value for cms_adposition.ID
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_adposition.PINDEX
	 * @return  the value of cms_adposition.PINDEX
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public Integer getPindex() {
		return pindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_adposition.PINDEX
	 * @param pindex  the value for cms_adposition.PINDEX
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public void setPindex(Integer pindex) {
		this.pindex = pindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_adposition.ENNAME
	 * @return  the value of cms_adposition.ENNAME
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public String getEnname() {
		return enname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_adposition.ENNAME
	 * @param enname  the value for cms_adposition.ENNAME
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public void setEnname(String enname) {
		this.enname = enname == null ? null : enname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_adposition.NAME
	 * @return  the value of cms_adposition.NAME
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_adposition.NAME
	 * @param name  the value for cms_adposition.NAME
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_adposition.CONTENT
	 * @return  the value of cms_adposition.CONTENT
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_adposition.CONTENT
	 * @param content  the value for cms_adposition.CONTENT
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_adposition.DISPLAY_NUMBER
	 * @return  the value of cms_adposition.DISPLAY_NUMBER
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public Integer getDisplayNumber() {
		return displayNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_adposition.DISPLAY_NUMBER
	 * @param displayNumber  the value for cms_adposition.DISPLAY_NUMBER
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public void setDisplayNumber(Integer displayNumber) {
		this.displayNumber = displayNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_adposition.STATUS
	 * @return  the value of cms_adposition.STATUS
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_adposition.STATUS
	 * @param status  the value for cms_adposition.STATUS
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_adposition.TYPE
	 * @return  the value of cms_adposition.TYPE
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_adposition.TYPE
	 * @param type  the value for cms_adposition.TYPE
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_adposition.CREATE_USER
	 * @return  the value of cms_adposition.CREATE_USER
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_adposition.CREATE_USER
	 * @param createUser  the value for cms_adposition.CREATE_USER
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser == null ? null : createUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_adposition.CREATE_USER_IDENTITY
	 * @return  the value of cms_adposition.CREATE_USER_IDENTITY
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public Short getCreateUserIdentity() {
		return createUserIdentity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_adposition.CREATE_USER_IDENTITY
	 * @param createUserIdentity  the value for cms_adposition.CREATE_USER_IDENTITY
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public void setCreateUserIdentity(Short createUserIdentity) {
		this.createUserIdentity = createUserIdentity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_adposition.CREATE_TIME
	 * @return  the value of cms_adposition.CREATE_TIME
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_adposition.CREATE_TIME
	 * @param createTime  the value for cms_adposition.CREATE_TIME
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_adposition.MODIFY_USER
	 * @return  the value of cms_adposition.MODIFY_USER
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public String getModifyUser() {
		return modifyUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_adposition.MODIFY_USER
	 * @param modifyUser  the value for cms_adposition.MODIFY_USER
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public void setModifyUser(String modifyUser) {
		this.modifyUser = modifyUser == null ? null : modifyUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_adposition.MODIFY_USER_IDENTITY
	 * @return  the value of cms_adposition.MODIFY_USER_IDENTITY
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public Short getModifyUserIdentity() {
		return modifyUserIdentity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_adposition.MODIFY_USER_IDENTITY
	 * @param modifyUserIdentity  the value for cms_adposition.MODIFY_USER_IDENTITY
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public void setModifyUserIdentity(Short modifyUserIdentity) {
		this.modifyUserIdentity = modifyUserIdentity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_adposition.MODIFY_TIME
	 * @return  the value of cms_adposition.MODIFY_TIME
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_adposition.MODIFY_TIME
	 * @param modifyTime  the value for cms_adposition.MODIFY_TIME
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_adposition.DELETE_FLG
	 * @return  the value of cms_adposition.DELETE_FLG
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public Short getDeleteFlg() {
		return deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_adposition.DELETE_FLG
	 * @param deleteFlg  the value for cms_adposition.DELETE_FLG
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public void setDeleteFlg(Short deleteFlg) {
		this.deleteFlg = deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_adposition.VERSION
	 * @return  the value of cms_adposition.VERSION
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_adposition.VERSION
	 * @param version  the value for cms_adposition.VERSION
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_adposition
	 * @mbggenerated  Mon Dec 05 11:17:10 CST 2016
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", pindex=").append(pindex);
		sb.append(", enname=").append(enname);
		sb.append(", name=").append(name);
		sb.append(", content=").append(content);
		sb.append(", displayNumber=").append(displayNumber);
		sb.append(", status=").append(status);
		sb.append(", type=").append(type);
		sb.append(", createUser=").append(createUser);
		sb.append(", createUserIdentity=").append(createUserIdentity);
		sb.append(", createTime=").append(createTime);
		sb.append(", modifyUser=").append(modifyUser);
		sb.append(", modifyUserIdentity=").append(modifyUserIdentity);
		sb.append(", modifyTime=").append(modifyTime);
		sb.append(", deleteFlg=").append(deleteFlg);
		sb.append(", version=").append(version);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
	
	private List<CmsAdHouse> houses;
	
	private List<CmsAdMedia> medias;
	
	public List<CmsAdMedia> getMedias() {
		return medias;
	}
	
	public void setMedias(List<CmsAdMedia> medias) {
		this.medias = medias;
	}
	
	public List<CmsAdHouse> getHouses() {
		return houses;
	}
	
	public void setHouses(List<CmsAdHouse> houses) {
		this.houses = houses;
	}
	
	private String statusName;

	public String getStatusName() {
		return statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}
}