package com.dlfc.zfgj.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.enums.ValuedEnum;
import org.springframework.web.context.request.RequestContextHolder;
import org.springframework.web.context.request.ServletRequestAttributes;

import com.dlfc.admin.common.persistence.MyDataEntity;
import com.dlfc.admin.common.utils.Const;
import com.dlfc.admin.common.utils.DateUtils;
import com.dlfc.admin.common.utils.StringUtils;

public class ConContractTp extends MyDataEntity<ConContractTp> implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.PINDEX
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private Integer pindex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.SOURCE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private Integer source;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.AGENT_STATUS
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private Short agentStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.EID
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String eid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.BEID
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String beid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.CNO
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String cno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.STATUS
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.RENTAL_MODE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private Short rentalMode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.LEASE_PURPOSE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private Short leasePurpose;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.LEASE_DOMAIN
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String leaseDomain;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.LEASE_AREA
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private BigDecimal leaseArea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.LEASE_TERM_YEAR
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private Integer leaseTermYear;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.LEASE_TERM_MONTH
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private Integer leaseTermMonth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.START_TIME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.END_TIME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private Date endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.LESSEE_NAME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String lesseeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.LESSEE_ID_TYPE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private Integer lesseeIdType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.LESSEE_ID_NO
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String lesseeIdNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.LESSEE_MOBILE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String lesseeMobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.LESSEE_ADDRESS
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String lesseeAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.LESSEE_EMAIL
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String lesseeEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.LESSEE_BACKUP_TEL
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String lesseeBackupTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.LESSEE_BACKUP_NAME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String lesseeBackupName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.LESSEE_IDS
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String lesseeIds;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.LESSEE_IDS_OTHER
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String lesseeIdsOther;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.MONTHLY_RENT
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private Integer monthlyRent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.SETTLEMENT_CYCLE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private Integer settlementCycle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.PAY_TIME_MONTH
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private Integer payTimeMonth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.PAY_TIME_DAY
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private Integer payTimeDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.OWNER_BEAR
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String ownerBear;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.OWNER_BEAR_OTHER
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String ownerBearOther;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.DEPOSIT_AMT
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private BigDecimal depositAmt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.PAYMENT_METHOD
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private Short paymentMethod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.LESSOR_NAME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String lessorName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.LESSOR_ID_TYPE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private Integer lessorIdType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.LESSOR_ID_NO
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String lessorIdNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.LESSOR_ADDRESS
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String lessorAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.LESSOR_EMAIL
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String lessorEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.LESSOR_BACKUP_NAME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String lessorBackupName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.LESSOR_BACKUP_TEL
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String lessorBackupTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.LESSOR_MOBILE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String lessorMobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.LESSOR_IDS
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String lessorIds;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.LESSOR_IDS_OTHER
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String lessorIdsOther;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.HOUSE_ADDR
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String houseAddr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.PROPERTY_TYPE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private Integer propertyType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.HOUSE_TYPE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private Integer houseType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.HOUSE_ID_NO
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String houseIdNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.STRUCTURE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private Integer structure;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.BUILDING_AREA
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private BigDecimal buildingArea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.HOUSE_OWNER_NAME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String houseOwnerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.HOUSE_OWNER_ID_TYPE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private Integer houseOwnerIdType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.HOUSE_OWNER_ID_NO
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String houseOwnerIdNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.HOUSE_OWNER_MOBILE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String houseOwnerMobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.PAY_DEPOSIT_TIME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private Date payDepositTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.AGT_NAME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String agtName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.AGT_ID_NO
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String agtIdNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.AGT_TEL
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String agtTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.AGENCY_FEE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private BigDecimal agencyFee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.ADDITIONAL_TERMS
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String additionalTerms;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.AGT_COM_NAME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String agtComName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.AGT_ADDRESS
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String agtAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.AGT_COM_TEL
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String agtComTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.REJECT_REASON
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String rejectReason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.REJECT_REASON_TYPE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private Integer rejectReasonType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.APPROVAL_TIME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private Date approvalTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.APPROVE_REJECT_TIME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private Date approveRejectTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.TO_SPECIAL
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private Integer toSpecial;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.LOCK_USERID
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private String lockUserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_contract_tp.LOCK_TIME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private Date lockTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table con_contract_tp
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.PINDEX
	 * @return  the value of con_contract_tp.PINDEX
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public Integer getPindex() {
		return pindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.PINDEX
	 * @param pindex  the value for con_contract_tp.PINDEX
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setPindex(Integer pindex) {
		this.pindex = pindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.SOURCE
	 * @return  the value of con_contract_tp.SOURCE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public Integer getSource() {
		return source;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.SOURCE
	 * @param source  the value for con_contract_tp.SOURCE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setSource(Integer source) {
		this.source = source;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.AGENT_STATUS
	 * @return  the value of con_contract_tp.AGENT_STATUS
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public Short getAgentStatus() {
		return agentStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.AGENT_STATUS
	 * @param agentStatus  the value for con_contract_tp.AGENT_STATUS
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setAgentStatus(Short agentStatus) {
		this.agentStatus = agentStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.EID
	 * @return  the value of con_contract_tp.EID
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getEid() {
		return eid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.EID
	 * @param eid  the value for con_contract_tp.EID
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setEid(String eid) {
		this.eid = eid == null ? null : eid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.BEID
	 * @return  the value of con_contract_tp.BEID
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getBeid() {
		return beid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.BEID
	 * @param beid  the value for con_contract_tp.BEID
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setBeid(String beid) {
		this.beid = beid == null ? null : beid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.CNO
	 * @return  the value of con_contract_tp.CNO
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getCno() {
		return cno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.CNO
	 * @param cno  the value for con_contract_tp.CNO
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setCno(String cno) {
		this.cno = cno == null ? null : cno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.STATUS
	 * @return  the value of con_contract_tp.STATUS
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.STATUS
	 * @param status  the value for con_contract_tp.STATUS
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.RENTAL_MODE
	 * @return  the value of con_contract_tp.RENTAL_MODE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public Short getRentalMode() {
		return rentalMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.RENTAL_MODE
	 * @param rentalMode  the value for con_contract_tp.RENTAL_MODE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setRentalMode(Short rentalMode) {
		this.rentalMode = rentalMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.LEASE_PURPOSE
	 * @return  the value of con_contract_tp.LEASE_PURPOSE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public Short getLeasePurpose() {
		return leasePurpose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.LEASE_PURPOSE
	 * @param leasePurpose  the value for con_contract_tp.LEASE_PURPOSE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setLeasePurpose(Short leasePurpose) {
		this.leasePurpose = leasePurpose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.LEASE_DOMAIN
	 * @return  the value of con_contract_tp.LEASE_DOMAIN
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getLeaseDomain() {
		return leaseDomain;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.LEASE_DOMAIN
	 * @param leaseDomain  the value for con_contract_tp.LEASE_DOMAIN
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setLeaseDomain(String leaseDomain) {
		this.leaseDomain = leaseDomain == null ? null : leaseDomain.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.LEASE_AREA
	 * @return  the value of con_contract_tp.LEASE_AREA
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public BigDecimal getLeaseArea() {
		return leaseArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.LEASE_AREA
	 * @param leaseArea  the value for con_contract_tp.LEASE_AREA
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setLeaseArea(BigDecimal leaseArea) {
		this.leaseArea = leaseArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.LEASE_TERM_YEAR
	 * @return  the value of con_contract_tp.LEASE_TERM_YEAR
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public Integer getLeaseTermYear() {
		return leaseTermYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.LEASE_TERM_YEAR
	 * @param leaseTermYear  the value for con_contract_tp.LEASE_TERM_YEAR
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setLeaseTermYear(Integer leaseTermYear) {
		this.leaseTermYear = leaseTermYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.LEASE_TERM_MONTH
	 * @return  the value of con_contract_tp.LEASE_TERM_MONTH
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public Integer getLeaseTermMonth() {
		return leaseTermMonth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.LEASE_TERM_MONTH
	 * @param leaseTermMonth  the value for con_contract_tp.LEASE_TERM_MONTH
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setLeaseTermMonth(Integer leaseTermMonth) {
		this.leaseTermMonth = leaseTermMonth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.START_TIME
	 * @return  the value of con_contract_tp.START_TIME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public Date getStartTime() {
		if (!StringUtils.isEmpty(dateStartTime)) {
			startTime = DateUtils.strToDate(dateStartTime, DateUtils.DATE_Y_M_D_PATERN);
		}
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.START_TIME
	 * @param startTime  the value for con_contract_tp.START_TIME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.END_TIME
	 * @return  the value of con_contract_tp.END_TIME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public Date getEndTime() {
		if (!StringUtils.isEmpty(dateEndTime)) {
			endTime = DateUtils.strToDate(dateEndTime, DateUtils.DATE_Y_M_D_PATERN);
		}
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.END_TIME
	 * @param endTime  the value for con_contract_tp.END_TIME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.LESSEE_NAME
	 * @return  the value of con_contract_tp.LESSEE_NAME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getLesseeName() {
		return lesseeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.LESSEE_NAME
	 * @param lesseeName  the value for con_contract_tp.LESSEE_NAME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setLesseeName(String lesseeName) {
		this.lesseeName = lesseeName == null ? null : lesseeName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.LESSEE_ID_TYPE
	 * @return  the value of con_contract_tp.LESSEE_ID_TYPE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public Integer getLesseeIdType() {
		return lesseeIdType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.LESSEE_ID_TYPE
	 * @param lesseeIdType  the value for con_contract_tp.LESSEE_ID_TYPE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setLesseeIdType(Integer lesseeIdType) {
		this.lesseeIdType = lesseeIdType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.LESSEE_ID_NO
	 * @return  the value of con_contract_tp.LESSEE_ID_NO
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getLesseeIdNo() {
		return lesseeIdNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.LESSEE_ID_NO
	 * @param lesseeIdNo  the value for con_contract_tp.LESSEE_ID_NO
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setLesseeIdNo(String lesseeIdNo) {
		this.lesseeIdNo = lesseeIdNo == null ? null : lesseeIdNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.LESSEE_MOBILE
	 * @return  the value of con_contract_tp.LESSEE_MOBILE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getLesseeMobile() {
		return lesseeMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.LESSEE_MOBILE
	 * @param lesseeMobile  the value for con_contract_tp.LESSEE_MOBILE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setLesseeMobile(String lesseeMobile) {
		this.lesseeMobile = lesseeMobile == null ? null : lesseeMobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.LESSEE_ADDRESS
	 * @return  the value of con_contract_tp.LESSEE_ADDRESS
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getLesseeAddress() {
		return lesseeAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.LESSEE_ADDRESS
	 * @param lesseeAddress  the value for con_contract_tp.LESSEE_ADDRESS
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setLesseeAddress(String lesseeAddress) {
		this.lesseeAddress = lesseeAddress == null ? null : lesseeAddress
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.LESSEE_EMAIL
	 * @return  the value of con_contract_tp.LESSEE_EMAIL
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getLesseeEmail() {
		return lesseeEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.LESSEE_EMAIL
	 * @param lesseeEmail  the value for con_contract_tp.LESSEE_EMAIL
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setLesseeEmail(String lesseeEmail) {
		this.lesseeEmail = lesseeEmail == null ? null : lesseeEmail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.LESSEE_BACKUP_TEL
	 * @return  the value of con_contract_tp.LESSEE_BACKUP_TEL
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getLesseeBackupTel() {
		return lesseeBackupTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.LESSEE_BACKUP_TEL
	 * @param lesseeBackupTel  the value for con_contract_tp.LESSEE_BACKUP_TEL
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setLesseeBackupTel(String lesseeBackupTel) {
		this.lesseeBackupTel = lesseeBackupTel == null ? null : lesseeBackupTel
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.LESSEE_BACKUP_NAME
	 * @return  the value of con_contract_tp.LESSEE_BACKUP_NAME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getLesseeBackupName() {
		return lesseeBackupName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.LESSEE_BACKUP_NAME
	 * @param lesseeBackupName  the value for con_contract_tp.LESSEE_BACKUP_NAME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setLesseeBackupName(String lesseeBackupName) {
		this.lesseeBackupName = lesseeBackupName == null ? null
				: lesseeBackupName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.LESSEE_IDS
	 * @return  the value of con_contract_tp.LESSEE_IDS
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getLesseeIds() {
		if (lesseeIdsArray != null && lesseeIdsArray.length > 0) {
			lesseeIds = lesseeIdsArray[0];
			for (int i = 1; i < lesseeIdsArray.length; i++) {
				lesseeIds = lesseeIds + "," + lesseeIdsArray[i];
			}
		}
		return lesseeIds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.LESSEE_IDS
	 * @param lesseeIds  the value for con_contract_tp.LESSEE_IDS
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setLesseeIds(String lesseeIds) {
		this.lesseeIds = lesseeIds == null ? null : lesseeIds.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.LESSEE_IDS_OTHER
	 * @return  the value of con_contract_tp.LESSEE_IDS_OTHER
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getLesseeIdsOther() {
		return lesseeIdsOther;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.LESSEE_IDS_OTHER
	 * @param lesseeIdsOther  the value for con_contract_tp.LESSEE_IDS_OTHER
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setLesseeIdsOther(String lesseeIdsOther) {
		this.lesseeIdsOther = lesseeIdsOther == null ? null : lesseeIdsOther
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.MONTHLY_RENT
	 * @return  the value of con_contract_tp.MONTHLY_RENT
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public Integer getMonthlyRent() {
		return monthlyRent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.MONTHLY_RENT
	 * @param monthlyRent  the value for con_contract_tp.MONTHLY_RENT
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setMonthlyRent(Integer monthlyRent) {
		this.monthlyRent = monthlyRent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.SETTLEMENT_CYCLE
	 * @return  the value of con_contract_tp.SETTLEMENT_CYCLE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public Integer getSettlementCycle() {
		return settlementCycle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.SETTLEMENT_CYCLE
	 * @param settlementCycle  the value for con_contract_tp.SETTLEMENT_CYCLE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setSettlementCycle(Integer settlementCycle) {
		this.settlementCycle = settlementCycle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.PAY_TIME_MONTH
	 * @return  the value of con_contract_tp.PAY_TIME_MONTH
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public Integer getPayTimeMonth() {
		return payTimeMonth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.PAY_TIME_MONTH
	 * @param payTimeMonth  the value for con_contract_tp.PAY_TIME_MONTH
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setPayTimeMonth(Integer payTimeMonth) {
		this.payTimeMonth = payTimeMonth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.PAY_TIME_DAY
	 * @return  the value of con_contract_tp.PAY_TIME_DAY
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public Integer getPayTimeDay() {
		return payTimeDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.PAY_TIME_DAY
	 * @param payTimeDay  the value for con_contract_tp.PAY_TIME_DAY
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setPayTimeDay(Integer payTimeDay) {
		this.payTimeDay = payTimeDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.OWNER_BEAR
	 * @return  the value of con_contract_tp.OWNER_BEAR
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getOwnerBear() {
		if (ownerBears != null && ownerBears.length > 0) {
			ownerBear = ownerBears[0];
			for (int i = 1; i < ownerBears.length; i++) {
				ownerBear = ownerBear + "," + ownerBears[i];
			}
		}
		return ownerBear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.OWNER_BEAR
	 * @param ownerBear  the value for con_contract_tp.OWNER_BEAR
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setOwnerBear(String ownerBear) {
		this.ownerBear = ownerBear == null ? null : ownerBear.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.OWNER_BEAR_OTHER
	 * @return  the value of con_contract_tp.OWNER_BEAR_OTHER
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getOwnerBearOther() {
		return ownerBearOther;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.OWNER_BEAR_OTHER
	 * @param ownerBearOther  the value for con_contract_tp.OWNER_BEAR_OTHER
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setOwnerBearOther(String ownerBearOther) {
		this.ownerBearOther = ownerBearOther == null ? null : ownerBearOther
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.DEPOSIT_AMT
	 * @return  the value of con_contract_tp.DEPOSIT_AMT
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public BigDecimal getDepositAmt() {
		return depositAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.DEPOSIT_AMT
	 * @param depositAmt  the value for con_contract_tp.DEPOSIT_AMT
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setDepositAmt(BigDecimal depositAmt) {
		this.depositAmt = depositAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.PAYMENT_METHOD
	 * @return  the value of con_contract_tp.PAYMENT_METHOD
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public Short getPaymentMethod() {
		return paymentMethod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.PAYMENT_METHOD
	 * @param paymentMethod  the value for con_contract_tp.PAYMENT_METHOD
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setPaymentMethod(Short paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.LESSOR_NAME
	 * @return  the value of con_contract_tp.LESSOR_NAME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getLessorName() {
		return lessorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.LESSOR_NAME
	 * @param lessorName  the value for con_contract_tp.LESSOR_NAME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setLessorName(String lessorName) {
		this.lessorName = lessorName == null ? null : lessorName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.LESSOR_ID_TYPE
	 * @return  the value of con_contract_tp.LESSOR_ID_TYPE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public Integer getLessorIdType() {
		return lessorIdType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.LESSOR_ID_TYPE
	 * @param lessorIdType  the value for con_contract_tp.LESSOR_ID_TYPE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setLessorIdType(Integer lessorIdType) {
		this.lessorIdType = lessorIdType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.LESSOR_ID_NO
	 * @return  the value of con_contract_tp.LESSOR_ID_NO
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getLessorIdNo() {
		return lessorIdNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.LESSOR_ID_NO
	 * @param lessorIdNo  the value for con_contract_tp.LESSOR_ID_NO
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setLessorIdNo(String lessorIdNo) {
		this.lessorIdNo = lessorIdNo == null ? null : lessorIdNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.LESSOR_ADDRESS
	 * @return  the value of con_contract_tp.LESSOR_ADDRESS
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getLessorAddress() {
		return lessorAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.LESSOR_ADDRESS
	 * @param lessorAddress  the value for con_contract_tp.LESSOR_ADDRESS
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setLessorAddress(String lessorAddress) {
		this.lessorAddress = lessorAddress == null ? null : lessorAddress
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.LESSOR_EMAIL
	 * @return  the value of con_contract_tp.LESSOR_EMAIL
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getLessorEmail() {
		return lessorEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.LESSOR_EMAIL
	 * @param lessorEmail  the value for con_contract_tp.LESSOR_EMAIL
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setLessorEmail(String lessorEmail) {
		this.lessorEmail = lessorEmail == null ? null : lessorEmail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.LESSOR_BACKUP_NAME
	 * @return  the value of con_contract_tp.LESSOR_BACKUP_NAME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getLessorBackupName() {
		return lessorBackupName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.LESSOR_BACKUP_NAME
	 * @param lessorBackupName  the value for con_contract_tp.LESSOR_BACKUP_NAME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setLessorBackupName(String lessorBackupName) {
		this.lessorBackupName = lessorBackupName == null ? null
				: lessorBackupName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.LESSOR_BACKUP_TEL
	 * @return  the value of con_contract_tp.LESSOR_BACKUP_TEL
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getLessorBackupTel() {
		return lessorBackupTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.LESSOR_BACKUP_TEL
	 * @param lessorBackupTel  the value for con_contract_tp.LESSOR_BACKUP_TEL
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setLessorBackupTel(String lessorBackupTel) {
		this.lessorBackupTel = lessorBackupTel == null ? null : lessorBackupTel
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.LESSOR_MOBILE
	 * @return  the value of con_contract_tp.LESSOR_MOBILE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getLessorMobile() {
		return lessorMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.LESSOR_MOBILE
	 * @param lessorMobile  the value for con_contract_tp.LESSOR_MOBILE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setLessorMobile(String lessorMobile) {
		this.lessorMobile = lessorMobile == null ? null : lessorMobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.LESSOR_IDS
	 * @return  the value of con_contract_tp.LESSOR_IDS
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getLessorIds() {
		if (lessorIdsArray != null && lessorIdsArray.length > 0) {
			lessorIds = lessorIdsArray[0];
			for (int i = 1; i < lessorIdsArray.length; i++) {
				lessorIds = lessorIds + "," + lessorIdsArray[i];
			}
		}
		return lessorIds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.LESSOR_IDS
	 * @param lessorIds  the value for con_contract_tp.LESSOR_IDS
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setLessorIds(String lessorIds) {
		this.lessorIds = lessorIds == null ? null : lessorIds.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.LESSOR_IDS_OTHER
	 * @return  the value of con_contract_tp.LESSOR_IDS_OTHER
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getLessorIdsOther() {
		return lessorIdsOther;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.LESSOR_IDS_OTHER
	 * @param lessorIdsOther  the value for con_contract_tp.LESSOR_IDS_OTHER
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setLessorIdsOther(String lessorIdsOther) {
		this.lessorIdsOther = lessorIdsOther == null ? null : lessorIdsOther
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.HOUSE_ADDR
	 * @return  the value of con_contract_tp.HOUSE_ADDR
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getHouseAddr() {
		return houseAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.HOUSE_ADDR
	 * @param houseAddr  the value for con_contract_tp.HOUSE_ADDR
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setHouseAddr(String houseAddr) {
		this.houseAddr = houseAddr == null ? null : houseAddr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.PROPERTY_TYPE
	 * @return  the value of con_contract_tp.PROPERTY_TYPE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public Integer getPropertyType() {
		return propertyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.PROPERTY_TYPE
	 * @param propertyType  the value for con_contract_tp.PROPERTY_TYPE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setPropertyType(Integer propertyType) {
		this.propertyType = propertyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.HOUSE_TYPE
	 * @return  the value of con_contract_tp.HOUSE_TYPE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public Integer getHouseType() {
		return houseType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.HOUSE_TYPE
	 * @param houseType  the value for con_contract_tp.HOUSE_TYPE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setHouseType(Integer houseType) {
		this.houseType = houseType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.HOUSE_ID_NO
	 * @return  the value of con_contract_tp.HOUSE_ID_NO
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getHouseIdNo() {
		return houseIdNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.HOUSE_ID_NO
	 * @param houseIdNo  the value for con_contract_tp.HOUSE_ID_NO
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setHouseIdNo(String houseIdNo) {
		this.houseIdNo = houseIdNo == null ? null : houseIdNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.STRUCTURE
	 * @return  the value of con_contract_tp.STRUCTURE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public Integer getStructure() {
		return structure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.STRUCTURE
	 * @param structure  the value for con_contract_tp.STRUCTURE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setStructure(Integer structure) {
		this.structure = structure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.BUILDING_AREA
	 * @return  the value of con_contract_tp.BUILDING_AREA
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public BigDecimal getBuildingArea() {
		return buildingArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.BUILDING_AREA
	 * @param buildingArea  the value for con_contract_tp.BUILDING_AREA
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setBuildingArea(BigDecimal buildingArea) {
		this.buildingArea = buildingArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.HOUSE_OWNER_NAME
	 * @return  the value of con_contract_tp.HOUSE_OWNER_NAME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getHouseOwnerName() {
		return houseOwnerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.HOUSE_OWNER_NAME
	 * @param houseOwnerName  the value for con_contract_tp.HOUSE_OWNER_NAME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setHouseOwnerName(String houseOwnerName) {
		this.houseOwnerName = houseOwnerName == null ? null : houseOwnerName
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.HOUSE_OWNER_ID_TYPE
	 * @return  the value of con_contract_tp.HOUSE_OWNER_ID_TYPE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public Integer getHouseOwnerIdType() {
		return houseOwnerIdType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.HOUSE_OWNER_ID_TYPE
	 * @param houseOwnerIdType  the value for con_contract_tp.HOUSE_OWNER_ID_TYPE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setHouseOwnerIdType(Integer houseOwnerIdType) {
		this.houseOwnerIdType = houseOwnerIdType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.HOUSE_OWNER_ID_NO
	 * @return  the value of con_contract_tp.HOUSE_OWNER_ID_NO
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getHouseOwnerIdNo() {
		return houseOwnerIdNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.HOUSE_OWNER_ID_NO
	 * @param houseOwnerIdNo  the value for con_contract_tp.HOUSE_OWNER_ID_NO
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setHouseOwnerIdNo(String houseOwnerIdNo) {
		this.houseOwnerIdNo = houseOwnerIdNo == null ? null : houseOwnerIdNo
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.HOUSE_OWNER_MOBILE
	 * @return  the value of con_contract_tp.HOUSE_OWNER_MOBILE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getHouseOwnerMobile() {
		return houseOwnerMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.HOUSE_OWNER_MOBILE
	 * @param houseOwnerMobile  the value for con_contract_tp.HOUSE_OWNER_MOBILE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setHouseOwnerMobile(String houseOwnerMobile) {
		this.houseOwnerMobile = houseOwnerMobile == null ? null
				: houseOwnerMobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.PAY_DEPOSIT_TIME
	 * @return  the value of con_contract_tp.PAY_DEPOSIT_TIME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public Date getPayDepositTime() {
		return payDepositTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.PAY_DEPOSIT_TIME
	 * @param payDepositTime  the value for con_contract_tp.PAY_DEPOSIT_TIME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setPayDepositTime(Date payDepositTime) {
		this.payDepositTime = payDepositTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.AGT_NAME
	 * @return  the value of con_contract_tp.AGT_NAME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getAgtName() {
		return agtName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.AGT_NAME
	 * @param agtName  the value for con_contract_tp.AGT_NAME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setAgtName(String agtName) {
		this.agtName = agtName == null ? null : agtName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.AGT_ID_NO
	 * @return  the value of con_contract_tp.AGT_ID_NO
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getAgtIdNo() {
		return agtIdNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.AGT_ID_NO
	 * @param agtIdNo  the value for con_contract_tp.AGT_ID_NO
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setAgtIdNo(String agtIdNo) {
		this.agtIdNo = agtIdNo == null ? null : agtIdNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.AGT_TEL
	 * @return  the value of con_contract_tp.AGT_TEL
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getAgtTel() {
		return agtTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.AGT_TEL
	 * @param agtTel  the value for con_contract_tp.AGT_TEL
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setAgtTel(String agtTel) {
		this.agtTel = agtTel == null ? null : agtTel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.AGENCY_FEE
	 * @return  the value of con_contract_tp.AGENCY_FEE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public BigDecimal getAgencyFee() {
		return agencyFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.AGENCY_FEE
	 * @param agencyFee  the value for con_contract_tp.AGENCY_FEE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setAgencyFee(BigDecimal agencyFee) {
		this.agencyFee = agencyFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.ADDITIONAL_TERMS
	 * @return  the value of con_contract_tp.ADDITIONAL_TERMS
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getAdditionalTerms() {
		return additionalTerms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.ADDITIONAL_TERMS
	 * @param additionalTerms  the value for con_contract_tp.ADDITIONAL_TERMS
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setAdditionalTerms(String additionalTerms) {
		this.additionalTerms = additionalTerms == null ? null : additionalTerms
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.AGT_COM_NAME
	 * @return  the value of con_contract_tp.AGT_COM_NAME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getAgtComName() {
		return agtComName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.AGT_COM_NAME
	 * @param agtComName  the value for con_contract_tp.AGT_COM_NAME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setAgtComName(String agtComName) {
		this.agtComName = agtComName == null ? null : agtComName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.AGT_ADDRESS
	 * @return  the value of con_contract_tp.AGT_ADDRESS
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getAgtAddress() {
		return agtAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.AGT_ADDRESS
	 * @param agtAddress  the value for con_contract_tp.AGT_ADDRESS
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setAgtAddress(String agtAddress) {
		this.agtAddress = agtAddress == null ? null : agtAddress.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.AGT_COM_TEL
	 * @return  the value of con_contract_tp.AGT_COM_TEL
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getAgtComTel() {
		return agtComTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.AGT_COM_TEL
	 * @param agtComTel  the value for con_contract_tp.AGT_COM_TEL
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setAgtComTel(String agtComTel) {
		this.agtComTel = agtComTel == null ? null : agtComTel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.REJECT_REASON
	 * @return  the value of con_contract_tp.REJECT_REASON
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getRejectReason() {
		return rejectReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.REJECT_REASON
	 * @param rejectReason  the value for con_contract_tp.REJECT_REASON
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setRejectReason(String rejectReason) {
		this.rejectReason = rejectReason == null ? null : rejectReason.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.REJECT_REASON_TYPE
	 * @return  the value of con_contract_tp.REJECT_REASON_TYPE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public Integer getRejectReasonType() {
		return rejectReasonType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.REJECT_REASON_TYPE
	 * @param rejectReasonType  the value for con_contract_tp.REJECT_REASON_TYPE
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setRejectReasonType(Integer rejectReasonType) {
		this.rejectReasonType = rejectReasonType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.APPROVAL_TIME
	 * @return  the value of con_contract_tp.APPROVAL_TIME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public Date getApprovalTime() {
		return approvalTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.APPROVAL_TIME
	 * @param approvalTime  the value for con_contract_tp.APPROVAL_TIME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setApprovalTime(Date approvalTime) {
		this.approvalTime = approvalTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.APPROVE_REJECT_TIME
	 * @return  the value of con_contract_tp.APPROVE_REJECT_TIME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public Date getApproveRejectTime() {
		return approveRejectTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.APPROVE_REJECT_TIME
	 * @param approveRejectTime  the value for con_contract_tp.APPROVE_REJECT_TIME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setApproveRejectTime(Date approveRejectTime) {
		this.approveRejectTime = approveRejectTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.TO_SPECIAL
	 * @return  the value of con_contract_tp.TO_SPECIAL
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public Integer getToSpecial() {
		return toSpecial;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.TO_SPECIAL
	 * @param toSpecial  the value for con_contract_tp.TO_SPECIAL
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setToSpecial(Integer toSpecial) {
		this.toSpecial = toSpecial;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.LOCK_USERID
	 * @return  the value of con_contract_tp.LOCK_USERID
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public String getLockUserid() {
		return lockUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.LOCK_USERID
	 * @param lockUserid  the value for con_contract_tp.LOCK_USERID
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setLockUserid(String lockUserid) {
		this.lockUserid = lockUserid == null ? null : lockUserid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_contract_tp.LOCK_TIME
	 * @return  the value of con_contract_tp.LOCK_TIME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public Date getLockTime() {
		return lockTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_contract_tp.LOCK_TIME
	 * @param lockTime  the value for con_contract_tp.LOCK_TIME
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	public void setLockTime(Date lockTime) {
		this.lockTime = lockTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_contract_tp
	 * @mbggenerated  Tue Jul 26 15:14:09 CST 2016
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", pindex=").append(pindex);
		sb.append(", source=").append(source);
		sb.append(", agentStatus=").append(agentStatus);
		sb.append(", eid=").append(eid);
		sb.append(", beid=").append(beid);
		sb.append(", cno=").append(cno);
		sb.append(", status=").append(status);
		sb.append(", rentalMode=").append(rentalMode);
		sb.append(", leasePurpose=").append(leasePurpose);
		sb.append(", leaseDomain=").append(leaseDomain);
		sb.append(", leaseArea=").append(leaseArea);
		sb.append(", leaseTermYear=").append(leaseTermYear);
		sb.append(", leaseTermMonth=").append(leaseTermMonth);
		sb.append(", startTime=").append(startTime);
		sb.append(", endTime=").append(endTime);
		sb.append(", lesseeName=").append(lesseeName);
		sb.append(", lesseeIdType=").append(lesseeIdType);
		sb.append(", lesseeIdNo=").append(lesseeIdNo);
		sb.append(", lesseeMobile=").append(lesseeMobile);
		sb.append(", lesseeAddress=").append(lesseeAddress);
		sb.append(", lesseeEmail=").append(lesseeEmail);
		sb.append(", lesseeBackupTel=").append(lesseeBackupTel);
		sb.append(", lesseeBackupName=").append(lesseeBackupName);
		sb.append(", lesseeIds=").append(lesseeIds);
		sb.append(", lesseeIdsOther=").append(lesseeIdsOther);
		sb.append(", monthlyRent=").append(monthlyRent);
		sb.append(", settlementCycle=").append(settlementCycle);
		sb.append(", payTimeMonth=").append(payTimeMonth);
		sb.append(", payTimeDay=").append(payTimeDay);
		sb.append(", ownerBear=").append(ownerBear);
		sb.append(", ownerBearOther=").append(ownerBearOther);
		sb.append(", depositAmt=").append(depositAmt);
		sb.append(", paymentMethod=").append(paymentMethod);
		sb.append(", lessorName=").append(lessorName);
		sb.append(", lessorIdType=").append(lessorIdType);
		sb.append(", lessorIdNo=").append(lessorIdNo);
		sb.append(", lessorAddress=").append(lessorAddress);
		sb.append(", lessorEmail=").append(lessorEmail);
		sb.append(", lessorBackupName=").append(lessorBackupName);
		sb.append(", lessorBackupTel=").append(lessorBackupTel);
		sb.append(", lessorMobile=").append(lessorMobile);
		sb.append(", lessorIds=").append(lessorIds);
		sb.append(", lessorIdsOther=").append(lessorIdsOther);
		sb.append(", houseAddr=").append(houseAddr);
		sb.append(", propertyType=").append(propertyType);
		sb.append(", houseType=").append(houseType);
		sb.append(", houseIdNo=").append(houseIdNo);
		sb.append(", structure=").append(structure);
		sb.append(", buildingArea=").append(buildingArea);
		sb.append(", houseOwnerName=").append(houseOwnerName);
		sb.append(", houseOwnerIdType=").append(houseOwnerIdType);
		sb.append(", houseOwnerIdNo=").append(houseOwnerIdNo);
		sb.append(", houseOwnerMobile=").append(houseOwnerMobile);
		sb.append(", payDepositTime=").append(payDepositTime);
		sb.append(", agtName=").append(agtName);
		sb.append(", agtIdNo=").append(agtIdNo);
		sb.append(", agtTel=").append(agtTel);
		sb.append(", agencyFee=").append(agencyFee);
		sb.append(", additionalTerms=").append(additionalTerms);
		sb.append(", agtComName=").append(agtComName);
		sb.append(", agtAddress=").append(agtAddress);
		sb.append(", agtComTel=").append(agtComTel);
		sb.append(", rejectReason=").append(rejectReason);
		sb.append(", rejectReasonType=").append(rejectReasonType);
		sb.append(", approvalTime=").append(approvalTime);
		sb.append(", approveRejectTime=").append(approveRejectTime);
		sb.append(", toSpecial=").append(toSpecial);
		sb.append(", lockUserid=").append(lockUserid);
		sb.append(", lockTime=").append(lockTime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * 拒绝类型名称
	 */
	private String rejectReasonTypeName;
	/**
	 * 支付方式名称
	 */
	private String paymentMethodName;
	/**
	 * 租赁用�?名称
	 */
	private String leasePurposeName;
	private String uid;
	private ConDissAgr conDissAgr;
	private ConDepositDistAgr depositDistAgr;
	private int depositType;
	private String dateStartTime;
	private String dateEndTime;
	private String[] ownerBears;
	private List<ConHouseUser> houUserList;
	private List<ConHouseItems> houItemsList;
	private List<SysInfoAtt> infoAttList;
	private List<UsrUserBankcard> userBankcardList;
	private List<ConOtherCosts> conOtherCostsList;
	private String rentalModeName;
	private String rentalPurposeName;
	private String propertyIdTypeName;
	private String settlementCycleName;
	private String lessorIdTypeName;
	private String lesseeIdTypeName;
	private String houseTypeName;
	private ConDeposit conDeposit;
	private List<ConOtherCosts> conOtherCosts;
	private String scope;
	private boolean renewalAble;
	public boolean isRenewalAble() {
		return renewalAble;
	}

	public void setRenewalAble(boolean renewalAble) {
		this.renewalAble = renewalAble;
	}

	private String[] lesseeIdsArray;
	private String[] lessorIdsArray;
	private HouHouseInfo houHouseInfo;
	private List<HouCoOwnerTemp> ownerTempList;
	private List<DateTimeBean> settlementCycleList; // 支付周期明细
	private List<HouCoOwner> houCoOwnerList;

	public String getPaymentMethodName() {
		return paymentMethodName;
	}

	public void setPaymentMethodName(String paymentMethodName) {
		this.paymentMethodName = paymentMethodName;
	}

	public String getLeasePurposeName() {
		return leasePurposeName;
	}

	public void setLeasePurposeName(String leasePurposeName) {
		this.leasePurposeName = leasePurposeName;
	}

	public String getDateStartTime() {
		if (startTime != null) {
			dateStartTime = DateUtils.dateToStr(startTime, DateUtils.DATE_YMD_PATERN);
		}

		return dateStartTime;
	}

	public void setDateStartTime(String dateStartTime) {
		this.dateStartTime = dateStartTime;
	}

	public String getDateEndTime() {
		if (endTime != null) {
			dateEndTime = DateUtils.dateToStr(endTime, DateUtils.DATE_YMD_PATERN);
		}
		return dateEndTime;
	}

	public void setDateEndTime(String dateEndTime) {
		this.dateEndTime = dateEndTime;
	}

	public List<ConHouseUser> getHouUserList() {
		return houUserList;
	}

	public void setHouUserList(List<ConHouseUser> houUserList) {
		this.houUserList = houUserList;
	}

	public ConDissAgr getConDissAgr() {
		return conDissAgr;
	}

	public void setConDissAgr(ConDissAgr conDissAgr) {
		this.conDissAgr = conDissAgr;
	}

	public String[] getOwnerBears() {
		if (ownerBear != null) {
			ownerBears = ownerBear.split(",");
		}
		return ownerBears;
	}

	public void setOwnerBears(String[] ownerBears) {
		this.ownerBears = ownerBears;
	}

	public List<ConHouseItems> getHouItemsList() {
		return houItemsList;
	}

	public void setHouItemsList(List<ConHouseItems> houItemsList) {
		this.houItemsList = houItemsList;
	}

	private ConDepositDistAgr conDepositDistAgr;

	public ConDepositDistAgr getConDepositDistAgr() {
		return conDepositDistAgr;
	}

	public void setConDepositDistAgr(ConDepositDistAgr conDepositDistAgr) {
		this.conDepositDistAgr = conDepositDistAgr;
	}

	public String getRentalModeName() {
		return rentalModeName;
	}

	public void setRentalModeName(String rentalModeName) {
		this.rentalModeName = rentalModeName;
	}

	public String getRentalPurposeName() {
		return rentalPurposeName;
	}

	public void setRentalPurposeName(String rentalPurposeName) {
		this.rentalPurposeName = rentalPurposeName;
	}

	public String getPropertyIdTypeName() {
		return propertyIdTypeName;
	}

	public void setPropertyIdTypeName(String propertyIdTypeName) {
		this.propertyIdTypeName = propertyIdTypeName;
	}

	public String getSettlementCycleName() {
		return settlementCycleName;
	}

	public void setSettlementCycleName(String settlementCycleName) {
		this.settlementCycleName = settlementCycleName;
	}

	private AgtEmpInfo agtEmpInfo;

	public AgtEmpInfo getAgtEmpInfo() {
		return agtEmpInfo;
	}

	public void setAgtEmpInfo(AgtEmpInfo agtEmpInfo) {
		this.agtEmpInfo = agtEmpInfo;
	}

	public String getLessorIdTypeName() {
		return lessorIdTypeName;
	}

	public void setLessorIdTypeName(String lessorIdTypeName) {
		this.lessorIdTypeName = lessorIdTypeName;
	}

	public String getLesseeIdTypeName() {
		return lesseeIdTypeName;
	}

	public void setLesseeIdTypeName(String lesseeIdTypeName) {
		this.lesseeIdTypeName = lesseeIdTypeName;
	}

	public ConDepositDistAgr getDepositDistAgr() {
		return depositDistAgr;
	}

	public void setDepositDistAgr(ConDepositDistAgr depositDistAgr) {
		this.depositDistAgr = depositDistAgr;
	}

	public List<SysInfoAtt> getInfoAttList() {
		return infoAttList;
	}

	public void setInfoAttList(List<SysInfoAtt> infoAttList) {
		this.infoAttList = infoAttList;
	}

	public List<UsrUserBankcard> getUserBankcardList() {
		return userBankcardList;
	}

	public void setUserBankcardList(List<UsrUserBankcard> userBankcardList) {
		this.userBankcardList = userBankcardList;
	}

	public String getScope() {
		return scope;
	}

	public void setScope(String scope) {
		this.scope = scope;
	}

	public int getDepositType() {
		return depositType;
	}

	public void setDepositType(int depositType) {
		this.depositType = depositType;
	}

	public List<HouCoOwner> getHouCoOwnerList() {
		return houCoOwnerList;
	}

	public void setHouCoOwnerList(List<HouCoOwner> houCoOwnerList) {
		this.houCoOwnerList = houCoOwnerList;
	}

	/**
	 * 取得当前用户ID
	 * 
	 * @return
	 */
	public String getCurrUserId() {
		return getSessionAttrStr(Const.SESSION_LOGIN_USER_ID);
	}

	/**
	 * 从session里取得可转化为String类型的�?
	 * 
	 * @param key
	 * @return
	 */
	private String getSessionAttrStr(String key) {
		Object obj = ((ServletRequestAttributes) RequestContextHolder.getRequestAttributes()).getRequest().getSession()
				.getAttribute(key);
		if (obj != null) {
			if (obj instanceof String) {
				return (String) obj;
			} else if (obj instanceof Integer) {
				return String.valueOf(obj);
			} else if (obj instanceof ValuedEnum) {
				return String.valueOf(((ValuedEnum) obj).getValue());
			}
		}

		return "";
	}
	
	public String getUid() {
		return uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public String getRejectReasonTypeName() {
		return rejectReasonTypeName;
	}
	public void setRejectReasonTypeName(String rejectReasonTypeName) {
		this.rejectReasonTypeName = rejectReasonTypeName;
	}
	
	public ConDeposit getConDeposit() {
		return conDeposit;
	}

	public void setConDeposit(ConDeposit conDeposit) {
		this.conDeposit = conDeposit;
	}

	public List<ConOtherCosts> getConOtherCostsList() {
		return conOtherCostsList;
	}

	public void setConOtherCostsList(List<ConOtherCosts> conOtherCostsList) {
		this.conOtherCostsList = conOtherCostsList;
	}	

	public List<ConOtherCosts> getConOtherCosts() {
		return conOtherCosts;
	}

	public void setConOtherCosts(List<ConOtherCosts> conOtherCosts) {
		this.conOtherCosts = conOtherCosts;
	}

	public String[] getLesseeIdsArray() {
		if (lesseeIds != null) {
			lesseeIdsArray = lesseeIds.split(",");
		}
		return lesseeIdsArray;
	}

	public void setLesseeIdsArray(String[] lesseeIdsArray) {
		this.lesseeIdsArray = lesseeIdsArray;
	}

	public String[] getLessorIdsArray() {
		if (lessorIds != null) {
			lessorIdsArray = lessorIds.split(",");
		}
		return lessorIdsArray;
	}

	public void setLessorIdsArray(String[] lessorIdsArray) {
		this.lessorIdsArray = lessorIdsArray;
	}

	public HouHouseInfo getHouHouseInfo() {
		return houHouseInfo;
	}

	public void setHouHouseInfo(HouHouseInfo houHouseInfo) {
		this.houHouseInfo = houHouseInfo;
	}

	public String getHouseTypeName() {
		return houseTypeName;
	}

	public void setHouseTypeName(String houseTypeName) {
		this.houseTypeName = houseTypeName;
	}

	public List<HouCoOwnerTemp> getOwnerTempList() {
		return ownerTempList;
	}

	public void setOwnerTempList(List<HouCoOwnerTemp> ownerTempList) {
		this.ownerTempList = ownerTempList;
	}
	
	public List<DateTimeBean> getSettlementCycleList() {
		return settlementCycleList;
	}

	public void setSettlementCycleList(List<DateTimeBean> settlementCycleList) {
		this.settlementCycleList = settlementCycleList;
	}
}