package com.dlfc.zfgj.entity;

import com.dlfc.admin.common.persistence.MyDataEntity;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ConDepositDistAgr extends MyDataEntity<ConDepositDistAgr> implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_deposit_dist_agr.PINDEX
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	private Integer pindex;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_deposit_dist_agr.TO_SPECIAL
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	private Integer toSpecial;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_deposit_dist_agr.NO
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	private String no;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_deposit_dist_agr.CID
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	private String cid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_deposit_dist_agr.DEPOSIT_AMT
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	private BigDecimal depositAmt;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_deposit_dist_agr.DEDUCT_AMT
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	private BigDecimal deductAmt;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_deposit_dist_agr.DESCRIPTION
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	private String description;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_deposit_dist_agr.STATUS
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	private Short status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_deposit_dist_agr.CHARGE_REASON
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	private Integer chargeReason;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_deposit_dist_agr.REJECT_TYPE
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	private Integer rejectType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_deposit_dist_agr.REJECT_REASON
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	private String rejectReason;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_deposit_dist_agr.LOCK_USERID
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	private String lockUserid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_deposit_dist_agr.LOCK_TIME
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	private Date lockTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table con_deposit_dist_agr
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_deposit_dist_agr.PINDEX
	 * @return  the value of con_deposit_dist_agr.PINDEX
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	public Integer getPindex() {
		return pindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_deposit_dist_agr.PINDEX
	 * @param pindex  the value for con_deposit_dist_agr.PINDEX
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	public void setPindex(Integer pindex) {
		this.pindex = pindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_deposit_dist_agr.TO_SPECIAL
	 * @return  the value of con_deposit_dist_agr.TO_SPECIAL
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	public Integer getToSpecial() {
		return toSpecial;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_deposit_dist_agr.TO_SPECIAL
	 * @param toSpecial  the value for con_deposit_dist_agr.TO_SPECIAL
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	public void setToSpecial(Integer toSpecial) {
		this.toSpecial = toSpecial;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_deposit_dist_agr.NO
	 * @return  the value of con_deposit_dist_agr.NO
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	public String getNo() {
		return no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_deposit_dist_agr.NO
	 * @param no  the value for con_deposit_dist_agr.NO
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	public void setNo(String no) {
		this.no = no == null ? null : no.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_deposit_dist_agr.CID
	 * @return  the value of con_deposit_dist_agr.CID
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	public String getCid() {
		return cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_deposit_dist_agr.CID
	 * @param cid  the value for con_deposit_dist_agr.CID
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	public void setCid(String cid) {
		this.cid = cid == null ? null : cid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_deposit_dist_agr.DEPOSIT_AMT
	 * @return  the value of con_deposit_dist_agr.DEPOSIT_AMT
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	public BigDecimal getDepositAmt() {
		return depositAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_deposit_dist_agr.DEPOSIT_AMT
	 * @param depositAmt  the value for con_deposit_dist_agr.DEPOSIT_AMT
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	public void setDepositAmt(BigDecimal depositAmt) {
		this.depositAmt = depositAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_deposit_dist_agr.DEDUCT_AMT
	 * @return  the value of con_deposit_dist_agr.DEDUCT_AMT
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	public BigDecimal getDeductAmt() {
		return deductAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_deposit_dist_agr.DEDUCT_AMT
	 * @param deductAmt  the value for con_deposit_dist_agr.DEDUCT_AMT
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	public void setDeductAmt(BigDecimal deductAmt) {
		this.deductAmt = deductAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_deposit_dist_agr.DESCRIPTION
	 * @return  the value of con_deposit_dist_agr.DESCRIPTION
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_deposit_dist_agr.DESCRIPTION
	 * @param description  the value for con_deposit_dist_agr.DESCRIPTION
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_deposit_dist_agr.STATUS
	 * @return  the value of con_deposit_dist_agr.STATUS
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_deposit_dist_agr.STATUS
	 * @param status  the value for con_deposit_dist_agr.STATUS
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_deposit_dist_agr.CHARGE_REASON
	 * @return  the value of con_deposit_dist_agr.CHARGE_REASON
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	public Integer getChargeReason() {
		return chargeReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_deposit_dist_agr.CHARGE_REASON
	 * @param chargeReason  the value for con_deposit_dist_agr.CHARGE_REASON
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	public void setChargeReason(Integer chargeReason) {
		this.chargeReason = chargeReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_deposit_dist_agr.REJECT_TYPE
	 * @return  the value of con_deposit_dist_agr.REJECT_TYPE
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	public Integer getRejectType() {
		return rejectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_deposit_dist_agr.REJECT_TYPE
	 * @param rejectType  the value for con_deposit_dist_agr.REJECT_TYPE
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	public void setRejectType(Integer rejectType) {
		this.rejectType = rejectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_deposit_dist_agr.REJECT_REASON
	 * @return  the value of con_deposit_dist_agr.REJECT_REASON
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	public String getRejectReason() {
		return rejectReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_deposit_dist_agr.REJECT_REASON
	 * @param rejectReason  the value for con_deposit_dist_agr.REJECT_REASON
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	public void setRejectReason(String rejectReason) {
		this.rejectReason = rejectReason == null ? null : rejectReason.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_deposit_dist_agr.LOCK_USERID
	 * @return  the value of con_deposit_dist_agr.LOCK_USERID
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	public String getLockUserid() {
		return lockUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_deposit_dist_agr.LOCK_USERID
	 * @param lockUserid  the value for con_deposit_dist_agr.LOCK_USERID
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	public void setLockUserid(String lockUserid) {
		this.lockUserid = lockUserid == null ? null : lockUserid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_deposit_dist_agr.LOCK_TIME
	 * @return  the value of con_deposit_dist_agr.LOCK_TIME
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	public Date getLockTime() {
		return lockTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_deposit_dist_agr.LOCK_TIME
	 * @param lockTime  the value for con_deposit_dist_agr.LOCK_TIME
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	public void setLockTime(Date lockTime) {
		this.lockTime = lockTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_agr
	 * @mbggenerated  Thu Dec 24 09:10:12 CST 2015
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", pindex=").append(pindex);
		sb.append(", toSpecial=").append(toSpecial);
		sb.append(", no=").append(no);
		sb.append(", cid=").append(cid);
		sb.append(", depositAmt=").append(depositAmt);
		sb.append(", deductAmt=").append(deductAmt);
		sb.append(", description=").append(description);
		sb.append(", status=").append(status);
		sb.append(", chargeReason=").append(chargeReason);
		sb.append(", rejectType=").append(rejectType);
		sb.append(", rejectReason=").append(rejectReason);
		sb.append(", lockUserid=").append(lockUserid);
		sb.append(", lockTime=").append(lockTime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	// 收取押金类型
 	private String depositTypeName;
 	
 	private String depositStatusName;
 	
 	private ConContract conContract;
 	
 	public String getDepositTypeName() {
 		return depositTypeName;
 	}

 	public void setDepositTypeName(String depositTypeName) {
 		this.depositTypeName = depositTypeName;
 	}

	public String getDepositStatusName() {
		return depositStatusName;
	}

	public void setDepositStatusName(String depositStatusName) {
		this.depositStatusName = depositStatusName;
	}

	public ConContract getConContract() {
		return conContract;
	}

	public void setConContract(ConContract conContract) {
		this.conContract = conContract;
	}
}