package com.dlfc.zfgj.entity;

import com.dlfc.admin.common.persistence.MyDataEntity;
import com.dlfc.admin.common.utils.ConversionUtils;
import com.dlfc.admin.common.utils.DateUtils;
import com.dlfc.admin.common.utils.IdGen;
import com.dlfc.admin.modules.sys.utils.UserUtils;
import com.dlfc.zfgj.mapper.ConRentstagingLogMapper;
import com.dlfc.zfgj.mapper.ConRentstagingMapper;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ConRentstagingLog extends MyDataEntity<ConRentstagingLog> implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_rentstaging_log.PINDEX
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	private Integer pindex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_rentstaging_log.RENSTAG_ID
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	private String renstagId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_rentstaging_log.CID
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	private String cid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_rentstaging_log.STATUS
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_rentstaging_log.VER
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	private String ver;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_rentstaging_log.NO
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	private String no;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_rentstaging_log.OPERATOR
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	private String operator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_rentstaging_log.OPT_EVENT
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	private Integer optEvent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_rentstaging_log.DCRP
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	private String dcrp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_rentstaging_log.OPT_TIME
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	private Date optTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_rentstaging_log.FEE
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	private BigDecimal fee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_rentstaging_log.AMOUNT
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	private BigDecimal amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_rentstaging_log.INSTALLMENTS
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	private Integer installments;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table con_rentstaging_log
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_rentstaging_log.PINDEX
	 * @return  the value of con_rentstaging_log.PINDEX
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public Integer getPindex() {
		return pindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_rentstaging_log.PINDEX
	 * @param pindex  the value for con_rentstaging_log.PINDEX
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public void setPindex(Integer pindex) {
		this.pindex = pindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_rentstaging_log.RENSTAG_ID
	 * @return  the value of con_rentstaging_log.RENSTAG_ID
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public String getRenstagId() {
		return renstagId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_rentstaging_log.RENSTAG_ID
	 * @param renstagId  the value for con_rentstaging_log.RENSTAG_ID
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public void setRenstagId(String renstagId) {
		this.renstagId = renstagId == null ? null : renstagId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_rentstaging_log.CID
	 * @return  the value of con_rentstaging_log.CID
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public String getCid() {
		return cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_rentstaging_log.CID
	 * @param cid  the value for con_rentstaging_log.CID
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public void setCid(String cid) {
		this.cid = cid == null ? null : cid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_rentstaging_log.STATUS
	 * @return  the value of con_rentstaging_log.STATUS
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_rentstaging_log.STATUS
	 * @param status  the value for con_rentstaging_log.STATUS
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_rentstaging_log.VER
	 * @return  the value of con_rentstaging_log.VER
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public String getVer() {
		return ver;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_rentstaging_log.VER
	 * @param ver  the value for con_rentstaging_log.VER
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public void setVer(String ver) {
		this.ver = ver == null ? null : ver.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_rentstaging_log.NO
	 * @return  the value of con_rentstaging_log.NO
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public String getNo() {
		return no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_rentstaging_log.NO
	 * @param no  the value for con_rentstaging_log.NO
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public void setNo(String no) {
		this.no = no == null ? null : no.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_rentstaging_log.OPERATOR
	 * @return  the value of con_rentstaging_log.OPERATOR
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public String getOperator() {
		return operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_rentstaging_log.OPERATOR
	 * @param operator  the value for con_rentstaging_log.OPERATOR
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public void setOperator(String operator) {
		this.operator = operator == null ? null : operator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_rentstaging_log.OPT_EVENT
	 * @return  the value of con_rentstaging_log.OPT_EVENT
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public Integer getOptEvent() {
		return optEvent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_rentstaging_log.OPT_EVENT
	 * @param optEvent  the value for con_rentstaging_log.OPT_EVENT
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public void setOptEvent(Integer optEvent) {
		this.optEvent = optEvent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_rentstaging_log.DCRP
	 * @return  the value of con_rentstaging_log.DCRP
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public String getDcrp() {
		return dcrp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_rentstaging_log.DCRP
	 * @param dcrp  the value for con_rentstaging_log.DCRP
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public void setDcrp(String dcrp) {
		this.dcrp = dcrp == null ? null : dcrp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_rentstaging_log.OPT_TIME
	 * @return  the value of con_rentstaging_log.OPT_TIME
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public Date getOptTime() {
		return optTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_rentstaging_log.OPT_TIME
	 * @param optTime  the value for con_rentstaging_log.OPT_TIME
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public void setOptTime(Date optTime) {
		this.optTime = optTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_rentstaging_log.FEE
	 * @return  the value of con_rentstaging_log.FEE
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public BigDecimal getFee() {
		return fee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_rentstaging_log.FEE
	 * @param fee  the value for con_rentstaging_log.FEE
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public void setFee(BigDecimal fee) {
		this.fee = fee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_rentstaging_log.AMOUNT
	 * @return  the value of con_rentstaging_log.AMOUNT
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public BigDecimal getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_rentstaging_log.AMOUNT
	 * @param amount  the value for con_rentstaging_log.AMOUNT
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_rentstaging_log.INSTALLMENTS
	 * @return  the value of con_rentstaging_log.INSTALLMENTS
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public Integer getInstallments() {
		return installments;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_rentstaging_log.INSTALLMENTS
	 * @param installments  the value for con_rentstaging_log.INSTALLMENTS
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public void setInstallments(Integer installments) {
		this.installments = installments;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_rentstaging_log
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", pindex=").append(pindex);
		sb.append(", renstagId=").append(renstagId);
		sb.append(", cid=").append(cid);
		sb.append(", status=").append(status);
		sb.append(", ver=").append(ver);
		sb.append(", no=").append(no);
		sb.append(", operator=").append(operator);
		sb.append(", optEvent=").append(optEvent);
		sb.append(", dcrp=").append(dcrp);
		sb.append(", optTime=").append(optTime);
		sb.append(", fee=").append(fee);
		sb.append(", amount=").append(amount);
		sb.append(", installments=").append(installments);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
	
	/**
	 * 保存业务日志
	 * 
	 * @param id 业务报主键ID
	 * @param drcp 操作描述
	 * @param optEvent 操作事件
	 */
	
	public void saveLog (String id, String drcp, int optEvent, ConRentstagingMapper conRentstagingMapper, ConRentstagingLogMapper conRentstagingLogMapper) {
		//插入之后使用id重新查询，获取最新的对象
		ConRentstaging conRentstaging = conRentstagingMapper.selectByPrimaryKey(id);
		//插入日志
		ConversionUtils.reflectionAttr(conRentstaging, this);
		this.setId(IdGen.uuid());
		this.setRenstagId(conRentstaging.getId());
		this.setOperator(UserUtils.getUser().getId());
		this.setOptEvent(optEvent);
		this.setOptTime(DateUtils.getSynchTime());
		this.setDcrp(drcp);
		this.setPindex(null);
		conRentstagingLogMapper.insertSelective(this);
	}
}