package com.dlfc.zfgj.entity;

import com.dlfc.admin.common.persistence.MyDataEntity;

import java.io.Serializable;
import java.math.BigDecimal;

public class ConRentstaging extends MyDataEntity<ConRentstaging> implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_rentstaging.PINDEX
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	private Integer pindex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_rentstaging.CID
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	private String cid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_rentstaging.STATUS
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_rentstaging.VER
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	private String ver;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_rentstaging.NO
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	private String no;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_rentstaging.FEE
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	private BigDecimal fee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_rentstaging.AMOUNT
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	private BigDecimal amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_rentstaging.INSTALLMENTS
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	private Integer installments;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table con_rentstaging
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_rentstaging.PINDEX
	 * @return  the value of con_rentstaging.PINDEX
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public Integer getPindex() {
		return pindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_rentstaging.PINDEX
	 * @param pindex  the value for con_rentstaging.PINDEX
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public void setPindex(Integer pindex) {
		this.pindex = pindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_rentstaging.CID
	 * @return  the value of con_rentstaging.CID
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public String getCid() {
		return cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_rentstaging.CID
	 * @param cid  the value for con_rentstaging.CID
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public void setCid(String cid) {
		this.cid = cid == null ? null : cid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_rentstaging.STATUS
	 * @return  the value of con_rentstaging.STATUS
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_rentstaging.STATUS
	 * @param status  the value for con_rentstaging.STATUS
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_rentstaging.VER
	 * @return  the value of con_rentstaging.VER
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public String getVer() {
		return ver;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_rentstaging.VER
	 * @param ver  the value for con_rentstaging.VER
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public void setVer(String ver) {
		this.ver = ver == null ? null : ver.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_rentstaging.NO
	 * @return  the value of con_rentstaging.NO
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public String getNo() {
		return no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_rentstaging.NO
	 * @param no  the value for con_rentstaging.NO
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public void setNo(String no) {
		this.no = no == null ? null : no.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_rentstaging.FEE
	 * @return  the value of con_rentstaging.FEE
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public BigDecimal getFee() {
		return fee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_rentstaging.FEE
	 * @param fee  the value for con_rentstaging.FEE
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public void setFee(BigDecimal fee) {
		this.fee = fee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_rentstaging.AMOUNT
	 * @return  the value of con_rentstaging.AMOUNT
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public BigDecimal getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_rentstaging.AMOUNT
	 * @param amount  the value for con_rentstaging.AMOUNT
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_rentstaging.INSTALLMENTS
	 * @return  the value of con_rentstaging.INSTALLMENTS
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public Integer getInstallments() {
		return installments;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_rentstaging.INSTALLMENTS
	 * @param installments  the value for con_rentstaging.INSTALLMENTS
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	public void setInstallments(Integer installments) {
		this.installments = installments;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_rentstaging
	 * @mbggenerated  Fri Dec 30 13:53:54 CST 2016
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", pindex=").append(pindex);
		sb.append(", cid=").append(cid);
		sb.append(", status=").append(status);
		sb.append(", ver=").append(ver);
		sb.append(", no=").append(no);
		sb.append(", fee=").append(fee);
		sb.append(", amount=").append(amount);
		sb.append(", installments=").append(installments);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
	
}