package com.dlfc.zfgj.entity;

import com.dlfc.admin.common.persistence.MyDataEntity;

import java.io.Serializable;

public class SssSweepstakesLog extends MyDataEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_sweepstakes_log.PINDEX
     *
     * @mbggenerated Tue Oct 25 16:40:15 CST 2016
     */
    private Integer pindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_sweepstakes_log.UID
     *
     * @mbggenerated Tue Oct 25 16:40:15 CST 2016
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_sweepstakes_log.STATUS
     *
     * @mbggenerated Tue Oct 25 16:40:15 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sss_sweepstakes_log
     *
     * @mbggenerated Tue Oct 25 16:40:15 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_sweepstakes_log.PINDEX
     *
     * @return the value of sss_sweepstakes_log.PINDEX
     *
     * @mbggenerated Tue Oct 25 16:40:15 CST 2016
     */
    public Integer getPindex() {
        return pindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_sweepstakes_log.PINDEX
     *
     * @param pindex the value for sss_sweepstakes_log.PINDEX
     *
     * @mbggenerated Tue Oct 25 16:40:15 CST 2016
     */
    public void setPindex(Integer pindex) {
        this.pindex = pindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_sweepstakes_log.UID
     *
     * @return the value of sss_sweepstakes_log.UID
     *
     * @mbggenerated Tue Oct 25 16:40:15 CST 2016
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_sweepstakes_log.UID
     *
     * @param uid the value for sss_sweepstakes_log.UID
     *
     * @mbggenerated Tue Oct 25 16:40:15 CST 2016
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_sweepstakes_log.STATUS
     *
     * @return the value of sss_sweepstakes_log.STATUS
     *
     * @mbggenerated Tue Oct 25 16:40:15 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_sweepstakes_log.STATUS
     *
     * @param status the value for sss_sweepstakes_log.STATUS
     *
     * @mbggenerated Tue Oct 25 16:40:15 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_sweepstakes_log
     *
     * @mbggenerated Tue Oct 25 16:40:15 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pindex=").append(pindex);
        sb.append(", uid=").append(uid);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}