package com.dlfc.zfgj.entity;

import com.dlfc.admin.common.persistence.MyDataEntity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;

public class SysBroadband extends MyDataEntity<SysBroadband> implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_broadband.PINDEX
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	private Integer pindex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_broadband.NAME
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_broadband.PRICE
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	private BigDecimal price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_broadband.CYCLE
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	private String cycle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_broadband.TYPE
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_broadband.IMG1
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	private String img1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_broadband.IMG2
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	private String img2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_broadband.IMG3
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	private String img3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_broadband.PHONE
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_broadband.ADD1
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	private String add1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_broadband.ADD2
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	private String add2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_broadband.TIME_TYPE
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	private String timeType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_broadband.SALE
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	private BigDecimal sale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_broadband.EPRICE
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	private BigDecimal eprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_broadband.STATUS
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_broadband
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_broadband.PINDEX
	 * @return  the value of sys_broadband.PINDEX
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public Integer getPindex() {
		return pindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_broadband.PINDEX
	 * @param pindex  the value for sys_broadband.PINDEX
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public void setPindex(Integer pindex) {
		this.pindex = pindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_broadband.NAME
	 * @return  the value of sys_broadband.NAME
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_broadband.NAME
	 * @param name  the value for sys_broadband.NAME
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_broadband.PRICE
	 * @return  the value of sys_broadband.PRICE
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_broadband.PRICE
	 * @param price  the value for sys_broadband.PRICE
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_broadband.CYCLE
	 * @return  the value of sys_broadband.CYCLE
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public String getCycle() {
		return cycle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_broadband.CYCLE
	 * @param cycle  the value for sys_broadband.CYCLE
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public void setCycle(String cycle) {
		this.cycle = cycle == null ? null : cycle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_broadband.TYPE
	 * @return  the value of sys_broadband.TYPE
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_broadband.TYPE
	 * @param type  the value for sys_broadband.TYPE
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_broadband.IMG1
	 * @return  the value of sys_broadband.IMG1
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public String getImg1() {
		return img1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_broadband.IMG1
	 * @param img1  the value for sys_broadband.IMG1
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public void setImg1(String img1) {
		this.img1 = img1 == null ? null : img1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_broadband.IMG2
	 * @return  the value of sys_broadband.IMG2
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public String getImg2() {
		return img2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_broadband.IMG2
	 * @param img2  the value for sys_broadband.IMG2
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public void setImg2(String img2) {
		this.img2 = img2 == null ? null : img2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_broadband.IMG3
	 * @return  the value of sys_broadband.IMG3
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public String getImg3() {
		return img3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_broadband.IMG3
	 * @param img3  the value for sys_broadband.IMG3
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public void setImg3(String img3) {
		this.img3 = img3 == null ? null : img3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_broadband.PHONE
	 * @return  the value of sys_broadband.PHONE
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_broadband.PHONE
	 * @param phone  the value for sys_broadband.PHONE
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_broadband.ADD1
	 * @return  the value of sys_broadband.ADD1
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public String getAdd1() {
		return add1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_broadband.ADD1
	 * @param add1  the value for sys_broadband.ADD1
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public void setAdd1(String add1) {
		this.add1 = add1 == null ? null : add1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_broadband.ADD2
	 * @return  the value of sys_broadband.ADD2
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public String getAdd2() {
		return add2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_broadband.ADD2
	 * @param add2  the value for sys_broadband.ADD2
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public void setAdd2(String add2) {
		this.add2 = add2 == null ? null : add2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_broadband.TIME_TYPE
	 * @return  the value of sys_broadband.TIME_TYPE
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public String getTimeType() {
		return timeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_broadband.TIME_TYPE
	 * @param timeType  the value for sys_broadband.TIME_TYPE
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public void setTimeType(String timeType) {
		this.timeType = timeType == null ? null : timeType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_broadband.SALE
	 * @return  the value of sys_broadband.SALE
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public BigDecimal getSale() {
		return sale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_broadband.SALE
	 * @param sale  the value for sys_broadband.SALE
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public void setSale(BigDecimal sale) {
		this.sale = sale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_broadband.EPRICE
	 * @return  the value of sys_broadband.EPRICE
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public BigDecimal getEprice() {
		return eprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_broadband.EPRICE
	 * @param eprice  the value for sys_broadband.EPRICE
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public void setEprice(BigDecimal eprice) {
		this.eprice = eprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_broadband.STATUS
	 * @return  the value of sys_broadband.STATUS
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_broadband.STATUS
	 * @param status  the value for sys_broadband.STATUS
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_broadband
	 * @mbggenerated  Thu Sep 22 09:33:44 CST 2016
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", pindex=").append(pindex);
		sb.append(", name=").append(name);
		sb.append(", price=").append(price);
		sb.append(", cycle=").append(cycle);
		sb.append(", type=").append(type);
		sb.append(", img1=").append(img1);
		sb.append(", img2=").append(img2);
		sb.append(", img3=").append(img3);
		sb.append(", phone=").append(phone);
		sb.append(", add1=").append(add1);
		sb.append(", add2=").append(add2);
		sb.append(", timeType=").append(timeType);
		sb.append(", sale=").append(sale);
		sb.append(", eprice=").append(eprice);
		sb.append(", status=").append(status);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
    
    // sys_code实体
    private SysCode sysCode;

	public SysCode getSysCode() {
		return sysCode;
	}

	public void setSysCode(SysCode sysCode) {
		this.sysCode = sysCode;
	}
	/** 订单号 */
	private String orderNO;
	/** 用户姓名 */
	private String paymentName;
	/** 用户电话 */
	private String paymentTel;
	/** 订单id */
	private String orderId;
	/** 时间轴list */
	private List<SysBroadbandLog> sysBroadbandLogList;
	/** 业务区分编号02宽带03融合 */
	private String bizNo;
	
	/** 业务周期名称 */
	private String bizName;
	
	/** 安装时间 */
	private String installTime;
	/** 周期名称 */
	private String cycleName;
	
	public String getBizName() {
		return bizName;
	}

	public void setBizName(String bizName) {
		this.bizName = bizName;
	}

	public String getInstallTime() {
		return installTime;
	}

	public void setInstallTime(String installTime) {
		this.installTime = installTime;
	}

	public String getOrderId() {
		return orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public String getBizNo() {
		return bizNo;
	}

	public void setBizNo(String bizNo) {
		this.bizNo = bizNo;
	}

	public List<SysBroadbandLog> getSysBroadbandLogList() {
		return sysBroadbandLogList;
	}

	public void setSysBroadbandLogList(List<SysBroadbandLog> sysBroadbandLogList) {
		this.sysBroadbandLogList = sysBroadbandLogList;
	}

	public String getOrderNO() {
		return orderNO;
	}

	public void setOrderNO(String orderNO) {
		this.orderNO = orderNO;
	}

	public String getPaymentName() {
		return paymentName;
	}

	public void setPaymentName(String paymentName) {
		this.paymentName = paymentName;
	}

	public String getPaymentTel() {
		return paymentTel;
	}

	public void setPaymentTel(String paymentTel) {
		this.paymentTel = paymentTel;
	}

	public String getCycleName() {
		return cycleName;
	}

	public void setCycleName(String cycleName) {
		this.cycleName = cycleName;
	}
	
}