package com.dlfc.zfgj.entity;

import com.dlfc.admin.common.persistence.MyDataEntity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysSpecialAuditLogExample extends MyDataEntity<SysSpecialAuditLog> implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_special_audit_log
	 * @mbggenerated  Mon Dec 21 11:22:53 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_special_audit_log
	 * @mbggenerated  Mon Dec 21 11:22:53 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_special_audit_log
	 * @mbggenerated  Mon Dec 21 11:22:53 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_special_audit_log
	 * @mbggenerated  Mon Dec 21 11:22:53 CST 2015
	 */
	public SysSpecialAuditLogExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_special_audit_log
	 * @mbggenerated  Mon Dec 21 11:22:53 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_special_audit_log
	 * @mbggenerated  Mon Dec 21 11:22:53 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_special_audit_log
	 * @mbggenerated  Mon Dec 21 11:22:53 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_special_audit_log
	 * @mbggenerated  Mon Dec 21 11:22:53 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_special_audit_log
	 * @mbggenerated  Mon Dec 21 11:22:53 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_special_audit_log
	 * @mbggenerated  Mon Dec 21 11:22:53 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_special_audit_log
	 * @mbggenerated  Mon Dec 21 11:22:53 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_special_audit_log
	 * @mbggenerated  Mon Dec 21 11:22:53 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_special_audit_log
	 * @mbggenerated  Mon Dec 21 11:22:53 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_special_audit_log
	 * @mbggenerated  Mon Dec 21 11:22:53 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_special_audit_log
	 * @mbggenerated  Mon Dec 21 11:22:53 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andPindexIsNull() {
			addCriterion("PINDEX is null");
			return (Criteria) this;
		}

		public Criteria andPindexIsNotNull() {
			addCriterion("PINDEX is not null");
			return (Criteria) this;
		}

		public Criteria andPindexEqualTo(Integer value) {
			addCriterion("PINDEX =", value, "pindex");
			return (Criteria) this;
		}

		public Criteria andPindexNotEqualTo(Integer value) {
			addCriterion("PINDEX <>", value, "pindex");
			return (Criteria) this;
		}

		public Criteria andPindexGreaterThan(Integer value) {
			addCriterion("PINDEX >", value, "pindex");
			return (Criteria) this;
		}

		public Criteria andPindexGreaterThanOrEqualTo(Integer value) {
			addCriterion("PINDEX >=", value, "pindex");
			return (Criteria) this;
		}

		public Criteria andPindexLessThan(Integer value) {
			addCriterion("PINDEX <", value, "pindex");
			return (Criteria) this;
		}

		public Criteria andPindexLessThanOrEqualTo(Integer value) {
			addCriterion("PINDEX <=", value, "pindex");
			return (Criteria) this;
		}

		public Criteria andPindexIn(List<Integer> values) {
			addCriterion("PINDEX in", values, "pindex");
			return (Criteria) this;
		}

		public Criteria andPindexNotIn(List<Integer> values) {
			addCriterion("PINDEX not in", values, "pindex");
			return (Criteria) this;
		}

		public Criteria andPindexBetween(Integer value1, Integer value2) {
			addCriterion("PINDEX between", value1, value2, "pindex");
			return (Criteria) this;
		}

		public Criteria andPindexNotBetween(Integer value1, Integer value2) {
			addCriterion("PINDEX not between", value1, value2, "pindex");
			return (Criteria) this;
		}

		public Criteria andKeyWordIsNull() {
			addCriterion("KEY_WORD is null");
			return (Criteria) this;
		}

		public Criteria andKeyWordIsNotNull() {
			addCriterion("KEY_WORD is not null");
			return (Criteria) this;
		}

		public Criteria andKeyWordEqualTo(String value) {
			addCriterion("KEY_WORD =", value, "keyWord");
			return (Criteria) this;
		}

		public Criteria andKeyWordNotEqualTo(String value) {
			addCriterion("KEY_WORD <>", value, "keyWord");
			return (Criteria) this;
		}

		public Criteria andKeyWordGreaterThan(String value) {
			addCriterion("KEY_WORD >", value, "keyWord");
			return (Criteria) this;
		}

		public Criteria andKeyWordGreaterThanOrEqualTo(String value) {
			addCriterion("KEY_WORD >=", value, "keyWord");
			return (Criteria) this;
		}

		public Criteria andKeyWordLessThan(String value) {
			addCriterion("KEY_WORD <", value, "keyWord");
			return (Criteria) this;
		}

		public Criteria andKeyWordLessThanOrEqualTo(String value) {
			addCriterion("KEY_WORD <=", value, "keyWord");
			return (Criteria) this;
		}

		public Criteria andKeyWordLike(String value) {
			addCriterion("KEY_WORD like", value, "keyWord");
			return (Criteria) this;
		}

		public Criteria andKeyWordNotLike(String value) {
			addCriterion("KEY_WORD not like", value, "keyWord");
			return (Criteria) this;
		}

		public Criteria andKeyWordIn(List<String> values) {
			addCriterion("KEY_WORD in", values, "keyWord");
			return (Criteria) this;
		}

		public Criteria andKeyWordNotIn(List<String> values) {
			addCriterion("KEY_WORD not in", values, "keyWord");
			return (Criteria) this;
		}

		public Criteria andKeyWordBetween(String value1, String value2) {
			addCriterion("KEY_WORD between", value1, value2, "keyWord");
			return (Criteria) this;
		}

		public Criteria andKeyWordNotBetween(String value1, String value2) {
			addCriterion("KEY_WORD not between", value1, value2, "keyWord");
			return (Criteria) this;
		}

		public Criteria andAuditIdIsNull() {
			addCriterion("AUDIT_ID is null");
			return (Criteria) this;
		}

		public Criteria andAuditIdIsNotNull() {
			addCriterion("AUDIT_ID is not null");
			return (Criteria) this;
		}

		public Criteria andAuditIdEqualTo(String value) {
			addCriterion("AUDIT_ID =", value, "auditId");
			return (Criteria) this;
		}

		public Criteria andAuditIdNotEqualTo(String value) {
			addCriterion("AUDIT_ID <>", value, "auditId");
			return (Criteria) this;
		}

		public Criteria andAuditIdGreaterThan(String value) {
			addCriterion("AUDIT_ID >", value, "auditId");
			return (Criteria) this;
		}

		public Criteria andAuditIdGreaterThanOrEqualTo(String value) {
			addCriterion("AUDIT_ID >=", value, "auditId");
			return (Criteria) this;
		}

		public Criteria andAuditIdLessThan(String value) {
			addCriterion("AUDIT_ID <", value, "auditId");
			return (Criteria) this;
		}

		public Criteria andAuditIdLessThanOrEqualTo(String value) {
			addCriterion("AUDIT_ID <=", value, "auditId");
			return (Criteria) this;
		}

		public Criteria andAuditIdLike(String value) {
			addCriterion("AUDIT_ID like", value, "auditId");
			return (Criteria) this;
		}

		public Criteria andAuditIdNotLike(String value) {
			addCriterion("AUDIT_ID not like", value, "auditId");
			return (Criteria) this;
		}

		public Criteria andAuditIdIn(List<String> values) {
			addCriterion("AUDIT_ID in", values, "auditId");
			return (Criteria) this;
		}

		public Criteria andAuditIdNotIn(List<String> values) {
			addCriterion("AUDIT_ID not in", values, "auditId");
			return (Criteria) this;
		}

		public Criteria andAuditIdBetween(String value1, String value2) {
			addCriterion("AUDIT_ID between", value1, value2, "auditId");
			return (Criteria) this;
		}

		public Criteria andAuditIdNotBetween(String value1, String value2) {
			addCriterion("AUDIT_ID not between", value1, value2, "auditId");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("TYPE is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Integer value) {
			addCriterion("TYPE =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Integer value) {
			addCriterion("TYPE <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Integer value) {
			addCriterion("TYPE >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("TYPE >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Integer value) {
			addCriterion("TYPE <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Integer value) {
			addCriterion("TYPE <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Integer> values) {
			addCriterion("TYPE in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Integer> values) {
			addCriterion("TYPE not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Integer value1, Integer value2) {
			addCriterion("TYPE between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("TYPE not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andFromNameIsNull() {
			addCriterion("FROM_NAME is null");
			return (Criteria) this;
		}

		public Criteria andFromNameIsNotNull() {
			addCriterion("FROM_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andFromNameEqualTo(String value) {
			addCriterion("FROM_NAME =", value, "fromName");
			return (Criteria) this;
		}

		public Criteria andFromNameNotEqualTo(String value) {
			addCriterion("FROM_NAME <>", value, "fromName");
			return (Criteria) this;
		}

		public Criteria andFromNameGreaterThan(String value) {
			addCriterion("FROM_NAME >", value, "fromName");
			return (Criteria) this;
		}

		public Criteria andFromNameGreaterThanOrEqualTo(String value) {
			addCriterion("FROM_NAME >=", value, "fromName");
			return (Criteria) this;
		}

		public Criteria andFromNameLessThan(String value) {
			addCriterion("FROM_NAME <", value, "fromName");
			return (Criteria) this;
		}

		public Criteria andFromNameLessThanOrEqualTo(String value) {
			addCriterion("FROM_NAME <=", value, "fromName");
			return (Criteria) this;
		}

		public Criteria andFromNameLike(String value) {
			addCriterion("FROM_NAME like", value, "fromName");
			return (Criteria) this;
		}

		public Criteria andFromNameNotLike(String value) {
			addCriterion("FROM_NAME not like", value, "fromName");
			return (Criteria) this;
		}

		public Criteria andFromNameIn(List<String> values) {
			addCriterion("FROM_NAME in", values, "fromName");
			return (Criteria) this;
		}

		public Criteria andFromNameNotIn(List<String> values) {
			addCriterion("FROM_NAME not in", values, "fromName");
			return (Criteria) this;
		}

		public Criteria andFromNameBetween(String value1, String value2) {
			addCriterion("FROM_NAME between", value1, value2, "fromName");
			return (Criteria) this;
		}

		public Criteria andFromNameNotBetween(String value1, String value2) {
			addCriterion("FROM_NAME not between", value1, value2, "fromName");
			return (Criteria) this;
		}

		public Criteria andFromDatetimeIsNull() {
			addCriterion("FROM_DATETIME is null");
			return (Criteria) this;
		}

		public Criteria andFromDatetimeIsNotNull() {
			addCriterion("FROM_DATETIME is not null");
			return (Criteria) this;
		}

		public Criteria andFromDatetimeEqualTo(Date value) {
			addCriterion("FROM_DATETIME =", value, "fromDatetime");
			return (Criteria) this;
		}

		public Criteria andFromDatetimeNotEqualTo(Date value) {
			addCriterion("FROM_DATETIME <>", value, "fromDatetime");
			return (Criteria) this;
		}

		public Criteria andFromDatetimeGreaterThan(Date value) {
			addCriterion("FROM_DATETIME >", value, "fromDatetime");
			return (Criteria) this;
		}

		public Criteria andFromDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("FROM_DATETIME >=", value, "fromDatetime");
			return (Criteria) this;
		}

		public Criteria andFromDatetimeLessThan(Date value) {
			addCriterion("FROM_DATETIME <", value, "fromDatetime");
			return (Criteria) this;
		}

		public Criteria andFromDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("FROM_DATETIME <=", value, "fromDatetime");
			return (Criteria) this;
		}

		public Criteria andFromDatetimeIn(List<Date> values) {
			addCriterion("FROM_DATETIME in", values, "fromDatetime");
			return (Criteria) this;
		}

		public Criteria andFromDatetimeNotIn(List<Date> values) {
			addCriterion("FROM_DATETIME not in", values, "fromDatetime");
			return (Criteria) this;
		}

		public Criteria andFromDatetimeBetween(Date value1, Date value2) {
			addCriterion("FROM_DATETIME between", value1, value2, "fromDatetime");
			return (Criteria) this;
		}

		public Criteria andFromDatetimeNotBetween(Date value1, Date value2) {
			addCriterion("FROM_DATETIME not between", value1, value2, "fromDatetime");
			return (Criteria) this;
		}

		public Criteria andInDatetimeIsNull() {
			addCriterion("IN_DATETIME is null");
			return (Criteria) this;
		}

		public Criteria andInDatetimeIsNotNull() {
			addCriterion("IN_DATETIME is not null");
			return (Criteria) this;
		}

		public Criteria andInDatetimeEqualTo(Date value) {
			addCriterion("IN_DATETIME =", value, "inDatetime");
			return (Criteria) this;
		}

		public Criteria andInDatetimeNotEqualTo(Date value) {
			addCriterion("IN_DATETIME <>", value, "inDatetime");
			return (Criteria) this;
		}

		public Criteria andInDatetimeGreaterThan(Date value) {
			addCriterion("IN_DATETIME >", value, "inDatetime");
			return (Criteria) this;
		}

		public Criteria andInDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("IN_DATETIME >=", value, "inDatetime");
			return (Criteria) this;
		}

		public Criteria andInDatetimeLessThan(Date value) {
			addCriterion("IN_DATETIME <", value, "inDatetime");
			return (Criteria) this;
		}

		public Criteria andInDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("IN_DATETIME <=", value, "inDatetime");
			return (Criteria) this;
		}

		public Criteria andInDatetimeIn(List<Date> values) {
			addCriterion("IN_DATETIME in", values, "inDatetime");
			return (Criteria) this;
		}

		public Criteria andInDatetimeNotIn(List<Date> values) {
			addCriterion("IN_DATETIME not in", values, "inDatetime");
			return (Criteria) this;
		}

		public Criteria andInDatetimeBetween(Date value1, Date value2) {
			addCriterion("IN_DATETIME between", value1, value2, "inDatetime");
			return (Criteria) this;
		}

		public Criteria andInDatetimeNotBetween(Date value1, Date value2) {
			addCriterion("IN_DATETIME not between", value1, value2, "inDatetime");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andRejectTypeIsNull() {
			addCriterion("REJECT_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andRejectTypeIsNotNull() {
			addCriterion("REJECT_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andRejectTypeEqualTo(Integer value) {
			addCriterion("REJECT_TYPE =", value, "rejectType");
			return (Criteria) this;
		}

		public Criteria andRejectTypeNotEqualTo(Integer value) {
			addCriterion("REJECT_TYPE <>", value, "rejectType");
			return (Criteria) this;
		}

		public Criteria andRejectTypeGreaterThan(Integer value) {
			addCriterion("REJECT_TYPE >", value, "rejectType");
			return (Criteria) this;
		}

		public Criteria andRejectTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("REJECT_TYPE >=", value, "rejectType");
			return (Criteria) this;
		}

		public Criteria andRejectTypeLessThan(Integer value) {
			addCriterion("REJECT_TYPE <", value, "rejectType");
			return (Criteria) this;
		}

		public Criteria andRejectTypeLessThanOrEqualTo(Integer value) {
			addCriterion("REJECT_TYPE <=", value, "rejectType");
			return (Criteria) this;
		}

		public Criteria andRejectTypeIn(List<Integer> values) {
			addCriterion("REJECT_TYPE in", values, "rejectType");
			return (Criteria) this;
		}

		public Criteria andRejectTypeNotIn(List<Integer> values) {
			addCriterion("REJECT_TYPE not in", values, "rejectType");
			return (Criteria) this;
		}

		public Criteria andRejectTypeBetween(Integer value1, Integer value2) {
			addCriterion("REJECT_TYPE between", value1, value2, "rejectType");
			return (Criteria) this;
		}

		public Criteria andRejectTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("REJECT_TYPE not between", value1, value2, "rejectType");
			return (Criteria) this;
		}

		public Criteria andRejectReasonIsNull() {
			addCriterion("REJECT_REASON is null");
			return (Criteria) this;
		}

		public Criteria andRejectReasonIsNotNull() {
			addCriterion("REJECT_REASON is not null");
			return (Criteria) this;
		}

		public Criteria andRejectReasonEqualTo(String value) {
			addCriterion("REJECT_REASON =", value, "rejectReason");
			return (Criteria) this;
		}

		public Criteria andRejectReasonNotEqualTo(String value) {
			addCriterion("REJECT_REASON <>", value, "rejectReason");
			return (Criteria) this;
		}

		public Criteria andRejectReasonGreaterThan(String value) {
			addCriterion("REJECT_REASON >", value, "rejectReason");
			return (Criteria) this;
		}

		public Criteria andRejectReasonGreaterThanOrEqualTo(String value) {
			addCriterion("REJECT_REASON >=", value, "rejectReason");
			return (Criteria) this;
		}

		public Criteria andRejectReasonLessThan(String value) {
			addCriterion("REJECT_REASON <", value, "rejectReason");
			return (Criteria) this;
		}

		public Criteria andRejectReasonLessThanOrEqualTo(String value) {
			addCriterion("REJECT_REASON <=", value, "rejectReason");
			return (Criteria) this;
		}

		public Criteria andRejectReasonLike(String value) {
			addCriterion("REJECT_REASON like", value, "rejectReason");
			return (Criteria) this;
		}

		public Criteria andRejectReasonNotLike(String value) {
			addCriterion("REJECT_REASON not like", value, "rejectReason");
			return (Criteria) this;
		}

		public Criteria andRejectReasonIn(List<String> values) {
			addCriterion("REJECT_REASON in", values, "rejectReason");
			return (Criteria) this;
		}

		public Criteria andRejectReasonNotIn(List<String> values) {
			addCriterion("REJECT_REASON not in", values, "rejectReason");
			return (Criteria) this;
		}

		public Criteria andRejectReasonBetween(String value1, String value2) {
			addCriterion("REJECT_REASON between", value1, value2, "rejectReason");
			return (Criteria) this;
		}

		public Criteria andRejectReasonNotBetween(String value1, String value2) {
			addCriterion("REJECT_REASON not between", value1, value2, "rejectReason");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNull() {
			addCriterion("CREATE_USER is null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNotNull() {
			addCriterion("CREATE_USER is not null");
			return (Criteria) this;
		}

		public Criteria andCreateUserEqualTo(String value) {
			addCriterion("CREATE_USER =", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotEqualTo(String value) {
			addCriterion("CREATE_USER <>", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThan(String value) {
			addCriterion("CREATE_USER >", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
			addCriterion("CREATE_USER >=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThan(String value) {
			addCriterion("CREATE_USER <", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThanOrEqualTo(String value) {
			addCriterion("CREATE_USER <=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLike(String value) {
			addCriterion("CREATE_USER like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotLike(String value) {
			addCriterion("CREATE_USER not like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserIn(List<String> values) {
			addCriterion("CREATE_USER in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotIn(List<String> values) {
			addCriterion("CREATE_USER not in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserBetween(String value1, String value2) {
			addCriterion("CREATE_USER between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotBetween(String value1, String value2) {
			addCriterion("CREATE_USER not between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityIsNull() {
			addCriterion("CREATE_USER_IDENTITY is null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityIsNotNull() {
			addCriterion("CREATE_USER_IDENTITY is not null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityEqualTo(Short value) {
			addCriterion("CREATE_USER_IDENTITY =", value, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityNotEqualTo(Short value) {
			addCriterion("CREATE_USER_IDENTITY <>", value, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityGreaterThan(Short value) {
			addCriterion("CREATE_USER_IDENTITY >", value, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityGreaterThanOrEqualTo(Short value) {
			addCriterion("CREATE_USER_IDENTITY >=", value, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityLessThan(Short value) {
			addCriterion("CREATE_USER_IDENTITY <", value, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityLessThanOrEqualTo(Short value) {
			addCriterion("CREATE_USER_IDENTITY <=", value, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityIn(List<Short> values) {
			addCriterion("CREATE_USER_IDENTITY in", values, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityNotIn(List<Short> values) {
			addCriterion("CREATE_USER_IDENTITY not in", values, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityBetween(Short value1, Short value2) {
			addCriterion("CREATE_USER_IDENTITY between", value1, value2, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityNotBetween(Short value1, Short value2) {
			addCriterion("CREATE_USER_IDENTITY not between", value1, value2, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifyUserIsNull() {
			addCriterion("MODIFY_USER is null");
			return (Criteria) this;
		}

		public Criteria andModifyUserIsNotNull() {
			addCriterion("MODIFY_USER is not null");
			return (Criteria) this;
		}

		public Criteria andModifyUserEqualTo(String value) {
			addCriterion("MODIFY_USER =", value, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserNotEqualTo(String value) {
			addCriterion("MODIFY_USER <>", value, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserGreaterThan(String value) {
			addCriterion("MODIFY_USER >", value, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserGreaterThanOrEqualTo(String value) {
			addCriterion("MODIFY_USER >=", value, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserLessThan(String value) {
			addCriterion("MODIFY_USER <", value, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserLessThanOrEqualTo(String value) {
			addCriterion("MODIFY_USER <=", value, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserLike(String value) {
			addCriterion("MODIFY_USER like", value, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserNotLike(String value) {
			addCriterion("MODIFY_USER not like", value, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserIn(List<String> values) {
			addCriterion("MODIFY_USER in", values, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserNotIn(List<String> values) {
			addCriterion("MODIFY_USER not in", values, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserBetween(String value1, String value2) {
			addCriterion("MODIFY_USER between", value1, value2, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserNotBetween(String value1, String value2) {
			addCriterion("MODIFY_USER not between", value1, value2, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityIsNull() {
			addCriterion("MODIFY_USER_IDENTITY is null");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityIsNotNull() {
			addCriterion("MODIFY_USER_IDENTITY is not null");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityEqualTo(Short value) {
			addCriterion("MODIFY_USER_IDENTITY =", value, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityNotEqualTo(Short value) {
			addCriterion("MODIFY_USER_IDENTITY <>", value, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityGreaterThan(Short value) {
			addCriterion("MODIFY_USER_IDENTITY >", value, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityGreaterThanOrEqualTo(Short value) {
			addCriterion("MODIFY_USER_IDENTITY >=", value, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityLessThan(Short value) {
			addCriterion("MODIFY_USER_IDENTITY <", value, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityLessThanOrEqualTo(Short value) {
			addCriterion("MODIFY_USER_IDENTITY <=", value, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityIn(List<Short> values) {
			addCriterion("MODIFY_USER_IDENTITY in", values, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityNotIn(List<Short> values) {
			addCriterion("MODIFY_USER_IDENTITY not in", values, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityBetween(Short value1, Short value2) {
			addCriterion("MODIFY_USER_IDENTITY between", value1, value2, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityNotBetween(Short value1, Short value2) {
			addCriterion("MODIFY_USER_IDENTITY not between", value1, value2, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNull() {
			addCriterion("MODIFY_TIME is null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNotNull() {
			addCriterion("MODIFY_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeEqualTo(Date value) {
			addCriterion("MODIFY_TIME =", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotEqualTo(Date value) {
			addCriterion("MODIFY_TIME <>", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThan(Date value) {
			addCriterion("MODIFY_TIME >", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("MODIFY_TIME >=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThan(Date value) {
			addCriterion("MODIFY_TIME <", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
			addCriterion("MODIFY_TIME <=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIn(List<Date> values) {
			addCriterion("MODIFY_TIME in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotIn(List<Date> values) {
			addCriterion("MODIFY_TIME not in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeBetween(Date value1, Date value2) {
			addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
			addCriterion("MODIFY_TIME not between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIsNull() {
			addCriterion("DELETE_FLG is null");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIsNotNull() {
			addCriterion("DELETE_FLG is not null");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgEqualTo(Short value) {
			addCriterion("DELETE_FLG =", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotEqualTo(Short value) {
			addCriterion("DELETE_FLG <>", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgGreaterThan(Short value) {
			addCriterion("DELETE_FLG >", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgGreaterThanOrEqualTo(Short value) {
			addCriterion("DELETE_FLG >=", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgLessThan(Short value) {
			addCriterion("DELETE_FLG <", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgLessThanOrEqualTo(Short value) {
			addCriterion("DELETE_FLG <=", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIn(List<Short> values) {
			addCriterion("DELETE_FLG in", values, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotIn(List<Short> values) {
			addCriterion("DELETE_FLG not in", values, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgBetween(Short value1, Short value2) {
			addCriterion("DELETE_FLG between", value1, value2, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotBetween(Short value1, Short value2) {
			addCriterion("DELETE_FLG not between", value1, value2, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andVersionIsNull() {
			addCriterion("VERSION is null");
			return (Criteria) this;
		}

		public Criteria andVersionIsNotNull() {
			addCriterion("VERSION is not null");
			return (Criteria) this;
		}

		public Criteria andVersionEqualTo(Integer value) {
			addCriterion("VERSION =", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotEqualTo(Integer value) {
			addCriterion("VERSION <>", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThan(Integer value) {
			addCriterion("VERSION >", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
			addCriterion("VERSION >=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThan(Integer value) {
			addCriterion("VERSION <", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThanOrEqualTo(Integer value) {
			addCriterion("VERSION <=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionIn(List<Integer> values) {
			addCriterion("VERSION in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotIn(List<Integer> values) {
			addCriterion("VERSION not in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionBetween(Integer value1, Integer value2) {
			addCriterion("VERSION between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotBetween(Integer value1, Integer value2) {
			addCriterion("VERSION not between", value1, value2, "version");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_special_audit_log
	 * @mbggenerated  Mon Dec 21 11:22:53 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_special_audit_log
     *
     * @mbggenerated do_not_delete_during_merge Mon Dec 21 10:14:53 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}