package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.AgtCertLinkLog;
import com.dlfc.zfgj.entity.AgtCertLinkLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MyBatisDao
public interface AgtCertLinkLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_cert_link_log
	 * @mbggenerated  Wed Dec 23 11:51:31 CST 2015
	 */
	int countByExample(AgtCertLinkLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_cert_link_log
	 * @mbggenerated  Wed Dec 23 11:51:31 CST 2015
	 */
	int deleteByExample(AgtCertLinkLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_cert_link_log
	 * @mbggenerated  Wed Dec 23 11:51:31 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_cert_link_log
	 * @mbggenerated  Wed Dec 23 11:51:31 CST 2015
	 */
	int insert(AgtCertLinkLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_cert_link_log
	 * @mbggenerated  Wed Dec 23 11:51:31 CST 2015
	 */
	int insertSelective(AgtCertLinkLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_cert_link_log
	 * @mbggenerated  Wed Dec 23 11:51:31 CST 2015
	 */
	List<AgtCertLinkLog> selectByExample(AgtCertLinkLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_cert_link_log
	 * @mbggenerated  Wed Dec 23 11:51:31 CST 2015
	 */
	AgtCertLinkLog selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_cert_link_log
	 * @mbggenerated  Wed Dec 23 11:51:31 CST 2015
	 */
	int updateByExampleSelective(@Param("record") AgtCertLinkLog record,
                                 @Param("example") AgtCertLinkLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_cert_link_log
	 * @mbggenerated  Wed Dec 23 11:51:31 CST 2015
	 */
	int updateByExample(@Param("record") AgtCertLinkLog record, @Param("example") AgtCertLinkLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_cert_link_log
	 * @mbggenerated  Wed Dec 23 11:51:31 CST 2015
	 */
	int updateByPrimaryKeySelective(AgtCertLinkLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_cert_link_log
	 * @mbggenerated  Wed Dec 23 11:51:31 CST 2015
	 */
	int updateByPrimaryKey(AgtCertLinkLog record);
}