package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.AgtEmpInfoLog;
import com.dlfc.zfgj.entity.AgtEmpInfoLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MyBatisDao
public interface AgtEmpInfoLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_emp_info_log
     *
     * @mbggenerated Wed Apr 06 14:51:39 CST 2016
     */
    int countByExample(AgtEmpInfoLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_emp_info_log
     *
     * @mbggenerated Wed Apr 06 14:51:39 CST 2016
     */
    int deleteByExample(AgtEmpInfoLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_emp_info_log
     *
     * @mbggenerated Wed Apr 06 14:51:39 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_emp_info_log
     *
     * @mbggenerated Wed Apr 06 14:51:39 CST 2016
     */
    int insert(AgtEmpInfoLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_emp_info_log
     *
     * @mbggenerated Wed Apr 06 14:51:39 CST 2016
     */
    int insertSelective(AgtEmpInfoLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_emp_info_log
     *
     * @mbggenerated Wed Apr 06 14:51:39 CST 2016
     */
    List<AgtEmpInfoLog> selectByExample(AgtEmpInfoLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_emp_info_log
     *
     * @mbggenerated Wed Apr 06 14:51:39 CST 2016
     */
    AgtEmpInfoLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_emp_info_log
     *
     * @mbggenerated Wed Apr 06 14:51:39 CST 2016
     */
    int updateByExampleSelective(@Param("record") AgtEmpInfoLog record, @Param("example") AgtEmpInfoLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_emp_info_log
     *
     * @mbggenerated Wed Apr 06 14:51:39 CST 2016
     */
    int updateByExample(@Param("record") AgtEmpInfoLog record, @Param("example") AgtEmpInfoLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_emp_info_log
     *
     * @mbggenerated Wed Apr 06 14:51:39 CST 2016
     */
    int updateByPrimaryKeySelective(AgtEmpInfoLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_emp_info_log
     *
     * @mbggenerated Wed Apr 06 14:51:39 CST 2016
     */
    int updateByPrimaryKey(AgtEmpInfoLog record);
}