
/**
* @name: CmsArticleMapper.java 
*
* @Copyright: (c) 2016 DLFC. All rights reserved. 
*
* @description: 
*
* @version: 1.0
* @date : 2016年8月12日 
* @author: Liu.Jia 
*
* @Modification  History:<br>
*  Date          Author         Version        Discription
*  2016年8月12日       Liu.Jia        1.0             <修改原因描述>
*/
package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.CmsArticle;
import com.dlfc.zfgj.entity.CmsArticleExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MyBatisDao
public interface CmsArticleMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cms_article
	 *
	 * @mbggenerated Fri Feb 19 14:01:54 CST 2016
	 */
	int countByExample(CmsArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cms_article
	 *
	 * @mbggenerated Fri Feb 19 14:01:54 CST 2016
	 */
	int deleteByExample(CmsArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cms_article
	 *
	 * @mbggenerated Fri Feb 19 14:01:54 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cms_article
	 *
	 * @mbggenerated Fri Feb 19 14:01:54 CST 2016
	 */
	int insert(CmsArticle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cms_article
	 *
	 * @mbggenerated Fri Feb 19 14:01:54 CST 2016
	 */
	int insertSelective(CmsArticle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cms_article
	 *
	 * @mbggenerated Fri Feb 19 14:01:54 CST 2016
	 */
	List<CmsArticle> selectByExampleWithBLOBs(CmsArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cms_article
	 *
	 * @mbggenerated Fri Feb 19 14:01:54 CST 2016
	 */
	List<CmsArticle> selectByExample(CmsArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cms_article
	 *
	 * @mbggenerated Fri Feb 19 14:01:54 CST 2016
	 */
	CmsArticle selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cms_article
	 *
	 * @mbggenerated Fri Feb 19 14:01:54 CST 2016
	 */
	int updateByExampleSelective(@Param("record") CmsArticle record, @Param("example") CmsArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cms_article
	 *
	 * @mbggenerated Fri Feb 19 14:01:54 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") CmsArticle record, @Param("example") CmsArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cms_article
	 *
	 * @mbggenerated Fri Feb 19 14:01:54 CST 2016
	 */
	int updateByExample(@Param("record") CmsArticle record, @Param("example") CmsArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cms_article
	 *
	 * @mbggenerated Fri Feb 19 14:01:54 CST 2016
	 */
	int updateByPrimaryKeySelective(CmsArticle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cms_article
	 *
	 * @mbggenerated Fri Feb 19 14:01:54 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(CmsArticle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cms_article
	 *
	 * @mbggenerated Fri Feb 19 14:01:54 CST 2016
	 */
	int updateByPrimaryKey(CmsArticle record);
//	//获取文章
//	CmsArticle getArticle(CmsArticle article);
//	//获取标题和内容
//	List<CmsArticle> getArticleByCategoryId(CmsArticle article);
//	//获取栏目信息
//	List<CmsArticle> getNotice(CmsArticle article);
//	//获取文章信息
//	List<CmsArticle> getArticleList(CmsArticle article);
//
//	// 获取租房贴士
//	List<CmsArticle> getRentingHint(String id);
//
//	// 获取租房贴士详情
//	List<Map<String, String>> getInfoContent(String id);
//
//	// 贴士分页
//	List<CmsArticle> hallList(CmsArticle cmsArticle);
//
//	// 获取租房网帮助菜单
//	List<Map<String, Object>> getDlfc(String id);
//
//	// 爱看排行榜
//	List<CmsArticle> getHitsList(CmsArticle cmsArticle);

}