package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.CmsSite;
import com.dlfc.zfgj.entity.CmsSiteExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MyBatisDao
public interface CmsSiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_site
     *
     * @mbggenerated Thu Jul 21 16:46:03 CST 2016
     */
    int countByExample(CmsSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_site
     *
     * @mbggenerated Thu Jul 21 16:46:03 CST 2016
     */
    int deleteByExample(CmsSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_site
     *
     * @mbggenerated Thu Jul 21 16:46:03 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_site
     *
     * @mbggenerated Thu Jul 21 16:46:03 CST 2016
     */
    int insert(CmsSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_site
     *
     * @mbggenerated Thu Jul 21 16:46:03 CST 2016
     */
    int insertSelective(CmsSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_site
     *
     * @mbggenerated Thu Jul 21 16:46:03 CST 2016
     */
    List<CmsSite> selectByExampleWithBLOBs(CmsSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_site
     *
     * @mbggenerated Thu Jul 21 16:46:03 CST 2016
     */
    List<CmsSite> selectByExample(CmsSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_site
     *
     * @mbggenerated Thu Jul 21 16:46:03 CST 2016
     */
    CmsSite selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_site
     *
     * @mbggenerated Thu Jul 21 16:46:03 CST 2016
     */
    int updateByExampleSelective(@Param("record") CmsSite record, @Param("example") CmsSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_site
     *
     * @mbggenerated Thu Jul 21 16:46:03 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") CmsSite record, @Param("example") CmsSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_site
     *
     * @mbggenerated Thu Jul 21 16:46:03 CST 2016
     */
    int updateByExample(@Param("record") CmsSite record, @Param("example") CmsSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_site
     *
     * @mbggenerated Thu Jul 21 16:46:03 CST 2016
     */
    int updateByPrimaryKeySelective(CmsSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_site
     *
     * @mbggenerated Thu Jul 21 16:46:03 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(CmsSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_site
     *
     * @mbggenerated Thu Jul 21 16:46:03 CST 2016
     */
    int updateByPrimaryKey(CmsSite record);
}