package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.CmsVoteType;
import com.dlfc.zfgj.entity.CmsVoteTypeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MyBatisDao
public interface CmsVoteTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_vote_type
     *
     * @mbggenerated Tue Jun 07 16:51:32 CST 2016
     */
    int countByExample(CmsVoteTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_vote_type
     *
     * @mbggenerated Tue Jun 07 16:51:32 CST 2016
     */
    int deleteByExample(CmsVoteTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_vote_type
     *
     * @mbggenerated Tue Jun 07 16:51:32 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_vote_type
     *
     * @mbggenerated Tue Jun 07 16:51:32 CST 2016
     */
    int insert(CmsVoteType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_vote_type
     *
     * @mbggenerated Tue Jun 07 16:51:32 CST 2016
     */
    int insertSelective(CmsVoteType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_vote_type
     *
     * @mbggenerated Tue Jun 07 16:51:32 CST 2016
     */
    List<CmsVoteType> selectByExample(CmsVoteTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_vote_type
     *
     * @mbggenerated Tue Jun 07 16:51:32 CST 2016
     */
    CmsVoteType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_vote_type
     *
     * @mbggenerated Tue Jun 07 16:51:32 CST 2016
     */
    int updateByExampleSelective(@Param("record") CmsVoteType record, @Param("example") CmsVoteTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_vote_type
     *
     * @mbggenerated Tue Jun 07 16:51:32 CST 2016
     */
    int updateByExample(@Param("record") CmsVoteType record, @Param("example") CmsVoteTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_vote_type
     *
     * @mbggenerated Tue Jun 07 16:51:32 CST 2016
     */
    int updateByPrimaryKeySelective(CmsVoteType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_vote_type
     *
     * @mbggenerated Tue Jun 07 16:51:32 CST 2016
     */
    int updateByPrimaryKey(CmsVoteType record);
}