package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.MyMapper;
import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.ConContract;
import com.dlfc.zfgj.entity.ConContractExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MyBatisDao
public interface ConContractMapper extends MyMapper<ConContract> {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table con_contract
	 *
	 * @mbggenerated Thu Mar 30 19:15:25 CST 2017
	 */
	int countByExample(ConContractExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table con_contract
	 *
	 * @mbggenerated Thu Mar 30 19:15:25 CST 2017
	 */
	int deleteByExample(ConContractExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table con_contract
	 *
	 * @mbggenerated Thu Mar 30 19:15:25 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table con_contract
	 *
	 * @mbggenerated Thu Mar 30 19:15:25 CST 2017
	 */
	int insert(ConContract record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table con_contract
	 *
	 * @mbggenerated Thu Mar 30 19:15:25 CST 2017
	 */
	int insertSelective(ConContract record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table con_contract
	 *
	 * @mbggenerated Thu Mar 30 19:15:25 CST 2017
	 */
	List<ConContract> selectByExample(ConContractExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table con_contract
	 *
	 * @mbggenerated Thu Mar 30 19:15:25 CST 2017
	 */
	ConContract selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table con_contract
	 *
	 * @mbggenerated Thu Mar 30 19:15:25 CST 2017
	 */
	int updateByExampleSelective(@Param("record") ConContract record, @Param("example") ConContractExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table con_contract
	 *
	 * @mbggenerated Thu Mar 30 19:15:25 CST 2017
	 */
	int updateByExample(@Param("record") ConContract record, @Param("example") ConContractExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table con_contract
	 *
	 * @mbggenerated Thu Mar 30 19:15:25 CST 2017
	 */
	int updateByPrimaryKeySelective(ConContract record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table con_contract
	 *
	 * @mbggenerated Thu Mar 30 19:15:25 CST 2017
	 */
	int updateByPrimaryKey(ConContract record);
//
//	ConContract selectByIdAndStatus(String id);
//
//	ConContract findById(String cid);
//
//	// 查询合同信息
//	List<ConContract> findList(ConContract condition);
//
//	ConContract findOne(String cid);
//
//	int selectStatusByEid(String eid);
//
//	List<ConContract> findByExample(ConContractExample example);
//
//	double getAreaInPeriod(ConContract con);
//
//	List<ConContract> getConInPeriod(ConContract con);
//
//	double getAreaInPeriodLease(ConContract con);
//
//	List<ConContract> getConInPeriodLease(ConContract con);
//	/** 大连市房屋租赁治安责任保证书 */
//	ConContract getGuarantee(String cid);
//
//	/**
//	 * 根据合同id查询合同对象
//	 * @param cid
//	 * @return ConContract对象
//	 * @author LiJianLong
//	 */
//	ConContract findByCid(String cid);
//
//    ConContract selectLatest(String eid);
//
//	List<ConContract> selectContractList(@Param(value = "eid") String eid, @Param(value = "beginPos") int beginPos, @Param(value = "count") int count);
//
//	List<ConContract> selectContractContList(String empId);
}