package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.ConContractV2;
import com.dlfc.zfgj.entity.ConContractV2Example;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MyBatisDao
public interface ConContractV2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_contract_v2
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    int countByExample(ConContractV2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_contract_v2
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    int deleteByExample(ConContractV2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_contract_v2
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_contract_v2
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    int insert(ConContractV2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_contract_v2
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    int insertSelective(ConContractV2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_contract_v2
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    List<ConContractV2> selectByExample(ConContractV2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_contract_v2
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    ConContractV2 selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_contract_v2
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    int updateByExampleSelective(@Param("record") ConContractV2 record, @Param("example") ConContractV2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_contract_v2
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    int updateByExample(@Param("record") ConContractV2 record, @Param("example") ConContractV2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_contract_v2
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    int updateByPrimaryKeySelective(ConContractV2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_contract_v2
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    int updateByPrimaryKey(ConContractV2 record);
//
//    ConContractV2 selectByIdAndStatus(String id);
//
//    ConContractV2 findById(String cid);
//
//    // 查询合同信息
//    List<ConContractV2> findList(ConContractV2 condition);
//
//    ConContractV2 findOne(String cid);
//
//    int selectStatusByEid(String eid);
//
//    List<ConContractV2> findByExample(ConContractV2Example example);
//
//    double getAreaInPeriod(ConContractV2 con);
//
//    List<ConContractV2> getConInPeriod(ConContractV2 con);
//
//    double getAreaInPeriodLease(ConContractV2 con);
//
//    List<ConContractV2> getConInPeriodLease(ConContractV2 con);
//    /** 大连市房屋租赁治安责任保证书 */
//    ConContractV2 getGuarantee(String cid);
//
//    /**
//     * 根据合同id查询合同对象
//     * @param cid
//     * @return ConContractV2对象
//     * @author LiJianLong
//     */
//    ConContractV2 findByCid(String cid);
//
//    ConContractV2 selectLatest(String eid);
//
//    List<ConContractV2> selectContractList(@Param(value = "eid") String eid, @Param(value = "beginPos") int beginPos, @Param(value = "count") int count);
//
//    List<ConContractV2> selectContractContList(String eid);
}