package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.MyMapper;
import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.ConDepositDistAgr;
import com.dlfc.zfgj.entity.ConDepositDistAgrExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MyBatisDao
public interface ConDepositDistAgrMapper extends MyMapper<ConDepositDistAgr> {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_agr
	 * @mbggenerated  Fri Apr 15 09:23:38 CST 2016
	 */
	int countByExample(ConDepositDistAgrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_agr
	 * @mbggenerated  Fri Apr 15 09:23:38 CST 2016
	 */
	int deleteByExample(ConDepositDistAgrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_agr
	 * @mbggenerated  Fri Apr 15 09:23:38 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_agr
	 * @mbggenerated  Fri Apr 15 09:23:38 CST 2016
	 */
	int insert(ConDepositDistAgr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_agr
	 * @mbggenerated  Fri Apr 15 09:23:38 CST 2016
	 */
	int insertSelective(ConDepositDistAgr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_agr
	 * @mbggenerated  Fri Apr 15 09:23:38 CST 2016
	 */
	List<ConDepositDistAgr> selectByExample(ConDepositDistAgrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_agr
	 * @mbggenerated  Fri Apr 15 09:23:38 CST 2016
	 */
	ConDepositDistAgr selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_agr
	 * @mbggenerated  Fri Apr 15 09:23:38 CST 2016
	 */
	int updateByExampleSelective(@Param("record") ConDepositDistAgr record,
                                 @Param("example") ConDepositDistAgrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_agr
	 * @mbggenerated  Fri Apr 15 09:23:38 CST 2016
	 */
	int updateByExample(@Param("record") ConDepositDistAgr record, @Param("example") ConDepositDistAgrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_agr
	 * @mbggenerated  Fri Apr 15 09:23:38 CST 2016
	 */
	int updateByPrimaryKeySelective(ConDepositDistAgr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_agr
	 * @mbggenerated  Fri Apr 15 09:23:38 CST 2016
	 */
	int updateByPrimaryKey(ConDepositDistAgr record);

//	ConDepositDistAgr selectByIdAndStatus(String id);
//
//	ConDepositDistAgr findByCid(String cid);
}