package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.ConHouseUserChildren;
import com.dlfc.zfgj.entity.ConHouseUserChildrenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@MyBatisDao
public interface ConHouseUserChildrenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user_children
     *
     * @mbggenerated Thu Jun 08 10:15:42 CST 2017
     */
    int countByExample(ConHouseUserChildrenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user_children
     *
     * @mbggenerated Thu Jun 08 10:15:42 CST 2017
     */
    int deleteByExample(ConHouseUserChildrenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user_children
     *
     * @mbggenerated Thu Jun 08 10:15:42 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user_children
     *
     * @mbggenerated Thu Jun 08 10:15:42 CST 2017
     */
    int insert(ConHouseUserChildren record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user_children
     *
     * @mbggenerated Thu Jun 08 10:15:42 CST 2017
     */
    int insertSelective(ConHouseUserChildren record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user_children
     *
     * @mbggenerated Thu Jun 08 10:15:42 CST 2017
     */
    List<ConHouseUserChildren> selectByExample(ConHouseUserChildrenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user_children
     *
     * @mbggenerated Thu Jun 08 10:15:42 CST 2017
     */
    ConHouseUserChildren selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user_children
     *
     * @mbggenerated Thu Jun 08 10:15:42 CST 2017
     */
    int updateByExampleSelective(@Param("record") ConHouseUserChildren record, @Param("example") ConHouseUserChildrenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user_children
     *
     * @mbggenerated Thu Jun 08 10:15:42 CST 2017
     */
    int updateByExample(@Param("record") ConHouseUserChildren record, @Param("example") ConHouseUserChildrenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user_children
     *
     * @mbggenerated Thu Jun 08 10:15:42 CST 2017
     */
    int updateByPrimaryKeySelective(ConHouseUserChildren record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user_children
     *
     * @mbggenerated Thu Jun 08 10:15:42 CST 2017
     */
    int updateByPrimaryKey(ConHouseUserChildren record);
}