package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.MyMapper;
import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.ConHouseUser;
import com.dlfc.zfgj.entity.ConHouseUserExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MyBatisDao
public interface ConHouseUserMapper extends MyMapper<ConHouseUser> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_user
	 * @mbggenerated  Tue Feb 23 17:33:53 CST 2016
	 */
	int countByExample(ConHouseUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_user
	 * @mbggenerated  Tue Feb 23 17:33:53 CST 2016
	 */
	int deleteByExample(ConHouseUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_user
	 * @mbggenerated  Tue Feb 23 17:33:53 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_user
	 * @mbggenerated  Tue Feb 23 17:33:53 CST 2016
	 */
	int insert(ConHouseUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_user
	 * @mbggenerated  Tue Feb 23 17:33:53 CST 2016
	 */
	int insertSelective(ConHouseUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_user
	 * @mbggenerated  Tue Feb 23 17:33:53 CST 2016
	 */
	List<ConHouseUser> selectByExample(ConHouseUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_user
	 * @mbggenerated  Tue Feb 23 17:33:53 CST 2016
	 */
	ConHouseUser selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_user
	 * @mbggenerated  Tue Feb 23 17:33:53 CST 2016
	 */
	int updateByExampleSelective(@Param("record") ConHouseUser record, @Param("example") ConHouseUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_user
	 * @mbggenerated  Tue Feb 23 17:33:53 CST 2016
	 */
	int updateByExample(@Param("record") ConHouseUser record, @Param("example") ConHouseUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_user
	 * @mbggenerated  Tue Feb 23 17:33:53 CST 2016
	 */
	int updateByPrimaryKeySelective(ConHouseUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_house_user
	 * @mbggenerated  Tue Feb 23 17:33:53 CST 2016
	 */
	int updateByPrimaryKey(ConHouseUser record);
}