package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.ConHouseUserChildrenLog;
import com.dlfc.zfgj.entity.ConHouseUserChildrenLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@MyBatisDao
public interface ConHouseUserChildrenLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user_children_log
     *
     * @mbggenerated Thu Jun 08 10:18:23 CST 2017
     */
    int countByExample(ConHouseUserChildrenLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user_children_log
     *
     * @mbggenerated Thu Jun 08 10:18:23 CST 2017
     */
    int deleteByExample(ConHouseUserChildrenLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user_children_log
     *
     * @mbggenerated Thu Jun 08 10:18:23 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user_children_log
     *
     * @mbggenerated Thu Jun 08 10:18:23 CST 2017
     */
    int insert(ConHouseUserChildrenLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user_children_log
     *
     * @mbggenerated Thu Jun 08 10:18:23 CST 2017
     */
    int insertSelective(ConHouseUserChildrenLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user_children_log
     *
     * @mbggenerated Thu Jun 08 10:18:23 CST 2017
     */
    List<ConHouseUserChildrenLog> selectByExample(ConHouseUserChildrenLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user_children_log
     *
     * @mbggenerated Thu Jun 08 10:18:23 CST 2017
     */
    ConHouseUserChildrenLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user_children_log
     *
     * @mbggenerated Thu Jun 08 10:18:23 CST 2017
     */
    int updateByExampleSelective(@Param("record") ConHouseUserChildrenLog record, @Param("example") ConHouseUserChildrenLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user_children_log
     *
     * @mbggenerated Thu Jun 08 10:18:23 CST 2017
     */
    int updateByExample(@Param("record") ConHouseUserChildrenLog record, @Param("example") ConHouseUserChildrenLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user_children_log
     *
     * @mbggenerated Thu Jun 08 10:18:23 CST 2017
     */
    int updateByPrimaryKeySelective(ConHouseUserChildrenLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_user_children_log
     *
     * @mbggenerated Thu Jun 08 10:18:23 CST 2017
     */
    int updateByPrimaryKey(ConHouseUserChildrenLog record);
}