package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.MyMapper;
import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.ConHouseItemsLog;
import com.dlfc.zfgj.entity.ConHouseItemsLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MyBatisDao
public interface ConHouseItemsLogMapper extends MyMapper<ConHouseItemsLog> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_items_log
     *
     * @mbggenerated Mon Dec 14 11:05:12 CST 2015
     */
    int countByExample(ConHouseItemsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_items_log
     *
     * @mbggenerated Mon Dec 14 11:05:12 CST 2015
     */
    int deleteByExample(ConHouseItemsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_items_log
     *
     * @mbggenerated Mon Dec 14 11:05:12 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_items_log
     *
     * @mbggenerated Mon Dec 14 11:05:12 CST 2015
     */
    int insert(ConHouseItemsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_items_log
     *
     * @mbggenerated Mon Dec 14 11:05:12 CST 2015
     */
    int insertSelective(ConHouseItemsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_items_log
     *
     * @mbggenerated Mon Dec 14 11:05:12 CST 2015
     */
    List<ConHouseItemsLog> selectByExample(ConHouseItemsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_items_log
     *
     * @mbggenerated Mon Dec 14 11:05:12 CST 2015
     */
    ConHouseItemsLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_items_log
     *
     * @mbggenerated Mon Dec 14 11:05:12 CST 2015
     */
    int updateByExampleSelective(@Param("record") ConHouseItemsLog record, @Param("example") ConHouseItemsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_items_log
     *
     * @mbggenerated Mon Dec 14 11:05:12 CST 2015
     */
    int updateByExample(@Param("record") ConHouseItemsLog record, @Param("example") ConHouseItemsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_items_log
     *
     * @mbggenerated Mon Dec 14 11:05:12 CST 2015
     */
    int updateByPrimaryKeySelective(ConHouseItemsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_house_items_log
     *
     * @mbggenerated Mon Dec 14 11:05:12 CST 2015
     */
    int updateByPrimaryKey(ConHouseItemsLog record);
}