package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.MyMapper;
import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.HouCoOwnerLog;
import com.dlfc.zfgj.entity.HouCoOwnerLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MyBatisDao
public interface HouCoOwnerLogMapper extends MyMapper<HouCoOwnerLog> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_co_owner_log
	 * @mbggenerated  Tue Mar 15 10:50:14 CST 2016
	 */
	int countByExample(HouCoOwnerLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_co_owner_log
	 * @mbggenerated  Tue Mar 15 10:50:14 CST 2016
	 */
	int deleteByExample(HouCoOwnerLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_co_owner_log
	 * @mbggenerated  Tue Mar 15 10:50:14 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_co_owner_log
	 * @mbggenerated  Tue Mar 15 10:50:14 CST 2016
	 */
	int insert(HouCoOwnerLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_co_owner_log
	 * @mbggenerated  Tue Mar 15 10:50:14 CST 2016
	 */
	int insertSelective(HouCoOwnerLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_co_owner_log
	 * @mbggenerated  Tue Mar 15 10:50:14 CST 2016
	 */
	List<HouCoOwnerLog> selectByExample(HouCoOwnerLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_co_owner_log
	 * @mbggenerated  Tue Mar 15 10:50:14 CST 2016
	 */
	HouCoOwnerLog selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_co_owner_log
	 * @mbggenerated  Tue Mar 15 10:50:14 CST 2016
	 */
	int updateByExampleSelective(@Param("record") HouCoOwnerLog record,
                                 @Param("example") HouCoOwnerLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_co_owner_log
	 * @mbggenerated  Tue Mar 15 10:50:14 CST 2016
	 */
	int updateByExample(@Param("record") HouCoOwnerLog record,
                        @Param("example") HouCoOwnerLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_co_owner_log
	 * @mbggenerated  Tue Mar 15 10:50:14 CST 2016
	 */
	int updateByPrimaryKeySelective(HouCoOwnerLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_co_owner_log
	 * @mbggenerated  Tue Mar 15 10:50:14 CST 2016
	 */
	int updateByPrimaryKey(HouCoOwnerLog record);
}