package com.dlfc.zfgj.mapper;

import com.dlfc.zfgj.entity.SysAreaProvinces;
import com.dlfc.zfgj.entity.SysAreaProvincesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysAreaProvincesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area_provinces
     *
     * @mbggenerated Wed May 10 19:18:33 CST 2017
     */
    int countByExample(SysAreaProvincesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area_provinces
     *
     * @mbggenerated Wed May 10 19:18:33 CST 2017
     */
    int deleteByExample(SysAreaProvincesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area_provinces
     *
     * @mbggenerated Wed May 10 19:18:33 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area_provinces
     *
     * @mbggenerated Wed May 10 19:18:33 CST 2017
     */
    int insert(SysAreaProvinces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area_provinces
     *
     * @mbggenerated Wed May 10 19:18:33 CST 2017
     */
    int insertSelective(SysAreaProvinces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area_provinces
     *
     * @mbggenerated Wed May 10 19:18:33 CST 2017
     */
    List<SysAreaProvinces> selectByExample(SysAreaProvincesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area_provinces
     *
     * @mbggenerated Wed May 10 19:18:33 CST 2017
     */
    SysAreaProvinces selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area_provinces
     *
     * @mbggenerated Wed May 10 19:18:33 CST 2017
     */
    int updateByExampleSelective(@Param("record") SysAreaProvinces record, @Param("example") SysAreaProvincesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area_provinces
     *
     * @mbggenerated Wed May 10 19:18:33 CST 2017
     */
    int updateByExample(@Param("record") SysAreaProvinces record, @Param("example") SysAreaProvincesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area_provinces
     *
     * @mbggenerated Wed May 10 19:18:33 CST 2017
     */
    int updateByPrimaryKeySelective(SysAreaProvinces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area_provinces
     *
     * @mbggenerated Wed May 10 19:18:33 CST 2017
     */
    int updateByPrimaryKey(SysAreaProvinces record);
}