package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.SysMobileCapcha;
import com.dlfc.zfgj.entity.SysMobileCapchaExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@MyBatisDao
public interface SysMobileCapchaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mobile_capcha
     *
     * @mbggenerated Fri Mar 31 10:54:56 CST 2017
     */
    int countByExample(SysMobileCapchaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mobile_capcha
     *
     * @mbggenerated Fri Mar 31 10:54:56 CST 2017
     */
    int deleteByExample(SysMobileCapchaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mobile_capcha
     *
     * @mbggenerated Fri Mar 31 10:54:56 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mobile_capcha
     *
     * @mbggenerated Fri Mar 31 10:54:56 CST 2017
     */
    int insert(SysMobileCapcha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mobile_capcha
     *
     * @mbggenerated Fri Mar 31 10:54:56 CST 2017
     */
    int insertSelective(SysMobileCapcha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mobile_capcha
     *
     * @mbggenerated Fri Mar 31 10:54:56 CST 2017
     */
    List<SysMobileCapcha> selectByExample(SysMobileCapchaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mobile_capcha
     *
     * @mbggenerated Fri Mar 31 10:54:56 CST 2017
     */
    SysMobileCapcha selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mobile_capcha
     *
     * @mbggenerated Fri Mar 31 10:54:56 CST 2017
     */
    int updateByExampleSelective(@Param("record") SysMobileCapcha record, @Param("example") SysMobileCapchaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mobile_capcha
     *
     * @mbggenerated Fri Mar 31 10:54:56 CST 2017
     */
    int updateByExample(@Param("record") SysMobileCapcha record, @Param("example") SysMobileCapchaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mobile_capcha
     *
     * @mbggenerated Fri Mar 31 10:54:56 CST 2017
     */
    int updateByPrimaryKeySelective(SysMobileCapcha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mobile_capcha
     *
     * @mbggenerated Fri Mar 31 10:54:56 CST 2017
     */
    int updateByPrimaryKey(SysMobileCapcha record);

//    Integer getCaptchaCountByMobile(SysMobileCapcha record);
//
//    SysMobileCapcha selectByVerCode(SysMobileCapcha record);
}