package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.SysTradeAreas;
import com.dlfc.zfgj.entity.SysTradeAreasExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MyBatisDao
public interface SysTradeAreasMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_trade_areas
	 * @mbggenerated  Fri Apr 08 11:03:12 CST 2016
	 */
	int countByExample(SysTradeAreasExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_trade_areas
	 * @mbggenerated  Fri Apr 08 11:03:12 CST 2016
	 */
	int deleteByExample(SysTradeAreasExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_trade_areas
	 * @mbggenerated  Fri Apr 08 11:03:12 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_trade_areas
	 * @mbggenerated  Fri Apr 08 11:03:12 CST 2016
	 */
	int insert(SysTradeAreas record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_trade_areas
	 * @mbggenerated  Fri Apr 08 11:03:12 CST 2016
	 */
	int insertSelective(SysTradeAreas record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_trade_areas
	 * @mbggenerated  Fri Apr 08 11:03:12 CST 2016
	 */
	List<SysTradeAreas> selectByExample(SysTradeAreasExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_trade_areas
	 * @mbggenerated  Fri Apr 08 11:03:12 CST 2016
	 */
	SysTradeAreas selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_trade_areas
	 * @mbggenerated  Fri Apr 08 11:03:12 CST 2016
	 */
	int updateByExampleSelective(@Param("record") SysTradeAreas record, @Param("example") SysTradeAreasExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_trade_areas
	 * @mbggenerated  Fri Apr 08 11:03:12 CST 2016
	 */
	int updateByExample(@Param("record") SysTradeAreas record, @Param("example") SysTradeAreasExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_trade_areas
	 * @mbggenerated  Fri Apr 08 11:03:12 CST 2016
	 */
	int updateByPrimaryKeySelective(SysTradeAreas record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_trade_areas
	 * @mbggenerated  Fri Apr 08 11:03:12 CST 2016
	 */
	int updateByPrimaryKey(SysTradeAreas record);

//	List<SysTradeAreas> findByParentId(SysTradeAreas record);
//
//	SysTradeAreas findByTradeId(SysTradeAreas record);
}