package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.UsrAccountLog;
import com.dlfc.zfgj.entity.UsrAccountLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MyBatisDao
public interface UsrAccountLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_account_log
     *
     * @mbggenerated Thu Apr 21 11:22:39 CST 2016
     */
    int countByExample(UsrAccountLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_account_log
     *
     * @mbggenerated Thu Apr 21 11:22:39 CST 2016
     */
    int deleteByExample(UsrAccountLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_account_log
     *
     * @mbggenerated Thu Apr 21 11:22:39 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_account_log
     *
     * @mbggenerated Thu Apr 21 11:22:39 CST 2016
     */
    int insert(UsrAccountLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_account_log
     *
     * @mbggenerated Thu Apr 21 11:22:39 CST 2016
     */
    int insertSelective(UsrAccountLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_account_log
     *
     * @mbggenerated Thu Apr 21 11:22:39 CST 2016
     */
    List<UsrAccountLog> selectByExample(UsrAccountLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_account_log
     *
     * @mbggenerated Thu Apr 21 11:22:39 CST 2016
     */
    UsrAccountLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_account_log
     *
     * @mbggenerated Thu Apr 21 11:22:39 CST 2016
     */
    int updateByExampleSelective(@Param("record") UsrAccountLog record, @Param("example") UsrAccountLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_account_log
     *
     * @mbggenerated Thu Apr 21 11:22:39 CST 2016
     */
    int updateByExample(@Param("record") UsrAccountLog record, @Param("example") UsrAccountLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_account_log
     *
     * @mbggenerated Thu Apr 21 11:22:39 CST 2016
     */
    int updateByPrimaryKeySelective(UsrAccountLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_account_log
     *
     * @mbggenerated Thu Apr 21 11:22:39 CST 2016
     */
    int updateByPrimaryKey(UsrAccountLog record);
}