package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.UsrAccount;
import com.dlfc.zfgj.entity.UsrAccountExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MyBatisDao
public interface UsrAccountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr_account
	 * @mbggenerated  Thu Apr 21 11:22:39 CST 2016
	 */
	int countByExample(UsrAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr_account
	 * @mbggenerated  Thu Apr 21 11:22:39 CST 2016
	 */
	int deleteByExample(UsrAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr_account
	 * @mbggenerated  Thu Apr 21 11:22:39 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr_account
	 * @mbggenerated  Thu Apr 21 11:22:39 CST 2016
	 */
	int insert(UsrAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr_account
	 * @mbggenerated  Thu Apr 21 11:22:39 CST 2016
	 */
	int insertSelective(UsrAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr_account
	 * @mbggenerated  Thu Apr 21 11:22:39 CST 2016
	 */
	List<UsrAccount> selectByExample(UsrAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr_account
	 * @mbggenerated  Thu Apr 21 11:22:39 CST 2016
	 */
	UsrAccount selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr_account
	 * @mbggenerated  Thu Apr 21 11:22:39 CST 2016
	 */
	int updateByExampleSelective(@Param("record") UsrAccount record, @Param("example") UsrAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr_account
	 * @mbggenerated  Thu Apr 21 11:22:39 CST 2016
	 */
	int updateByExample(@Param("record") UsrAccount record, @Param("example") UsrAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr_account
	 * @mbggenerated  Thu Apr 21 11:22:39 CST 2016
	 */
	int updateByPrimaryKeySelective(UsrAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr_account
	 * @mbggenerated  Thu Apr 21 11:22:39 CST 2016
	 */
	int updateByPrimaryKey(UsrAccount record);
}