package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.UsrDelInfo;
import com.dlfc.zfgj.entity.UsrDelInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MyBatisDao
public interface UsrDelInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr_del_info
	 * @mbggenerated  Wed Mar 02 20:46:01 CST 2016
	 */
	int countByExample(UsrDelInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr_del_info
	 * @mbggenerated  Wed Mar 02 20:46:01 CST 2016
	 */
	int deleteByExample(UsrDelInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr_del_info
	 * @mbggenerated  Wed Mar 02 20:46:01 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr_del_info
	 * @mbggenerated  Wed Mar 02 20:46:01 CST 2016
	 */
	int insert(UsrDelInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr_del_info
	 * @mbggenerated  Wed Mar 02 20:46:01 CST 2016
	 */
	int insertSelective(UsrDelInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr_del_info
	 * @mbggenerated  Wed Mar 02 20:46:01 CST 2016
	 */
	List<UsrDelInfo> selectByExample(UsrDelInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr_del_info
	 * @mbggenerated  Wed Mar 02 20:46:01 CST 2016
	 */
	UsrDelInfo selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr_del_info
	 * @mbggenerated  Wed Mar 02 20:46:01 CST 2016
	 */
	int updateByExampleSelective(@Param("record") UsrDelInfo record, @Param("example") UsrDelInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr_del_info
	 * @mbggenerated  Wed Mar 02 20:46:01 CST 2016
	 */
	int updateByExample(@Param("record") UsrDelInfo record, @Param("example") UsrDelInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr_del_info
	 * @mbggenerated  Wed Mar 02 20:46:01 CST 2016
	 */
	int updateByPrimaryKeySelective(UsrDelInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr_del_info
	 * @mbggenerated  Wed Mar 02 20:46:01 CST 2016
	 */
	int updateByPrimaryKey(UsrDelInfo record);

//	List<String> selectEmpIdList(String userId);
}