package com.dlfc.zfgj.security.entity;

import com.dlfc.admin.common.persistence.MyDataEntity;
import com.dlfc.admin.common.utils.DateUtils;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class ConContractV2 extends MyDataEntity<ConContractV2> implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.ID
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.PINDEX
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Integer pindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.SOURCE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Integer source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.EID
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.BEID
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String beid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.STATUS
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.RENTAL_MODE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Short rentalMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.LEASE_PURPOSE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Short leasePurpose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.LEASE_DOMAIN
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String leaseDomain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.LEASE_AREA
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private BigDecimal leaseArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.LEASE_TERM_YEAR
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Integer leaseTermYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.LEASE_TERM_MONTH
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Integer leaseTermMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.START_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.END_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.LESSEE_PID
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String lesseePid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.LESSEE_NAME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String lesseeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.LESSEE_ID_TYPE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Integer lesseeIdType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.LESSEE_ID_NO
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String lesseeIdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.LESSEE_MOBILE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String lesseeMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.LESSEE_ADDRESS
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String lesseeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.LESSEE_EMAIL
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String lesseeEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.LESSEE_BACKUP_TEL
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String lesseeBackupTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.LESSEE_BACKUP_NAME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String lesseeBackupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.LESSEE_IDS
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String lesseeIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.LESSEE_IDS_OTHER
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String lesseeIdsOther;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.MONTHLY_RENT
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Integer monthlyRent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.SETTLEMENT_CYCLE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Integer settlementCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.PAY_TIME_MONTH
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Integer payTimeMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.PAY_TIME_DAY
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Integer payTimeDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.OWNER_BEAR
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String ownerBear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.OWNER_BEAR_OTHER
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String ownerBearOther;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.DEPOSIT_AMT
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private BigDecimal depositAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.STAGES
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Integer stages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.PAYMENT_METHOD
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Short paymentMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.LESSOR_PID
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String lessorPid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.LESSOR_NAME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String lessorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.LESSOR_ID_TYPE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Integer lessorIdType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.LESSOR_ID_NO
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String lessorIdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.LESSOR_ADDRESS
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String lessorAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.LESSOR_EMAIL
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String lessorEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.LESSOR_BACKUP_NAME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String lessorBackupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.LESSOR_BACKUP_TEL
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String lessorBackupTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.LESSOR_MOBILE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String lessorMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.LESSOR_IDS
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String lessorIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.LESSOR_IDS_OTHER
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String lessorIdsOther;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.HOUSE_ADDR
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String houseAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.PROPERTY_TYPE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Integer propertyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.HOUSE_TYPE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String houseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.BUILDING_AREA
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private BigDecimal buildingArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.HOUSE_OWNER_PID
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String houseOwnerPid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.HOUSE_OWNER_NAME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String houseOwnerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.HOUSE_OWNER_ID_TYPE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Integer houseOwnerIdType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.HOUSE_OWNER_ID_NO
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String houseOwnerIdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.HOUSE_OWNER_MOBILE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String houseOwnerMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.REJECT_REASON
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String rejectReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.REJECT_REASON_TYPE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Integer rejectReasonType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.CONFIRM_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Date confirmTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.SEND_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.APPROVAL_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Date approvalTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.CANCEL_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Date cancelTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.FINISH_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Date finishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.REJECT_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Date rejectTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.AGENCY_FEE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private BigDecimal agencyFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.NATION
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.HKADR
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String hkadr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.ADDITIONAL_TERMS
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String additionalTerms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.AGT_COM_NAME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String agtComName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.AGT_ADDRESS
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String agtAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.AGT_COM_TEL
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String agtComTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.PROXY_ATT_ID
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String proxyAttId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.CREATE_USER
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.CREATE_USER_IDENTITY
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Short createUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.CREATE_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.MODIFY_USER
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.MODIFY_USER_IDENTITY
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Short modifyUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.MODIFY_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.DELETE_FLG
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Short deleteFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.VERSION
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.HOUSE_STRUCTURE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private Integer houseStructure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_contract_v2.PROPERTY_ID_NO
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    private String propertyIdNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.ID
     *
     * @return the value of con_contract_v2.ID
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.ID
     *
     * @param id the value for con_contract_v2.ID
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.PINDEX
     *
     * @return the value of con_contract_v2.PINDEX
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Integer getPindex() {
        return pindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.PINDEX
     *
     * @param pindex the value for con_contract_v2.PINDEX
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setPindex(Integer pindex) {
        this.pindex = pindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.SOURCE
     *
     * @return the value of con_contract_v2.SOURCE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.SOURCE
     *
     * @param source the value for con_contract_v2.SOURCE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.EID
     *
     * @return the value of con_contract_v2.EID
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.EID
     *
     * @param eid the value for con_contract_v2.EID
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setEid(String eid) {
        this.eid = eid == null ? null : eid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.BEID
     *
     * @return the value of con_contract_v2.BEID
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getBeid() {
        return beid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.BEID
     *
     * @param beid the value for con_contract_v2.BEID
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setBeid(String beid) {
        this.beid = beid == null ? null : beid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.STATUS
     *
     * @return the value of con_contract_v2.STATUS
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.STATUS
     *
     * @param status the value for con_contract_v2.STATUS
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.RENTAL_MODE
     *
     * @return the value of con_contract_v2.RENTAL_MODE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Short getRentalMode() {
        return rentalMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.RENTAL_MODE
     *
     * @param rentalMode the value for con_contract_v2.RENTAL_MODE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setRentalMode(Short rentalMode) {
        this.rentalMode = rentalMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.LEASE_PURPOSE
     *
     * @return the value of con_contract_v2.LEASE_PURPOSE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Short getLeasePurpose() {
        return leasePurpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.LEASE_PURPOSE
     *
     * @param leasePurpose the value for con_contract_v2.LEASE_PURPOSE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setLeasePurpose(Short leasePurpose) {
        this.leasePurpose = leasePurpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.LEASE_DOMAIN
     *
     * @return the value of con_contract_v2.LEASE_DOMAIN
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getLeaseDomain() {
        return leaseDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.LEASE_DOMAIN
     *
     * @param leaseDomain the value for con_contract_v2.LEASE_DOMAIN
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setLeaseDomain(String leaseDomain) {
        this.leaseDomain = leaseDomain == null ? null : leaseDomain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.LEASE_AREA
     *
     * @return the value of con_contract_v2.LEASE_AREA
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public BigDecimal getLeaseArea() {
        return leaseArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.LEASE_AREA
     *
     * @param leaseArea the value for con_contract_v2.LEASE_AREA
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setLeaseArea(BigDecimal leaseArea) {
        this.leaseArea = leaseArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.LEASE_TERM_YEAR
     *
     * @return the value of con_contract_v2.LEASE_TERM_YEAR
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Integer getLeaseTermYear() {
        return leaseTermYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.LEASE_TERM_YEAR
     *
     * @param leaseTermYear the value for con_contract_v2.LEASE_TERM_YEAR
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setLeaseTermYear(Integer leaseTermYear) {
        this.leaseTermYear = leaseTermYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.LEASE_TERM_MONTH
     *
     * @return the value of con_contract_v2.LEASE_TERM_MONTH
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Integer getLeaseTermMonth() {
        return leaseTermMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.LEASE_TERM_MONTH
     *
     * @param leaseTermMonth the value for con_contract_v2.LEASE_TERM_MONTH
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setLeaseTermMonth(Integer leaseTermMonth) {
        this.leaseTermMonth = leaseTermMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.START_TIME
     *
     * @return the value of con_contract_v2.START_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.START_TIME
     *
     * @param startTime the value for con_contract_v2.START_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.END_TIME
     *
     * @return the value of con_contract_v2.END_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.END_TIME
     *
     * @param endTime the value for con_contract_v2.END_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.LESSEE_PID
     *
     * @return the value of con_contract_v2.LESSEE_PID
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getLesseePid() {
        return lesseePid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.LESSEE_PID
     *
     * @param lesseePid the value for con_contract_v2.LESSEE_PID
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setLesseePid(String lesseePid) {
        this.lesseePid = lesseePid == null ? null : lesseePid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.LESSEE_NAME
     *
     * @return the value of con_contract_v2.LESSEE_NAME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getLesseeName() {
        return lesseeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.LESSEE_NAME
     *
     * @param lesseeName the value for con_contract_v2.LESSEE_NAME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setLesseeName(String lesseeName) {
        this.lesseeName = lesseeName == null ? null : lesseeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.LESSEE_ID_TYPE
     *
     * @return the value of con_contract_v2.LESSEE_ID_TYPE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Integer getLesseeIdType() {
        return lesseeIdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.LESSEE_ID_TYPE
     *
     * @param lesseeIdType the value for con_contract_v2.LESSEE_ID_TYPE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setLesseeIdType(Integer lesseeIdType) {
        this.lesseeIdType = lesseeIdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.LESSEE_ID_NO
     *
     * @return the value of con_contract_v2.LESSEE_ID_NO
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getLesseeIdNo() {
        return lesseeIdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.LESSEE_ID_NO
     *
     * @param lesseeIdNo the value for con_contract_v2.LESSEE_ID_NO
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setLesseeIdNo(String lesseeIdNo) {
        this.lesseeIdNo = lesseeIdNo == null ? null : lesseeIdNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.LESSEE_MOBILE
     *
     * @return the value of con_contract_v2.LESSEE_MOBILE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getLesseeMobile() {
        return lesseeMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.LESSEE_MOBILE
     *
     * @param lesseeMobile the value for con_contract_v2.LESSEE_MOBILE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setLesseeMobile(String lesseeMobile) {
        this.lesseeMobile = lesseeMobile == null ? null : lesseeMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.LESSEE_ADDRESS
     *
     * @return the value of con_contract_v2.LESSEE_ADDRESS
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getLesseeAddress() {
        return lesseeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.LESSEE_ADDRESS
     *
     * @param lesseeAddress the value for con_contract_v2.LESSEE_ADDRESS
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setLesseeAddress(String lesseeAddress) {
        this.lesseeAddress = lesseeAddress == null ? null : lesseeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.LESSEE_EMAIL
     *
     * @return the value of con_contract_v2.LESSEE_EMAIL
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getLesseeEmail() {
        return lesseeEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.LESSEE_EMAIL
     *
     * @param lesseeEmail the value for con_contract_v2.LESSEE_EMAIL
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setLesseeEmail(String lesseeEmail) {
        this.lesseeEmail = lesseeEmail == null ? null : lesseeEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.LESSEE_BACKUP_TEL
     *
     * @return the value of con_contract_v2.LESSEE_BACKUP_TEL
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getLesseeBackupTel() {
        return lesseeBackupTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.LESSEE_BACKUP_TEL
     *
     * @param lesseeBackupTel the value for con_contract_v2.LESSEE_BACKUP_TEL
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setLesseeBackupTel(String lesseeBackupTel) {
        this.lesseeBackupTel = lesseeBackupTel == null ? null : lesseeBackupTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.LESSEE_BACKUP_NAME
     *
     * @return the value of con_contract_v2.LESSEE_BACKUP_NAME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getLesseeBackupName() {
        return lesseeBackupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.LESSEE_BACKUP_NAME
     *
     * @param lesseeBackupName the value for con_contract_v2.LESSEE_BACKUP_NAME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setLesseeBackupName(String lesseeBackupName) {
        this.lesseeBackupName = lesseeBackupName == null ? null : lesseeBackupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.LESSEE_IDS
     *
     * @return the value of con_contract_v2.LESSEE_IDS
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getLesseeIds() {
        return lesseeIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.LESSEE_IDS
     *
     * @param lesseeIds the value for con_contract_v2.LESSEE_IDS
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setLesseeIds(String lesseeIds) {
        this.lesseeIds = lesseeIds == null ? null : lesseeIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.LESSEE_IDS_OTHER
     *
     * @return the value of con_contract_v2.LESSEE_IDS_OTHER
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getLesseeIdsOther() {
        return lesseeIdsOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.LESSEE_IDS_OTHER
     *
     * @param lesseeIdsOther the value for con_contract_v2.LESSEE_IDS_OTHER
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setLesseeIdsOther(String lesseeIdsOther) {
        this.lesseeIdsOther = lesseeIdsOther == null ? null : lesseeIdsOther.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.MONTHLY_RENT
     *
     * @return the value of con_contract_v2.MONTHLY_RENT
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Integer getMonthlyRent() {
        return monthlyRent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.MONTHLY_RENT
     *
     * @param monthlyRent the value for con_contract_v2.MONTHLY_RENT
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setMonthlyRent(Integer monthlyRent) {
        this.monthlyRent = monthlyRent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.SETTLEMENT_CYCLE
     *
     * @return the value of con_contract_v2.SETTLEMENT_CYCLE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Integer getSettlementCycle() {
        return settlementCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.SETTLEMENT_CYCLE
     *
     * @param settlementCycle the value for con_contract_v2.SETTLEMENT_CYCLE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setSettlementCycle(Integer settlementCycle) {
        this.settlementCycle = settlementCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.PAY_TIME_MONTH
     *
     * @return the value of con_contract_v2.PAY_TIME_MONTH
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Integer getPayTimeMonth() {
        return payTimeMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.PAY_TIME_MONTH
     *
     * @param payTimeMonth the value for con_contract_v2.PAY_TIME_MONTH
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setPayTimeMonth(Integer payTimeMonth) {
        this.payTimeMonth = payTimeMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.PAY_TIME_DAY
     *
     * @return the value of con_contract_v2.PAY_TIME_DAY
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Integer getPayTimeDay() {
        return payTimeDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.PAY_TIME_DAY
     *
     * @param payTimeDay the value for con_contract_v2.PAY_TIME_DAY
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setPayTimeDay(Integer payTimeDay) {
        this.payTimeDay = payTimeDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.OWNER_BEAR
     *
     * @return the value of con_contract_v2.OWNER_BEAR
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getOwnerBear() {
        return ownerBear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.OWNER_BEAR
     *
     * @param ownerBear the value for con_contract_v2.OWNER_BEAR
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setOwnerBear(String ownerBear) {
        this.ownerBear = ownerBear == null ? null : ownerBear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.OWNER_BEAR_OTHER
     *
     * @return the value of con_contract_v2.OWNER_BEAR_OTHER
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getOwnerBearOther() {
        return ownerBearOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.OWNER_BEAR_OTHER
     *
     * @param ownerBearOther the value for con_contract_v2.OWNER_BEAR_OTHER
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setOwnerBearOther(String ownerBearOther) {
        this.ownerBearOther = ownerBearOther == null ? null : ownerBearOther.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.DEPOSIT_AMT
     *
     * @return the value of con_contract_v2.DEPOSIT_AMT
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public BigDecimal getDepositAmt() {
        return depositAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.DEPOSIT_AMT
     *
     * @param depositAmt the value for con_contract_v2.DEPOSIT_AMT
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setDepositAmt(BigDecimal depositAmt) {
        this.depositAmt = depositAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.STAGES
     *
     * @return the value of con_contract_v2.STAGES
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Integer getStages() {
        return stages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.STAGES
     *
     * @param stages the value for con_contract_v2.STAGES
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setStages(Integer stages) {
        this.stages = stages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.PAYMENT_METHOD
     *
     * @return the value of con_contract_v2.PAYMENT_METHOD
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Short getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.PAYMENT_METHOD
     *
     * @param paymentMethod the value for con_contract_v2.PAYMENT_METHOD
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setPaymentMethod(Short paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.LESSOR_PID
     *
     * @return the value of con_contract_v2.LESSOR_PID
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getLessorPid() {
        return lessorPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.LESSOR_PID
     *
     * @param lessorPid the value for con_contract_v2.LESSOR_PID
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setLessorPid(String lessorPid) {
        this.lessorPid = lessorPid == null ? null : lessorPid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.LESSOR_NAME
     *
     * @return the value of con_contract_v2.LESSOR_NAME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getLessorName() {
        return lessorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.LESSOR_NAME
     *
     * @param lessorName the value for con_contract_v2.LESSOR_NAME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setLessorName(String lessorName) {
        this.lessorName = lessorName == null ? null : lessorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.LESSOR_ID_TYPE
     *
     * @return the value of con_contract_v2.LESSOR_ID_TYPE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Integer getLessorIdType() {
        return lessorIdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.LESSOR_ID_TYPE
     *
     * @param lessorIdType the value for con_contract_v2.LESSOR_ID_TYPE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setLessorIdType(Integer lessorIdType) {
        this.lessorIdType = lessorIdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.LESSOR_ID_NO
     *
     * @return the value of con_contract_v2.LESSOR_ID_NO
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getLessorIdNo() {
        return lessorIdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.LESSOR_ID_NO
     *
     * @param lessorIdNo the value for con_contract_v2.LESSOR_ID_NO
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setLessorIdNo(String lessorIdNo) {
        this.lessorIdNo = lessorIdNo == null ? null : lessorIdNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.LESSOR_ADDRESS
     *
     * @return the value of con_contract_v2.LESSOR_ADDRESS
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getLessorAddress() {
        return lessorAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.LESSOR_ADDRESS
     *
     * @param lessorAddress the value for con_contract_v2.LESSOR_ADDRESS
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setLessorAddress(String lessorAddress) {
        this.lessorAddress = lessorAddress == null ? null : lessorAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.LESSOR_EMAIL
     *
     * @return the value of con_contract_v2.LESSOR_EMAIL
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getLessorEmail() {
        return lessorEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.LESSOR_EMAIL
     *
     * @param lessorEmail the value for con_contract_v2.LESSOR_EMAIL
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setLessorEmail(String lessorEmail) {
        this.lessorEmail = lessorEmail == null ? null : lessorEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.LESSOR_BACKUP_NAME
     *
     * @return the value of con_contract_v2.LESSOR_BACKUP_NAME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getLessorBackupName() {
        return lessorBackupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.LESSOR_BACKUP_NAME
     *
     * @param lessorBackupName the value for con_contract_v2.LESSOR_BACKUP_NAME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setLessorBackupName(String lessorBackupName) {
        this.lessorBackupName = lessorBackupName == null ? null : lessorBackupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.LESSOR_BACKUP_TEL
     *
     * @return the value of con_contract_v2.LESSOR_BACKUP_TEL
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getLessorBackupTel() {
        return lessorBackupTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.LESSOR_BACKUP_TEL
     *
     * @param lessorBackupTel the value for con_contract_v2.LESSOR_BACKUP_TEL
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setLessorBackupTel(String lessorBackupTel) {
        this.lessorBackupTel = lessorBackupTel == null ? null : lessorBackupTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.LESSOR_MOBILE
     *
     * @return the value of con_contract_v2.LESSOR_MOBILE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getLessorMobile() {
        return lessorMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.LESSOR_MOBILE
     *
     * @param lessorMobile the value for con_contract_v2.LESSOR_MOBILE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setLessorMobile(String lessorMobile) {
        this.lessorMobile = lessorMobile == null ? null : lessorMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.LESSOR_IDS
     *
     * @return the value of con_contract_v2.LESSOR_IDS
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getLessorIds() {
        return lessorIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.LESSOR_IDS
     *
     * @param lessorIds the value for con_contract_v2.LESSOR_IDS
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setLessorIds(String lessorIds) {
        this.lessorIds = lessorIds == null ? null : lessorIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.LESSOR_IDS_OTHER
     *
     * @return the value of con_contract_v2.LESSOR_IDS_OTHER
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getLessorIdsOther() {
        return lessorIdsOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.LESSOR_IDS_OTHER
     *
     * @param lessorIdsOther the value for con_contract_v2.LESSOR_IDS_OTHER
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setLessorIdsOther(String lessorIdsOther) {
        this.lessorIdsOther = lessorIdsOther == null ? null : lessorIdsOther.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.HOUSE_ADDR
     *
     * @return the value of con_contract_v2.HOUSE_ADDR
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getHouseAddr() {
        return houseAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.HOUSE_ADDR
     *
     * @param houseAddr the value for con_contract_v2.HOUSE_ADDR
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setHouseAddr(String houseAddr) {
        this.houseAddr = houseAddr == null ? null : houseAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.PROPERTY_TYPE
     *
     * @return the value of con_contract_v2.PROPERTY_TYPE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Integer getPropertyType() {
        return propertyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.PROPERTY_TYPE
     *
     * @param propertyType the value for con_contract_v2.PROPERTY_TYPE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setPropertyType(Integer propertyType) {
        this.propertyType = propertyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.HOUSE_TYPE
     *
     * @return the value of con_contract_v2.HOUSE_TYPE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getHouseType() {
        return houseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.HOUSE_TYPE
     *
     * @param houseType the value for con_contract_v2.HOUSE_TYPE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setHouseType(String houseType) {
        this.houseType = houseType == null ? null : houseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.BUILDING_AREA
     *
     * @return the value of con_contract_v2.BUILDING_AREA
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public BigDecimal getBuildingArea() {
        return buildingArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.BUILDING_AREA
     *
     * @param buildingArea the value for con_contract_v2.BUILDING_AREA
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setBuildingArea(BigDecimal buildingArea) {
        this.buildingArea = buildingArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.HOUSE_OWNER_PID
     *
     * @return the value of con_contract_v2.HOUSE_OWNER_PID
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getHouseOwnerPid() {
        return houseOwnerPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.HOUSE_OWNER_PID
     *
     * @param houseOwnerPid the value for con_contract_v2.HOUSE_OWNER_PID
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setHouseOwnerPid(String houseOwnerPid) {
        this.houseOwnerPid = houseOwnerPid == null ? null : houseOwnerPid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.HOUSE_OWNER_NAME
     *
     * @return the value of con_contract_v2.HOUSE_OWNER_NAME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getHouseOwnerName() {
        return houseOwnerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.HOUSE_OWNER_NAME
     *
     * @param houseOwnerName the value for con_contract_v2.HOUSE_OWNER_NAME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setHouseOwnerName(String houseOwnerName) {
        this.houseOwnerName = houseOwnerName == null ? null : houseOwnerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.HOUSE_OWNER_ID_TYPE
     *
     * @return the value of con_contract_v2.HOUSE_OWNER_ID_TYPE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Integer getHouseOwnerIdType() {
        return houseOwnerIdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.HOUSE_OWNER_ID_TYPE
     *
     * @param houseOwnerIdType the value for con_contract_v2.HOUSE_OWNER_ID_TYPE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setHouseOwnerIdType(Integer houseOwnerIdType) {
        this.houseOwnerIdType = houseOwnerIdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.HOUSE_OWNER_ID_NO
     *
     * @return the value of con_contract_v2.HOUSE_OWNER_ID_NO
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getHouseOwnerIdNo() {
        return houseOwnerIdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.HOUSE_OWNER_ID_NO
     *
     * @param houseOwnerIdNo the value for con_contract_v2.HOUSE_OWNER_ID_NO
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setHouseOwnerIdNo(String houseOwnerIdNo) {
        this.houseOwnerIdNo = houseOwnerIdNo == null ? null : houseOwnerIdNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.HOUSE_OWNER_MOBILE
     *
     * @return the value of con_contract_v2.HOUSE_OWNER_MOBILE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getHouseOwnerMobile() {
        return houseOwnerMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.HOUSE_OWNER_MOBILE
     *
     * @param houseOwnerMobile the value for con_contract_v2.HOUSE_OWNER_MOBILE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setHouseOwnerMobile(String houseOwnerMobile) {
        this.houseOwnerMobile = houseOwnerMobile == null ? null : houseOwnerMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.REJECT_REASON
     *
     * @return the value of con_contract_v2.REJECT_REASON
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getRejectReason() {
        return rejectReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.REJECT_REASON
     *
     * @param rejectReason the value for con_contract_v2.REJECT_REASON
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setRejectReason(String rejectReason) {
        this.rejectReason = rejectReason == null ? null : rejectReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.REJECT_REASON_TYPE
     *
     * @return the value of con_contract_v2.REJECT_REASON_TYPE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Integer getRejectReasonType() {
        return rejectReasonType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.REJECT_REASON_TYPE
     *
     * @param rejectReasonType the value for con_contract_v2.REJECT_REASON_TYPE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setRejectReasonType(Integer rejectReasonType) {
        this.rejectReasonType = rejectReasonType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.CONFIRM_TIME
     *
     * @return the value of con_contract_v2.CONFIRM_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Date getConfirmTime() {
        return confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.CONFIRM_TIME
     *
     * @param confirmTime the value for con_contract_v2.CONFIRM_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setConfirmTime(Date confirmTime) {
        this.confirmTime = confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.SEND_TIME
     *
     * @return the value of con_contract_v2.SEND_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.SEND_TIME
     *
     * @param sendTime the value for con_contract_v2.SEND_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.APPROVAL_TIME
     *
     * @return the value of con_contract_v2.APPROVAL_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Date getApprovalTime() {
        return approvalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.APPROVAL_TIME
     *
     * @param approvalTime the value for con_contract_v2.APPROVAL_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setApprovalTime(Date approvalTime) {
        this.approvalTime = approvalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.CANCEL_TIME
     *
     * @return the value of con_contract_v2.CANCEL_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Date getCancelTime() {
        return cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.CANCEL_TIME
     *
     * @param cancelTime the value for con_contract_v2.CANCEL_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setCancelTime(Date cancelTime) {
        this.cancelTime = cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.FINISH_TIME
     *
     * @return the value of con_contract_v2.FINISH_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.FINISH_TIME
     *
     * @param finishTime the value for con_contract_v2.FINISH_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.REJECT_TIME
     *
     * @return the value of con_contract_v2.REJECT_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Date getRejectTime() {
        return rejectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.REJECT_TIME
     *
     * @param rejectTime the value for con_contract_v2.REJECT_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setRejectTime(Date rejectTime) {
        this.rejectTime = rejectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.AGENCY_FEE
     *
     * @return the value of con_contract_v2.AGENCY_FEE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public BigDecimal getAgencyFee() {
        return agencyFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.AGENCY_FEE
     *
     * @param agencyFee the value for con_contract_v2.AGENCY_FEE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setAgencyFee(BigDecimal agencyFee) {
        this.agencyFee = agencyFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.NATION
     *
     * @return the value of con_contract_v2.NATION
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.NATION
     *
     * @param nation the value for con_contract_v2.NATION
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.HKADR
     *
     * @return the value of con_contract_v2.HKADR
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getHkadr() {
        return hkadr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.HKADR
     *
     * @param hkadr the value for con_contract_v2.HKADR
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setHkadr(String hkadr) {
        this.hkadr = hkadr == null ? null : hkadr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.ADDITIONAL_TERMS
     *
     * @return the value of con_contract_v2.ADDITIONAL_TERMS
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getAdditionalTerms() {
        return additionalTerms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.ADDITIONAL_TERMS
     *
     * @param additionalTerms the value for con_contract_v2.ADDITIONAL_TERMS
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setAdditionalTerms(String additionalTerms) {
        this.additionalTerms = additionalTerms == null ? null : additionalTerms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.AGT_COM_NAME
     *
     * @return the value of con_contract_v2.AGT_COM_NAME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getAgtComName() {
        return agtComName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.AGT_COM_NAME
     *
     * @param agtComName the value for con_contract_v2.AGT_COM_NAME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setAgtComName(String agtComName) {
        this.agtComName = agtComName == null ? null : agtComName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.AGT_ADDRESS
     *
     * @return the value of con_contract_v2.AGT_ADDRESS
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getAgtAddress() {
        return agtAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.AGT_ADDRESS
     *
     * @param agtAddress the value for con_contract_v2.AGT_ADDRESS
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setAgtAddress(String agtAddress) {
        this.agtAddress = agtAddress == null ? null : agtAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.AGT_COM_TEL
     *
     * @return the value of con_contract_v2.AGT_COM_TEL
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getAgtComTel() {
        return agtComTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.AGT_COM_TEL
     *
     * @param agtComTel the value for con_contract_v2.AGT_COM_TEL
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setAgtComTel(String agtComTel) {
        this.agtComTel = agtComTel == null ? null : agtComTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.PROXY_ATT_ID
     *
     * @return the value of con_contract_v2.PROXY_ATT_ID
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getProxyAttId() {
        return proxyAttId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.PROXY_ATT_ID
     *
     * @param proxyAttId the value for con_contract_v2.PROXY_ATT_ID
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setProxyAttId(String proxyAttId) {
        this.proxyAttId = proxyAttId == null ? null : proxyAttId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.CREATE_USER
     *
     * @return the value of con_contract_v2.CREATE_USER
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.CREATE_USER
     *
     * @param createUser the value for con_contract_v2.CREATE_USER
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.CREATE_USER_IDENTITY
     *
     * @return the value of con_contract_v2.CREATE_USER_IDENTITY
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Short getCreateUserIdentity() {
        return createUserIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.CREATE_USER_IDENTITY
     *
     * @param createUserIdentity the value for con_contract_v2.CREATE_USER_IDENTITY
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setCreateUserIdentity(Short createUserIdentity) {
        this.createUserIdentity = createUserIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.CREATE_TIME
     *
     * @return the value of con_contract_v2.CREATE_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.CREATE_TIME
     *
     * @param createTime the value for con_contract_v2.CREATE_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.MODIFY_USER
     *
     * @return the value of con_contract_v2.MODIFY_USER
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.MODIFY_USER
     *
     * @param modifyUser the value for con_contract_v2.MODIFY_USER
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.MODIFY_USER_IDENTITY
     *
     * @return the value of con_contract_v2.MODIFY_USER_IDENTITY
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Short getModifyUserIdentity() {
        return modifyUserIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.MODIFY_USER_IDENTITY
     *
     * @param modifyUserIdentity the value for con_contract_v2.MODIFY_USER_IDENTITY
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setModifyUserIdentity(Short modifyUserIdentity) {
        this.modifyUserIdentity = modifyUserIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.MODIFY_TIME
     *
     * @return the value of con_contract_v2.MODIFY_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.MODIFY_TIME
     *
     * @param modifyTime the value for con_contract_v2.MODIFY_TIME
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.DELETE_FLG
     *
     * @return the value of con_contract_v2.DELETE_FLG
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Short getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.DELETE_FLG
     *
     * @param deleteFlg the value for con_contract_v2.DELETE_FLG
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setDeleteFlg(Short deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.VERSION
     *
     * @return the value of con_contract_v2.VERSION
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.VERSION
     *
     * @param version the value for con_contract_v2.VERSION
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.HOUSE_STRUCTURE
     *
     * @return the value of con_contract_v2.HOUSE_STRUCTURE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public Integer getHouseStructure() {
        return houseStructure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.HOUSE_STRUCTURE
     *
     * @param houseStructure the value for con_contract_v2.HOUSE_STRUCTURE
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setHouseStructure(Integer houseStructure) {
        this.houseStructure = houseStructure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_contract_v2.PROPERTY_ID_NO
     *
     * @return the value of con_contract_v2.PROPERTY_ID_NO
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public String getPropertyIdNo() {
        return propertyIdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_contract_v2.PROPERTY_ID_NO
     *
     * @param propertyIdNo the value for con_contract_v2.PROPERTY_ID_NO
     *
     * @mbggenerated Tue Mar 21 10:34:26 CST 2017
     */
    public void setPropertyIdNo(String propertyIdNo) {
        this.propertyIdNo = propertyIdNo == null ? null : propertyIdNo.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pindex=").append(pindex);
        sb.append(", source=").append(source);
        sb.append(", eid=").append(eid);
        sb.append(", beid=").append(beid);
        sb.append(", status=").append(status);
        sb.append(", rentalMode=").append(rentalMode);
        sb.append(", leasePurpose=").append(leasePurpose);
        sb.append(", leaseDomain=").append(leaseDomain);
        sb.append(", leaseArea=").append(leaseArea);
        sb.append(", leaseTermYear=").append(leaseTermYear);
        sb.append(", leaseTermMonth=").append(leaseTermMonth);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", lesseePid=").append(lesseePid);
        sb.append(", lesseeName=").append(lesseeName);
        sb.append(", lesseeIdType=").append(lesseeIdType);
        sb.append(", lesseeIdNo=").append(lesseeIdNo);
        sb.append(", lesseeMobile=").append(lesseeMobile);
        sb.append(", lesseeAddress=").append(lesseeAddress);
        sb.append(", lesseeEmail=").append(lesseeEmail);
        sb.append(", lesseeBackupTel=").append(lesseeBackupTel);
        sb.append(", lesseeBackupName=").append(lesseeBackupName);
        sb.append(", lesseeIds=").append(lesseeIds);
        sb.append(", lesseeIdsOther=").append(lesseeIdsOther);
        sb.append(", monthlyRent=").append(monthlyRent);
        sb.append(", settlementCycle=").append(settlementCycle);
        sb.append(", payTimeMonth=").append(payTimeMonth);
        sb.append(", payTimeDay=").append(payTimeDay);
        sb.append(", ownerBear=").append(ownerBear);
        sb.append(", ownerBearOther=").append(ownerBearOther);
        sb.append(", depositAmt=").append(depositAmt);
        sb.append(", paymentMethod=").append(paymentMethod);
        sb.append(", stages=").append(stages);
        sb.append(", lessorPid=").append(lessorPid);
        sb.append(", lessorName=").append(lessorName);
        sb.append(", lessorIdType=").append(lessorIdType);
        sb.append(", lessorIdNo=").append(lessorIdNo);
        sb.append(", lessorAddress=").append(lessorAddress);
        sb.append(", lessorEmail=").append(lessorEmail);
        sb.append(", lessorBackupName=").append(lessorBackupName);
        sb.append(", lessorBackupTel=").append(lessorBackupTel);
        sb.append(", lessorMobile=").append(lessorMobile);
        sb.append(", lessorIds=").append(lessorIds);
        sb.append(", lessorIdsOther=").append(lessorIdsOther);
        sb.append(", houseAddr=").append(houseAddr);
        sb.append(", propertyType=").append(propertyType);
        sb.append(", houseType=").append(houseType);
        sb.append(", buildingArea=").append(buildingArea);
        sb.append(", houseOwnerPid=").append(houseOwnerPid);
        sb.append(", houseOwnerName=").append(houseOwnerName);
        sb.append(", houseOwnerIdType=").append(houseOwnerIdType);
        sb.append(", houseOwnerIdNo=").append(houseOwnerIdNo);
        sb.append(", houseOwnerMobile=").append(houseOwnerMobile);
        sb.append(", rejectReason=").append(rejectReason);
        sb.append(", rejectReasonType=").append(rejectReasonType);
        sb.append(", confirmTime=").append(confirmTime);
        sb.append(", sendTime=").append(sendTime);
        sb.append(", approvalTime=").append(approvalTime);
        sb.append(", cancelTime=").append(cancelTime);
        sb.append(", finishTime=").append(finishTime);
        sb.append(", rejectTime=").append(rejectTime);
        sb.append(", agencyFee=").append(agencyFee);
        sb.append(", additionalTerms=").append(additionalTerms);
        sb.append(", proxyAttId=").append(proxyAttId);
        sb.append("]");
        return sb.toString();
    }

    private List<SysInfoAtt> infoAttList;

    private ConDepositDistAgr conDepositDistAgr;

    private ConDissAgr conDissAgr;

    private String lessorIdTypeName;
    private String lesseeIdTypeName;

    private AgtEmpInfo agtEmpInfo;
    private int depositType;
    private Integer depositStatus;

    private String conditionText;

    private Integer conditionType;

    private String depositTypeName;

    private String statusTypeName;

    private HouHouseInfo houseInfo;

    private String rentalModeName;

    private String propertyIdTypeName;

    private String rentalPurposeName;

    private String statusName;

    private String dateStartTime;

    private String dateEndTime;

    private String houPropertyName;

    private String apartmentLayout;

    private String settlementCycleName;

    private String dateConfirmTime;

    public String getDateConfirmTime() {
        if (confirmTime != null) {
            dateConfirmTime = DateUtils.dateToStr(confirmTime, DateUtils.DATE_YMD_PATERN);
        }
        return dateConfirmTime;
    }

    public void setDateConfirmTime(String dateConfirmTime) {
        this.dateConfirmTime = dateConfirmTime;
    }

    /**
     * 房源编号
     */
    private String houNo;
    /**
     * 房源认证状态
     */
    private String certStatus;

    public String getCertStatus() {
        return certStatus;
    }

    public void setCertStatus(String certStatus) {
        this.certStatus = certStatus;
    }

    private ConDeposit conDeposit;

    private List<ConHouseUser> houseUsers;

    public ConDepositDistAgr getConDepositDistAgr() {
        return conDepositDistAgr;
    }

    public void setConDepositDistAgr(ConDepositDistAgr conDepositDistAgr) {
        this.conDepositDistAgr = conDepositDistAgr;
    }

    public ConDissAgr getConDissAgr() {
        return conDissAgr;
    }

    public void setConDissAgr(ConDissAgr conDissAgr) {
        this.conDissAgr = conDissAgr;
    }

    public AgtEmpInfo getAgtEmpInfo() {
        return agtEmpInfo;
    }

    public void setAgtEmpInfo(AgtEmpInfo agtEmpInfo) {
        this.agtEmpInfo = agtEmpInfo;
    }

    public Integer getDepositStatus() {
        return depositStatus;
    }

    public void setDepositStatus(Integer depositStatus) {
        this.depositStatus = depositStatus;
    }

    public String getConditionText() {
        return conditionText;
    }

    public void setConditionText(String conditionText) {
        this.conditionText = conditionText;
    }

    public Integer getConditionType() {
        return conditionType;
    }

    public void setConditionType(Integer conditionType) {
        this.conditionType = conditionType;
    }

    public List<SysInfoAtt> getInfoAttList() {
        return infoAttList;
    }

    public void setInfoAttList(List<SysInfoAtt> infoAttList) {
        this.infoAttList = infoAttList;
    }

    public String getDepositTypeName() {
        return depositTypeName;
    }

    public void setDepositTypeName(String depositTypeName) {
        this.depositTypeName = depositTypeName;
    }

    public String getStatusTypeName() {
        return statusTypeName;
    }

    public void setStatusTypeName(String statusTypeName) {
        this.statusTypeName = statusTypeName;
    }

    public HouHouseInfo getHouseInfo() {
        return houseInfo;
    }

    public void setHouseInfo(HouHouseInfo houseInfo) {
        this.houseInfo = houseInfo;
    }

    public String getRentalModeName() {
        return rentalModeName;
    }

    public void setRentalModeName(String rentalModeName) {
        this.rentalModeName = rentalModeName;
    }

    public String getPropertyIdTypeName() {
        return propertyIdTypeName;
    }

    public void setPropertyIdTypeName(String propertyIdTypeName) {
        this.propertyIdTypeName = propertyIdTypeName;
    }

    public String getRentalPurposeName() {
        return rentalPurposeName;
    }

    public void setRentalPurposeName(String rentalPurposeName) {
        this.rentalPurposeName = rentalPurposeName;
    }

    public String getLessorIdTypeName() {
        return lessorIdTypeName;
    }

    public void setLessorIdTypeName(String lessorIdTypeName) {
        this.lessorIdTypeName = lessorIdTypeName;
    }

    public String getLesseeIdTypeName() {
        return lesseeIdTypeName;
    }

    public void setLesseeIdTypeName(String lesseeIdTypeName) {
        this.lesseeIdTypeName = lesseeIdTypeName;
    }

    public String getStatusName() {
        return statusName;
    }

    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }

    public String getHouNo() {
        return houNo;
    }

    public void setHouNo(String houNo) {
        this.houNo = houNo;
    }

    public ConDeposit getConDeposit() {
        return conDeposit;
    }

    public void setConDeposit(ConDeposit conDeposit) {
        this.conDeposit = conDeposit;
    }

    public int getDepositType() {
        return depositType;
    }

    public void setDepositType(int depositType) {
        this.depositType = depositType;
    }

    public String getDateStartTime() {
        if (startTime != null) {
            dateStartTime = DateUtils.dateToStr(startTime, DateUtils.DATE_YMD_PATERN);
        }

        return dateStartTime;
    }

    public void setDateStartTime(String dateStartTime) {
        this.dateStartTime = dateStartTime;
    }

    public String getDateEndTime() {
        if (endTime != null) {
            dateEndTime = DateUtils.dateToStr(endTime, DateUtils.DATE_YMD_PATERN);
        }
        return dateEndTime;
    }

    public void setDateEndTime(String dateEndTime) {
        this.dateEndTime = dateEndTime;
    }

    public List<ConHouseUser> getHouseUsers() {
        return houseUsers;
    }

    public void setHouseUsers(List<ConHouseUser> houseUsers) {
        this.houseUsers = houseUsers;
    }

    public String getLeasePurposeName() {
        return leasePurposeName;
    }

    public void setLeasePurposeName(String leasePurposeName) {
        this.leasePurposeName = leasePurposeName;
    }

    public String getRentTypeName() {
        return rentTypeName;
    }

    public void setRentTypeName(String rentTypeName) {
        this.rentTypeName = rentTypeName;
    }

    public String[] getLesseeBears() {
        if (ownerBear != null) {
            lesseeBears = ownerBear.split(",");
        }
        return lesseeBears;
    }

    public void setLesseeBears(String[] lesseeBears) {
        this.lesseeBears = lesseeBears;
    }

    private String leasePurposeName;

    private String rentTypeName;

    private String rentType;

    private String[] lesseeBears;

    private List<ConHouseItems> houItemsList;
    private List<ConOtherCosts> conOtherCostsList;

    public List<ConHouseItems> getHouItemsList() {
        return houItemsList;
    }

    public void setHouItemsList(List<ConHouseItems> houItemsList) {
        this.houItemsList = houItemsList;
    }

    public String getRentType() {
        return rentType;
    }

    public void setRentType(String rentType) {
        this.rentType = rentType;
    }

    public String getHouPropertyName() {
        return houPropertyName;
    }

    public void setHouPropertyName(String houPropertyName) {
        this.houPropertyName = houPropertyName;
    }

    public String getApartmentLayout() {
        return apartmentLayout;
    }

    public void setApartmentLayout(String apartmentLayout) {
        this.apartmentLayout = apartmentLayout;
    }

    public String getSettlementCycleName() {
        return settlementCycleName;
    }

    public void setSettlementCycleName(String settlementCycleName) {
        this.settlementCycleName = settlementCycleName;
    }

    private HouLeaseInfo houLeaseInfo;

    public HouLeaseInfo getHouLeaseInfo() {
        return houLeaseInfo;
    }

    public void setHouLeaseInfo(HouLeaseInfo houLeaseInfo) {
        this.houLeaseInfo = houLeaseInfo;
    }

    public List<HouCoOwner> getHouseOwner() {
        return houseOwner;
    }

    public void setHouseOwner(List<HouCoOwner> houseOwner) {
        this.houseOwner = houseOwner;
    }

    public List<ConOtherCosts> getConOtherCosts() {
        return conOtherCosts;
    }

    public void setConOtherCosts(List<ConOtherCosts> conOtherCosts) {
        this.conOtherCosts = conOtherCosts;
    }

    public List<ConOtherCosts> getConOtherCostsList() {
        return conOtherCostsList;
    }

    public void setConOtherCostsList(List<ConOtherCosts> conOtherCostsList) {
        this.conOtherCostsList = conOtherCostsList;
    }

    public String getDepositAmtCn() {
        return depositAmtCn;
    }

    public void setDepositAmtCn(String depositAmtCn) {
        this.depositAmtCn = depositAmtCn;
    }

    public String getDno() {
        return dno;
    }

    public void setDno(String dno) {
        this.dno = dno;
    }

    public ConRentstaging getConRentstaging() {
        return conRentstaging;
    }

    public void setConRentstaging(ConRentstaging conRentstaging) {
        this.conRentstaging = conRentstaging;
    }

    private List<HouCoOwner> houseOwner;

    private List<ConOtherCosts> conOtherCosts;

    private String depositAmtCn;

    private String dno;

    private String dstatus;
    /**
     * 租金分期实体
     */
    private ConRentstaging conRentstaging;

//    public Date getStartTime() {
//        if (!StringUtils.isEmpty(dateStartTime)) {
//            startTime = DateUtils.strToDate(dateStartTime, DateUtils.DATE_Y_M_D_PATERN);
//        }
//        return startTime;
//    }
//
//    public Date getEndTime() {
//        if (!StringUtils.isEmpty(dateEndTime)) {
//            endTime = DateUtils.strToDate(dateEndTime, DateUtils.DATE_Y_M_D_PATERN);
//        }
//        return endTime;
//    }

    public String getDstatus() {
        return dstatus;
    }

    public void setDstatus(String dstatus) {
        this.dstatus = dstatus;
    }

    private String rent;//租金分期付款总数

    public String getRent() {
        return rent;
    }

    public void setRent(String rent) {
        this.rent = rent;
    }

    //已交租金总数
    private BigDecimal total;

    public BigDecimal getTotal() {
        return total;
    }

    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    // 是否为在线支付
    public String onlinePayment;

    public String getOnlinePayment() {
        return onlinePayment;
    }

    public void setOnlinePayment(String onlinePayment) {
        this.onlinePayment = onlinePayment;
    }

    // 用户id
    public String currUserId;

    public String getCurrUserId() {
        return currUserId;
    }

    public void setCurrUserId(String currUserId) {
        this.currUserId = currUserId;
    }

    //结算周期
    private String cycle;

    public String getCycle() {
        return cycle;
    }

    public void setCycle(String cycle) {
        this.cycle = cycle;
    }

    // 是否显示付房租按钮
    private boolean rentPayDisplay;

    public boolean isRentPayDisplay() {
        return rentPayDisplay;
    }

    public void setRentPayDisplay(boolean rentPayDisplay) {
        this.rentPayDisplay = rentPayDisplay;
    }
}