package com.dlfc.zfgj.entity;

import com.dlfc.admin.common.persistence.MyDataEntity;

import java.io.Serializable;

public class CmsArticleData extends MyDataEntity<CmsArticleData> implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_data.copyfrom
     *
     * @mbggenerated Fri Feb 19 14:01:54 CST 2016
     */
    private String copyfrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_data.relation
     *
     * @mbggenerated Fri Feb 19 14:01:54 CST 2016
     */
    private String relation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_data.allow_comment
     *
     * @mbggenerated Fri Feb 19 14:01:54 CST 2016
     */
    private String allowComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_data.content
     *
     * @mbggenerated Fri Feb 19 14:01:54 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_article_data
     *
     * @mbggenerated Fri Feb 19 14:01:54 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_data.copyfrom
     *
     * @return the value of cms_article_data.copyfrom
     *
     * @mbggenerated Fri Feb 19 14:01:54 CST 2016
     */
    public String getCopyfrom() {
        return copyfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_data.copyfrom
     *
     * @param copyfrom the value for cms_article_data.copyfrom
     *
     * @mbggenerated Fri Feb 19 14:01:54 CST 2016
     */
    public void setCopyfrom(String copyfrom) {
        this.copyfrom = copyfrom == null ? null : copyfrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_data.relation
     *
     * @return the value of cms_article_data.relation
     *
     * @mbggenerated Fri Feb 19 14:01:54 CST 2016
     */
    public String getRelation() {
        return relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_data.relation
     *
     * @param relation the value for cms_article_data.relation
     *
     * @mbggenerated Fri Feb 19 14:01:54 CST 2016
     */
    public void setRelation(String relation) {
        this.relation = relation == null ? null : relation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_data.allow_comment
     *
     * @return the value of cms_article_data.allow_comment
     *
     * @mbggenerated Fri Feb 19 14:01:54 CST 2016
     */
    public String getAllowComment() {
        return allowComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_data.allow_comment
     *
     * @param allowComment the value for cms_article_data.allow_comment
     *
     * @mbggenerated Fri Feb 19 14:01:54 CST 2016
     */
    public void setAllowComment(String allowComment) {
        this.allowComment = allowComment == null ? null : allowComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_data.content
     *
     * @return the value of cms_article_data.content
     *
     * @mbggenerated Fri Feb 19 14:01:54 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_data.content
     *
     * @param content the value for cms_article_data.content
     *
     * @mbggenerated Fri Feb 19 14:01:54 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_data
     *
     * @mbggenerated Fri Feb 19 14:01:54 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", copyfrom=").append(copyfrom);
        sb.append(", relation=").append(relation);
        sb.append(", allowComment=").append(allowComment);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}