package com.dlfc.zfgj.entity;

import com.dlfc.admin.common.persistence.MyDataEntity;
import com.dlfc.admin.common.utils.DateUtils;
import org.apache.commons.lang3.StringUtils;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ConDissAgr extends MyDataEntity<ConDissAgr> implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_diss_agr.PINDEX
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	private Integer pindex;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_diss_agr.NO
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	private String no;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_diss_agr.CID
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	private String cid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_diss_agr.REASON
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	private Integer reason;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_diss_agr.TO_SPECIAL
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	private Integer toSpecial;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_diss_agr.DESCRIPTION
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	private String description;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_diss_agr.EFFECTIVE_TIME
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	private Date effectiveTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_diss_agr.RETRUN_RENT_AMT
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	private BigDecimal retrunRentAmt;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_diss_agr.PAYMENT_PERSON_TYPE
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	private Integer paymentPersonType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_diss_agr.PAYMENT_AMT
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	private BigDecimal paymentAmt;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_diss_agr.PAYMENT_FROM
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	private String paymentFrom;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_diss_agr.CREATE_USER_TYPE
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	private Integer createUserType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_diss_agr.PAYMENT_TO
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	private String paymentTo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_diss_agr.PAYMENT_DEPOSIT_AMT
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	private BigDecimal paymentDepositAmt;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_diss_agr.PAYMENT_DEPOSIT_FLG
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	private Short paymentDepositFlg;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_diss_agr.STATUS
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	private Short status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_diss_agr.REJECT_TYPE
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	private Integer rejectType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_diss_agr.REJECT_REASON
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	private String rejectReason;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_diss_agr.LOCK_USERID
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	private String lockUserid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_diss_agr.LOCK_TIME
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	private Date lockTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table con_diss_agr
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_diss_agr.PINDEX
	 * @return  the value of con_diss_agr.PINDEX
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public Integer getPindex() {
		return pindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_diss_agr.PINDEX
	 * @param pindex  the value for con_diss_agr.PINDEX
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public void setPindex(Integer pindex) {
		this.pindex = pindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_diss_agr.NO
	 * @return  the value of con_diss_agr.NO
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public String getNo() {
		return no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_diss_agr.NO
	 * @param no  the value for con_diss_agr.NO
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public void setNo(String no) {
		this.no = no == null ? null : no.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_diss_agr.CID
	 * @return  the value of con_diss_agr.CID
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public String getCid() {
		return cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_diss_agr.CID
	 * @param cid  the value for con_diss_agr.CID
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public void setCid(String cid) {
		this.cid = cid == null ? null : cid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_diss_agr.REASON
	 * @return  the value of con_diss_agr.REASON
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public Integer getReason() {
		return reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_diss_agr.REASON
	 * @param reason  the value for con_diss_agr.REASON
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public void setReason(Integer reason) {
		this.reason = reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_diss_agr.TO_SPECIAL
	 * @return  the value of con_diss_agr.TO_SPECIAL
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public Integer getToSpecial() {
		return toSpecial;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_diss_agr.TO_SPECIAL
	 * @param toSpecial  the value for con_diss_agr.TO_SPECIAL
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public void setToSpecial(Integer toSpecial) {
		this.toSpecial = toSpecial;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_diss_agr.DESCRIPTION
	 * @return  the value of con_diss_agr.DESCRIPTION
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_diss_agr.DESCRIPTION
	 * @param description  the value for con_diss_agr.DESCRIPTION
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_diss_agr.EFFECTIVE_TIME
	 * @return  the value of con_diss_agr.EFFECTIVE_TIME
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public Date getEffectiveTime() {
		if (!StringUtils.isBlank(this.formatSaveTime)) {
			this.effectiveTime = DateUtils.strToDate(formatSaveTime, DateUtils.DATE_Y_M_D_PATERN);
		}
		return effectiveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_diss_agr.EFFECTIVE_TIME
	 * @param effectiveTime  the value for con_diss_agr.EFFECTIVE_TIME
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public void setEffectiveTime(Date effectiveTime) {
		this.effectiveTime = effectiveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_diss_agr.RETRUN_RENT_AMT
	 * @return  the value of con_diss_agr.RETRUN_RENT_AMT
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public BigDecimal getRetrunRentAmt() {
		return retrunRentAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_diss_agr.RETRUN_RENT_AMT
	 * @param retrunRentAmt  the value for con_diss_agr.RETRUN_RENT_AMT
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public void setRetrunRentAmt(BigDecimal retrunRentAmt) {
		this.retrunRentAmt = retrunRentAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_diss_agr.PAYMENT_PERSON_TYPE
	 * @return  the value of con_diss_agr.PAYMENT_PERSON_TYPE
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public Integer getPaymentPersonType() {
		return paymentPersonType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_diss_agr.PAYMENT_PERSON_TYPE
	 * @param paymentPersonType  the value for con_diss_agr.PAYMENT_PERSON_TYPE
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public void setPaymentPersonType(Integer paymentPersonType) {
		this.paymentPersonType = paymentPersonType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_diss_agr.PAYMENT_AMT
	 * @return  the value of con_diss_agr.PAYMENT_AMT
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public BigDecimal getPaymentAmt() {
		return paymentAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_diss_agr.PAYMENT_AMT
	 * @param paymentAmt  the value for con_diss_agr.PAYMENT_AMT
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public void setPaymentAmt(BigDecimal paymentAmt) {
		this.paymentAmt = paymentAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_diss_agr.PAYMENT_FROM
	 * @return  the value of con_diss_agr.PAYMENT_FROM
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public String getPaymentFrom() {
		return paymentFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_diss_agr.PAYMENT_FROM
	 * @param paymentFrom  the value for con_diss_agr.PAYMENT_FROM
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public void setPaymentFrom(String paymentFrom) {
		this.paymentFrom = paymentFrom == null ? null : paymentFrom.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_diss_agr.CREATE_USER_TYPE
	 * @return  the value of con_diss_agr.CREATE_USER_TYPE
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public Integer getCreateUserType() {
		return createUserType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_diss_agr.CREATE_USER_TYPE
	 * @param createUserType  the value for con_diss_agr.CREATE_USER_TYPE
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public void setCreateUserType(Integer createUserType) {
		this.createUserType = createUserType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_diss_agr.PAYMENT_TO
	 * @return  the value of con_diss_agr.PAYMENT_TO
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public String getPaymentTo() {
		return paymentTo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_diss_agr.PAYMENT_TO
	 * @param paymentTo  the value for con_diss_agr.PAYMENT_TO
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public void setPaymentTo(String paymentTo) {
		this.paymentTo = paymentTo == null ? null : paymentTo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_diss_agr.PAYMENT_DEPOSIT_AMT
	 * @return  the value of con_diss_agr.PAYMENT_DEPOSIT_AMT
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public BigDecimal getPaymentDepositAmt() {
		return paymentDepositAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_diss_agr.PAYMENT_DEPOSIT_AMT
	 * @param paymentDepositAmt  the value for con_diss_agr.PAYMENT_DEPOSIT_AMT
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public void setPaymentDepositAmt(BigDecimal paymentDepositAmt) {
		this.paymentDepositAmt = paymentDepositAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_diss_agr.PAYMENT_DEPOSIT_FLG
	 * @return  the value of con_diss_agr.PAYMENT_DEPOSIT_FLG
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public Short getPaymentDepositFlg() {
		return paymentDepositFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_diss_agr.PAYMENT_DEPOSIT_FLG
	 * @param paymentDepositFlg  the value for con_diss_agr.PAYMENT_DEPOSIT_FLG
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public void setPaymentDepositFlg(Short paymentDepositFlg) {
		this.paymentDepositFlg = paymentDepositFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_diss_agr.STATUS
	 * @return  the value of con_diss_agr.STATUS
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_diss_agr.STATUS
	 * @param status  the value for con_diss_agr.STATUS
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_diss_agr.REJECT_TYPE
	 * @return  the value of con_diss_agr.REJECT_TYPE
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public Integer getRejectType() {
		return rejectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_diss_agr.REJECT_TYPE
	 * @param rejectType  the value for con_diss_agr.REJECT_TYPE
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public void setRejectType(Integer rejectType) {
		this.rejectType = rejectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_diss_agr.REJECT_REASON
	 * @return  the value of con_diss_agr.REJECT_REASON
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public String getRejectReason() {
		return rejectReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_diss_agr.REJECT_REASON
	 * @param rejectReason  the value for con_diss_agr.REJECT_REASON
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public void setRejectReason(String rejectReason) {
		this.rejectReason = rejectReason == null ? null : rejectReason.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_diss_agr.LOCK_USERID
	 * @return  the value of con_diss_agr.LOCK_USERID
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public String getLockUserid() {
		return lockUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_diss_agr.LOCK_USERID
	 * @param lockUserid  the value for con_diss_agr.LOCK_USERID
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public void setLockUserid(String lockUserid) {
		this.lockUserid = lockUserid == null ? null : lockUserid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_diss_agr.LOCK_TIME
	 * @return  the value of con_diss_agr.LOCK_TIME
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public Date getLockTime() {
		return lockTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_diss_agr.LOCK_TIME
	 * @param lockTime  the value for con_diss_agr.LOCK_TIME
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	public void setLockTime(Date lockTime) {
		this.lockTime = lockTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_diss_agr
	 * @mbggenerated  Thu Dec 24 09:13:03 CST 2015
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", pindex=").append(pindex);
		sb.append(", no=").append(no);
		sb.append(", cid=").append(cid);
		sb.append(", reason=").append(reason);
		sb.append(", toSpecial=").append(toSpecial);
		sb.append(", description=").append(description);
		sb.append(", effectiveTime=").append(effectiveTime);
		sb.append(", retrunRentAmt=").append(retrunRentAmt);
		sb.append(", paymentPersonType=").append(paymentPersonType);
		sb.append(", paymentAmt=").append(paymentAmt);
		sb.append(", paymentFrom=").append(paymentFrom);
		sb.append(", createUserType=").append(createUserType);
		sb.append(", paymentTo=").append(paymentTo);
		sb.append(", paymentDepositAmt=").append(paymentDepositAmt);
		sb.append(", paymentDepositFlg=").append(paymentDepositFlg);
		sb.append(", status=").append(status);
		sb.append(", rejectType=").append(rejectType);
		sb.append(", rejectReason=").append(rejectReason);
		sb.append(", lockUserid=").append(lockUserid);
		sb.append(", lockTime=").append(lockTime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	public String getDissStatusName() {
		return dissStatusName;
	}

	public void setDissStatusName(String dissStatusName) {
		this.dissStatusName = dissStatusName;
	}

	 

	public String getPaymentPersonTypeName() {
		return paymentPersonTypeName;
	}

	public void setPaymentPersonTypeName(String paymentPersonTypeName) {
		this.paymentPersonTypeName = paymentPersonTypeName;
	}

	public String getReasonName() {
		return reasonName;
	}

	public void setReasonName(String reasonName) {
		this.reasonName = reasonName;
	}

	public ConContract getConContract() {
		return conContract;
	}

	public void setConContract(ConContract conContract) {
		this.conContract = conContract;
	}

	public String getFormatSaveTime() {
		if (effectiveTime != null) {
			formatSaveTime = DateUtils.dateToStr(effectiveTime, DateUtils.DATE_YMD_PATERN);
		}
		return formatSaveTime;
	}

	public void setFormatSaveTime(String formatSaveTime) {
		this.formatSaveTime = formatSaveTime;
	}

	private String dissStatusName;
	
	private String reasonName;
	
	private String paymentPersonTypeName;
	
	private ConContract conContract;
	
	private String formatSaveTime;
	
}