package com.dlfc.zfgj.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ConDepositDistLogExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table con_deposit_dist_log
	 * @mbggenerated  Fri Apr 15 09:23:38 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table con_deposit_dist_log
	 * @mbggenerated  Fri Apr 15 09:23:38 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table con_deposit_dist_log
	 * @mbggenerated  Fri Apr 15 09:23:38 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_log
	 * @mbggenerated  Fri Apr 15 09:23:38 CST 2016
	 */
	public ConDepositDistLogExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_log
	 * @mbggenerated  Fri Apr 15 09:23:38 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_log
	 * @mbggenerated  Fri Apr 15 09:23:38 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_log
	 * @mbggenerated  Fri Apr 15 09:23:38 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_log
	 * @mbggenerated  Fri Apr 15 09:23:38 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_log
	 * @mbggenerated  Fri Apr 15 09:23:38 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_log
	 * @mbggenerated  Fri Apr 15 09:23:38 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_log
	 * @mbggenerated  Fri Apr 15 09:23:38 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_log
	 * @mbggenerated  Fri Apr 15 09:23:38 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_log
	 * @mbggenerated  Fri Apr 15 09:23:38 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_dist_log
	 * @mbggenerated  Fri Apr 15 09:23:38 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table con_deposit_dist_log
	 * @mbggenerated  Fri Apr 15 09:23:38 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andPindexIsNull() {
			addCriterion("PINDEX is null");
			return (Criteria) this;
		}

		public Criteria andPindexIsNotNull() {
			addCriterion("PINDEX is not null");
			return (Criteria) this;
		}

		public Criteria andPindexEqualTo(Integer value) {
			addCriterion("PINDEX =", value, "pindex");
			return (Criteria) this;
		}

		public Criteria andPindexNotEqualTo(Integer value) {
			addCriterion("PINDEX <>", value, "pindex");
			return (Criteria) this;
		}

		public Criteria andPindexGreaterThan(Integer value) {
			addCriterion("PINDEX >", value, "pindex");
			return (Criteria) this;
		}

		public Criteria andPindexGreaterThanOrEqualTo(Integer value) {
			addCriterion("PINDEX >=", value, "pindex");
			return (Criteria) this;
		}

		public Criteria andPindexLessThan(Integer value) {
			addCriterion("PINDEX <", value, "pindex");
			return (Criteria) this;
		}

		public Criteria andPindexLessThanOrEqualTo(Integer value) {
			addCriterion("PINDEX <=", value, "pindex");
			return (Criteria) this;
		}

		public Criteria andPindexIn(List<Integer> values) {
			addCriterion("PINDEX in", values, "pindex");
			return (Criteria) this;
		}

		public Criteria andPindexNotIn(List<Integer> values) {
			addCriterion("PINDEX not in", values, "pindex");
			return (Criteria) this;
		}

		public Criteria andPindexBetween(Integer value1, Integer value2) {
			addCriterion("PINDEX between", value1, value2, "pindex");
			return (Criteria) this;
		}

		public Criteria andPindexNotBetween(Integer value1, Integer value2) {
			addCriterion("PINDEX not between", value1, value2, "pindex");
			return (Criteria) this;
		}

		public Criteria andAgrIdIsNull() {
			addCriterion("AGR_ID is null");
			return (Criteria) this;
		}

		public Criteria andAgrIdIsNotNull() {
			addCriterion("AGR_ID is not null");
			return (Criteria) this;
		}

		public Criteria andAgrIdEqualTo(String value) {
			addCriterion("AGR_ID =", value, "agrId");
			return (Criteria) this;
		}

		public Criteria andAgrIdNotEqualTo(String value) {
			addCriterion("AGR_ID <>", value, "agrId");
			return (Criteria) this;
		}

		public Criteria andAgrIdGreaterThan(String value) {
			addCriterion("AGR_ID >", value, "agrId");
			return (Criteria) this;
		}

		public Criteria andAgrIdGreaterThanOrEqualTo(String value) {
			addCriterion("AGR_ID >=", value, "agrId");
			return (Criteria) this;
		}

		public Criteria andAgrIdLessThan(String value) {
			addCriterion("AGR_ID <", value, "agrId");
			return (Criteria) this;
		}

		public Criteria andAgrIdLessThanOrEqualTo(String value) {
			addCriterion("AGR_ID <=", value, "agrId");
			return (Criteria) this;
		}

		public Criteria andAgrIdLike(String value) {
			addCriterion("AGR_ID like", value, "agrId");
			return (Criteria) this;
		}

		public Criteria andAgrIdNotLike(String value) {
			addCriterion("AGR_ID not like", value, "agrId");
			return (Criteria) this;
		}

		public Criteria andAgrIdIn(List<String> values) {
			addCriterion("AGR_ID in", values, "agrId");
			return (Criteria) this;
		}

		public Criteria andAgrIdNotIn(List<String> values) {
			addCriterion("AGR_ID not in", values, "agrId");
			return (Criteria) this;
		}

		public Criteria andAgrIdBetween(String value1, String value2) {
			addCriterion("AGR_ID between", value1, value2, "agrId");
			return (Criteria) this;
		}

		public Criteria andAgrIdNotBetween(String value1, String value2) {
			addCriterion("AGR_ID not between", value1, value2, "agrId");
			return (Criteria) this;
		}

		public Criteria andNoIsNull() {
			addCriterion("NO is null");
			return (Criteria) this;
		}

		public Criteria andNoIsNotNull() {
			addCriterion("NO is not null");
			return (Criteria) this;
		}

		public Criteria andNoEqualTo(String value) {
			addCriterion("NO =", value, "no");
			return (Criteria) this;
		}

		public Criteria andNoNotEqualTo(String value) {
			addCriterion("NO <>", value, "no");
			return (Criteria) this;
		}

		public Criteria andNoGreaterThan(String value) {
			addCriterion("NO >", value, "no");
			return (Criteria) this;
		}

		public Criteria andNoGreaterThanOrEqualTo(String value) {
			addCriterion("NO >=", value, "no");
			return (Criteria) this;
		}

		public Criteria andNoLessThan(String value) {
			addCriterion("NO <", value, "no");
			return (Criteria) this;
		}

		public Criteria andNoLessThanOrEqualTo(String value) {
			addCriterion("NO <=", value, "no");
			return (Criteria) this;
		}

		public Criteria andNoLike(String value) {
			addCriterion("NO like", value, "no");
			return (Criteria) this;
		}

		public Criteria andNoNotLike(String value) {
			addCriterion("NO not like", value, "no");
			return (Criteria) this;
		}

		public Criteria andNoIn(List<String> values) {
			addCriterion("NO in", values, "no");
			return (Criteria) this;
		}

		public Criteria andNoNotIn(List<String> values) {
			addCriterion("NO not in", values, "no");
			return (Criteria) this;
		}

		public Criteria andNoBetween(String value1, String value2) {
			addCriterion("NO between", value1, value2, "no");
			return (Criteria) this;
		}

		public Criteria andNoNotBetween(String value1, String value2) {
			addCriterion("NO not between", value1, value2, "no");
			return (Criteria) this;
		}

		public Criteria andCidIsNull() {
			addCriterion("CID is null");
			return (Criteria) this;
		}

		public Criteria andCidIsNotNull() {
			addCriterion("CID is not null");
			return (Criteria) this;
		}

		public Criteria andCidEqualTo(String value) {
			addCriterion("CID =", value, "cid");
			return (Criteria) this;
		}

		public Criteria andCidNotEqualTo(String value) {
			addCriterion("CID <>", value, "cid");
			return (Criteria) this;
		}

		public Criteria andCidGreaterThan(String value) {
			addCriterion("CID >", value, "cid");
			return (Criteria) this;
		}

		public Criteria andCidGreaterThanOrEqualTo(String value) {
			addCriterion("CID >=", value, "cid");
			return (Criteria) this;
		}

		public Criteria andCidLessThan(String value) {
			addCriterion("CID <", value, "cid");
			return (Criteria) this;
		}

		public Criteria andCidLessThanOrEqualTo(String value) {
			addCriterion("CID <=", value, "cid");
			return (Criteria) this;
		}

		public Criteria andCidLike(String value) {
			addCriterion("CID like", value, "cid");
			return (Criteria) this;
		}

		public Criteria andCidNotLike(String value) {
			addCriterion("CID not like", value, "cid");
			return (Criteria) this;
		}

		public Criteria andCidIn(List<String> values) {
			addCriterion("CID in", values, "cid");
			return (Criteria) this;
		}

		public Criteria andCidNotIn(List<String> values) {
			addCriterion("CID not in", values, "cid");
			return (Criteria) this;
		}

		public Criteria andCidBetween(String value1, String value2) {
			addCriterion("CID between", value1, value2, "cid");
			return (Criteria) this;
		}

		public Criteria andCidNotBetween(String value1, String value2) {
			addCriterion("CID not between", value1, value2, "cid");
			return (Criteria) this;
		}

		public Criteria andDeductAmtIsNull() {
			addCriterion("DEDUCT_AMT is null");
			return (Criteria) this;
		}

		public Criteria andDeductAmtIsNotNull() {
			addCriterion("DEDUCT_AMT is not null");
			return (Criteria) this;
		}

		public Criteria andDeductAmtEqualTo(BigDecimal value) {
			addCriterion("DEDUCT_AMT =", value, "deductAmt");
			return (Criteria) this;
		}

		public Criteria andDeductAmtNotEqualTo(BigDecimal value) {
			addCriterion("DEDUCT_AMT <>", value, "deductAmt");
			return (Criteria) this;
		}

		public Criteria andDeductAmtGreaterThan(BigDecimal value) {
			addCriterion("DEDUCT_AMT >", value, "deductAmt");
			return (Criteria) this;
		}

		public Criteria andDeductAmtGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("DEDUCT_AMT >=", value, "deductAmt");
			return (Criteria) this;
		}

		public Criteria andDeductAmtLessThan(BigDecimal value) {
			addCriterion("DEDUCT_AMT <", value, "deductAmt");
			return (Criteria) this;
		}

		public Criteria andDeductAmtLessThanOrEqualTo(BigDecimal value) {
			addCriterion("DEDUCT_AMT <=", value, "deductAmt");
			return (Criteria) this;
		}

		public Criteria andDeductAmtIn(List<BigDecimal> values) {
			addCriterion("DEDUCT_AMT in", values, "deductAmt");
			return (Criteria) this;
		}

		public Criteria andDeductAmtNotIn(List<BigDecimal> values) {
			addCriterion("DEDUCT_AMT not in", values, "deductAmt");
			return (Criteria) this;
		}

		public Criteria andDeductAmtBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("DEDUCT_AMT between", value1, value2, "deductAmt");
			return (Criteria) this;
		}

		public Criteria andDeductAmtNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("DEDUCT_AMT not between", value1, value2, "deductAmt");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("STATUS like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("STATUS not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andVerIsNull() {
			addCriterion("VER is null");
			return (Criteria) this;
		}

		public Criteria andVerIsNotNull() {
			addCriterion("VER is not null");
			return (Criteria) this;
		}

		public Criteria andVerEqualTo(String value) {
			addCriterion("VER =", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerNotEqualTo(String value) {
			addCriterion("VER <>", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerGreaterThan(String value) {
			addCriterion("VER >", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerGreaterThanOrEqualTo(String value) {
			addCriterion("VER >=", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerLessThan(String value) {
			addCriterion("VER <", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerLessThanOrEqualTo(String value) {
			addCriterion("VER <=", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerLike(String value) {
			addCriterion("VER like", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerNotLike(String value) {
			addCriterion("VER not like", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerIn(List<String> values) {
			addCriterion("VER in", values, "ver");
			return (Criteria) this;
		}

		public Criteria andVerNotIn(List<String> values) {
			addCriterion("VER not in", values, "ver");
			return (Criteria) this;
		}

		public Criteria andVerBetween(String value1, String value2) {
			addCriterion("VER between", value1, value2, "ver");
			return (Criteria) this;
		}

		public Criteria andVerNotBetween(String value1, String value2) {
			addCriterion("VER not between", value1, value2, "ver");
			return (Criteria) this;
		}

		public Criteria andChargeReasonIsNull() {
			addCriterion("CHARGE_REASON is null");
			return (Criteria) this;
		}

		public Criteria andChargeReasonIsNotNull() {
			addCriterion("CHARGE_REASON is not null");
			return (Criteria) this;
		}

		public Criteria andChargeReasonEqualTo(Integer value) {
			addCriterion("CHARGE_REASON =", value, "chargeReason");
			return (Criteria) this;
		}

		public Criteria andChargeReasonNotEqualTo(Integer value) {
			addCriterion("CHARGE_REASON <>", value, "chargeReason");
			return (Criteria) this;
		}

		public Criteria andChargeReasonGreaterThan(Integer value) {
			addCriterion("CHARGE_REASON >", value, "chargeReason");
			return (Criteria) this;
		}

		public Criteria andChargeReasonGreaterThanOrEqualTo(Integer value) {
			addCriterion("CHARGE_REASON >=", value, "chargeReason");
			return (Criteria) this;
		}

		public Criteria andChargeReasonLessThan(Integer value) {
			addCriterion("CHARGE_REASON <", value, "chargeReason");
			return (Criteria) this;
		}

		public Criteria andChargeReasonLessThanOrEqualTo(Integer value) {
			addCriterion("CHARGE_REASON <=", value, "chargeReason");
			return (Criteria) this;
		}

		public Criteria andChargeReasonIn(List<Integer> values) {
			addCriterion("CHARGE_REASON in", values, "chargeReason");
			return (Criteria) this;
		}

		public Criteria andChargeReasonNotIn(List<Integer> values) {
			addCriterion("CHARGE_REASON not in", values, "chargeReason");
			return (Criteria) this;
		}

		public Criteria andChargeReasonBetween(Integer value1, Integer value2) {
			addCriterion("CHARGE_REASON between", value1, value2, "chargeReason");
			return (Criteria) this;
		}

		public Criteria andChargeReasonNotBetween(Integer value1, Integer value2) {
			addCriterion("CHARGE_REASON not between", value1, value2, "chargeReason");
			return (Criteria) this;
		}

		public Criteria andRejectTypeIsNull() {
			addCriterion("REJECT_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andRejectTypeIsNotNull() {
			addCriterion("REJECT_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andRejectTypeEqualTo(Integer value) {
			addCriterion("REJECT_TYPE =", value, "rejectType");
			return (Criteria) this;
		}

		public Criteria andRejectTypeNotEqualTo(Integer value) {
			addCriterion("REJECT_TYPE <>", value, "rejectType");
			return (Criteria) this;
		}

		public Criteria andRejectTypeGreaterThan(Integer value) {
			addCriterion("REJECT_TYPE >", value, "rejectType");
			return (Criteria) this;
		}

		public Criteria andRejectTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("REJECT_TYPE >=", value, "rejectType");
			return (Criteria) this;
		}

		public Criteria andRejectTypeLessThan(Integer value) {
			addCriterion("REJECT_TYPE <", value, "rejectType");
			return (Criteria) this;
		}

		public Criteria andRejectTypeLessThanOrEqualTo(Integer value) {
			addCriterion("REJECT_TYPE <=", value, "rejectType");
			return (Criteria) this;
		}

		public Criteria andRejectTypeIn(List<Integer> values) {
			addCriterion("REJECT_TYPE in", values, "rejectType");
			return (Criteria) this;
		}

		public Criteria andRejectTypeNotIn(List<Integer> values) {
			addCriterion("REJECT_TYPE not in", values, "rejectType");
			return (Criteria) this;
		}

		public Criteria andRejectTypeBetween(Integer value1, Integer value2) {
			addCriterion("REJECT_TYPE between", value1, value2, "rejectType");
			return (Criteria) this;
		}

		public Criteria andRejectTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("REJECT_TYPE not between", value1, value2, "rejectType");
			return (Criteria) this;
		}

		public Criteria andRejectReasonIsNull() {
			addCriterion("REJECT_REASON is null");
			return (Criteria) this;
		}

		public Criteria andRejectReasonIsNotNull() {
			addCriterion("REJECT_REASON is not null");
			return (Criteria) this;
		}

		public Criteria andRejectReasonEqualTo(String value) {
			addCriterion("REJECT_REASON =", value, "rejectReason");
			return (Criteria) this;
		}

		public Criteria andRejectReasonNotEqualTo(String value) {
			addCriterion("REJECT_REASON <>", value, "rejectReason");
			return (Criteria) this;
		}

		public Criteria andRejectReasonGreaterThan(String value) {
			addCriterion("REJECT_REASON >", value, "rejectReason");
			return (Criteria) this;
		}

		public Criteria andRejectReasonGreaterThanOrEqualTo(String value) {
			addCriterion("REJECT_REASON >=", value, "rejectReason");
			return (Criteria) this;
		}

		public Criteria andRejectReasonLessThan(String value) {
			addCriterion("REJECT_REASON <", value, "rejectReason");
			return (Criteria) this;
		}

		public Criteria andRejectReasonLessThanOrEqualTo(String value) {
			addCriterion("REJECT_REASON <=", value, "rejectReason");
			return (Criteria) this;
		}

		public Criteria andRejectReasonLike(String value) {
			addCriterion("REJECT_REASON like", value, "rejectReason");
			return (Criteria) this;
		}

		public Criteria andRejectReasonNotLike(String value) {
			addCriterion("REJECT_REASON not like", value, "rejectReason");
			return (Criteria) this;
		}

		public Criteria andRejectReasonIn(List<String> values) {
			addCriterion("REJECT_REASON in", values, "rejectReason");
			return (Criteria) this;
		}

		public Criteria andRejectReasonNotIn(List<String> values) {
			addCriterion("REJECT_REASON not in", values, "rejectReason");
			return (Criteria) this;
		}

		public Criteria andRejectReasonBetween(String value1, String value2) {
			addCriterion("REJECT_REASON between", value1, value2, "rejectReason");
			return (Criteria) this;
		}

		public Criteria andRejectReasonNotBetween(String value1, String value2) {
			addCriterion("REJECT_REASON not between", value1, value2, "rejectReason");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNull() {
			addCriterion("CREATE_USER is null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNotNull() {
			addCriterion("CREATE_USER is not null");
			return (Criteria) this;
		}

		public Criteria andCreateUserEqualTo(String value) {
			addCriterion("CREATE_USER =", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotEqualTo(String value) {
			addCriterion("CREATE_USER <>", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThan(String value) {
			addCriterion("CREATE_USER >", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
			addCriterion("CREATE_USER >=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThan(String value) {
			addCriterion("CREATE_USER <", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThanOrEqualTo(String value) {
			addCriterion("CREATE_USER <=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLike(String value) {
			addCriterion("CREATE_USER like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotLike(String value) {
			addCriterion("CREATE_USER not like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserIn(List<String> values) {
			addCriterion("CREATE_USER in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotIn(List<String> values) {
			addCriterion("CREATE_USER not in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserBetween(String value1, String value2) {
			addCriterion("CREATE_USER between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotBetween(String value1, String value2) {
			addCriterion("CREATE_USER not between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityIsNull() {
			addCriterion("CREATE_USER_IDENTITY is null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityIsNotNull() {
			addCriterion("CREATE_USER_IDENTITY is not null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityEqualTo(Short value) {
			addCriterion("CREATE_USER_IDENTITY =", value, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityNotEqualTo(Short value) {
			addCriterion("CREATE_USER_IDENTITY <>", value, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityGreaterThan(Short value) {
			addCriterion("CREATE_USER_IDENTITY >", value, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityGreaterThanOrEqualTo(Short value) {
			addCriterion("CREATE_USER_IDENTITY >=", value, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityLessThan(Short value) {
			addCriterion("CREATE_USER_IDENTITY <", value, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityLessThanOrEqualTo(Short value) {
			addCriterion("CREATE_USER_IDENTITY <=", value, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityIn(List<Short> values) {
			addCriterion("CREATE_USER_IDENTITY in", values, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityNotIn(List<Short> values) {
			addCriterion("CREATE_USER_IDENTITY not in", values, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityBetween(Short value1, Short value2) {
			addCriterion("CREATE_USER_IDENTITY between", value1, value2, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityNotBetween(Short value1, Short value2) {
			addCriterion("CREATE_USER_IDENTITY not between", value1, value2, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifyUserIsNull() {
			addCriterion("MODIFY_USER is null");
			return (Criteria) this;
		}

		public Criteria andModifyUserIsNotNull() {
			addCriterion("MODIFY_USER is not null");
			return (Criteria) this;
		}

		public Criteria andModifyUserEqualTo(String value) {
			addCriterion("MODIFY_USER =", value, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserNotEqualTo(String value) {
			addCriterion("MODIFY_USER <>", value, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserGreaterThan(String value) {
			addCriterion("MODIFY_USER >", value, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserGreaterThanOrEqualTo(String value) {
			addCriterion("MODIFY_USER >=", value, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserLessThan(String value) {
			addCriterion("MODIFY_USER <", value, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserLessThanOrEqualTo(String value) {
			addCriterion("MODIFY_USER <=", value, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserLike(String value) {
			addCriterion("MODIFY_USER like", value, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserNotLike(String value) {
			addCriterion("MODIFY_USER not like", value, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserIn(List<String> values) {
			addCriterion("MODIFY_USER in", values, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserNotIn(List<String> values) {
			addCriterion("MODIFY_USER not in", values, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserBetween(String value1, String value2) {
			addCriterion("MODIFY_USER between", value1, value2, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserNotBetween(String value1, String value2) {
			addCriterion("MODIFY_USER not between", value1, value2, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityIsNull() {
			addCriterion("MODIFY_USER_IDENTITY is null");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityIsNotNull() {
			addCriterion("MODIFY_USER_IDENTITY is not null");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityEqualTo(Short value) {
			addCriterion("MODIFY_USER_IDENTITY =", value, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityNotEqualTo(Short value) {
			addCriterion("MODIFY_USER_IDENTITY <>", value, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityGreaterThan(Short value) {
			addCriterion("MODIFY_USER_IDENTITY >", value, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityGreaterThanOrEqualTo(Short value) {
			addCriterion("MODIFY_USER_IDENTITY >=", value, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityLessThan(Short value) {
			addCriterion("MODIFY_USER_IDENTITY <", value, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityLessThanOrEqualTo(Short value) {
			addCriterion("MODIFY_USER_IDENTITY <=", value, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityIn(List<Short> values) {
			addCriterion("MODIFY_USER_IDENTITY in", values, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityNotIn(List<Short> values) {
			addCriterion("MODIFY_USER_IDENTITY not in", values, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityBetween(Short value1, Short value2) {
			addCriterion("MODIFY_USER_IDENTITY between", value1, value2, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityNotBetween(Short value1, Short value2) {
			addCriterion("MODIFY_USER_IDENTITY not between", value1, value2, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNull() {
			addCriterion("MODIFY_TIME is null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNotNull() {
			addCriterion("MODIFY_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeEqualTo(Date value) {
			addCriterion("MODIFY_TIME =", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotEqualTo(Date value) {
			addCriterion("MODIFY_TIME <>", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThan(Date value) {
			addCriterion("MODIFY_TIME >", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("MODIFY_TIME >=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThan(Date value) {
			addCriterion("MODIFY_TIME <", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
			addCriterion("MODIFY_TIME <=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIn(List<Date> values) {
			addCriterion("MODIFY_TIME in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotIn(List<Date> values) {
			addCriterion("MODIFY_TIME not in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeBetween(Date value1, Date value2) {
			addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
			addCriterion("MODIFY_TIME not between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIsNull() {
			addCriterion("DELETE_FLG is null");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIsNotNull() {
			addCriterion("DELETE_FLG is not null");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgEqualTo(Short value) {
			addCriterion("DELETE_FLG =", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotEqualTo(Short value) {
			addCriterion("DELETE_FLG <>", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgGreaterThan(Short value) {
			addCriterion("DELETE_FLG >", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgGreaterThanOrEqualTo(Short value) {
			addCriterion("DELETE_FLG >=", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgLessThan(Short value) {
			addCriterion("DELETE_FLG <", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgLessThanOrEqualTo(Short value) {
			addCriterion("DELETE_FLG <=", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIn(List<Short> values) {
			addCriterion("DELETE_FLG in", values, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotIn(List<Short> values) {
			addCriterion("DELETE_FLG not in", values, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgBetween(Short value1, Short value2) {
			addCriterion("DELETE_FLG between", value1, value2, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotBetween(Short value1, Short value2) {
			addCriterion("DELETE_FLG not between", value1, value2, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andVersionIsNull() {
			addCriterion("VERSION is null");
			return (Criteria) this;
		}

		public Criteria andVersionIsNotNull() {
			addCriterion("VERSION is not null");
			return (Criteria) this;
		}

		public Criteria andVersionEqualTo(Integer value) {
			addCriterion("VERSION =", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotEqualTo(Integer value) {
			addCriterion("VERSION <>", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThan(Integer value) {
			addCriterion("VERSION >", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
			addCriterion("VERSION >=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThan(Integer value) {
			addCriterion("VERSION <", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThanOrEqualTo(Integer value) {
			addCriterion("VERSION <=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionIn(List<Integer> values) {
			addCriterion("VERSION in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotIn(List<Integer> values) {
			addCriterion("VERSION not in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionBetween(Integer value1, Integer value2) {
			addCriterion("VERSION between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotBetween(Integer value1, Integer value2) {
			addCriterion("VERSION not between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andOperatorIsNull() {
			addCriterion("OPERATOR is null");
			return (Criteria) this;
		}

		public Criteria andOperatorIsNotNull() {
			addCriterion("OPERATOR is not null");
			return (Criteria) this;
		}

		public Criteria andOperatorEqualTo(String value) {
			addCriterion("OPERATOR =", value, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorNotEqualTo(String value) {
			addCriterion("OPERATOR <>", value, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorGreaterThan(String value) {
			addCriterion("OPERATOR >", value, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorGreaterThanOrEqualTo(String value) {
			addCriterion("OPERATOR >=", value, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorLessThan(String value) {
			addCriterion("OPERATOR <", value, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorLessThanOrEqualTo(String value) {
			addCriterion("OPERATOR <=", value, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorLike(String value) {
			addCriterion("OPERATOR like", value, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorNotLike(String value) {
			addCriterion("OPERATOR not like", value, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorIn(List<String> values) {
			addCriterion("OPERATOR in", values, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorNotIn(List<String> values) {
			addCriterion("OPERATOR not in", values, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorBetween(String value1, String value2) {
			addCriterion("OPERATOR between", value1, value2, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorNotBetween(String value1, String value2) {
			addCriterion("OPERATOR not between", value1, value2, "operator");
			return (Criteria) this;
		}

		public Criteria andOptEventIsNull() {
			addCriterion("OPT_EVENT is null");
			return (Criteria) this;
		}

		public Criteria andOptEventIsNotNull() {
			addCriterion("OPT_EVENT is not null");
			return (Criteria) this;
		}

		public Criteria andOptEventEqualTo(Integer value) {
			addCriterion("OPT_EVENT =", value, "optEvent");
			return (Criteria) this;
		}

		public Criteria andOptEventNotEqualTo(Integer value) {
			addCriterion("OPT_EVENT <>", value, "optEvent");
			return (Criteria) this;
		}

		public Criteria andOptEventGreaterThan(Integer value) {
			addCriterion("OPT_EVENT >", value, "optEvent");
			return (Criteria) this;
		}

		public Criteria andOptEventGreaterThanOrEqualTo(Integer value) {
			addCriterion("OPT_EVENT >=", value, "optEvent");
			return (Criteria) this;
		}

		public Criteria andOptEventLessThan(Integer value) {
			addCriterion("OPT_EVENT <", value, "optEvent");
			return (Criteria) this;
		}

		public Criteria andOptEventLessThanOrEqualTo(Integer value) {
			addCriterion("OPT_EVENT <=", value, "optEvent");
			return (Criteria) this;
		}

		public Criteria andOptEventIn(List<Integer> values) {
			addCriterion("OPT_EVENT in", values, "optEvent");
			return (Criteria) this;
		}

		public Criteria andOptEventNotIn(List<Integer> values) {
			addCriterion("OPT_EVENT not in", values, "optEvent");
			return (Criteria) this;
		}

		public Criteria andOptEventBetween(Integer value1, Integer value2) {
			addCriterion("OPT_EVENT between", value1, value2, "optEvent");
			return (Criteria) this;
		}

		public Criteria andOptEventNotBetween(Integer value1, Integer value2) {
			addCriterion("OPT_EVENT not between", value1, value2, "optEvent");
			return (Criteria) this;
		}

		public Criteria andDcrpIsNull() {
			addCriterion("DCRP is null");
			return (Criteria) this;
		}

		public Criteria andDcrpIsNotNull() {
			addCriterion("DCRP is not null");
			return (Criteria) this;
		}

		public Criteria andDcrpEqualTo(String value) {
			addCriterion("DCRP =", value, "dcrp");
			return (Criteria) this;
		}

		public Criteria andDcrpNotEqualTo(String value) {
			addCriterion("DCRP <>", value, "dcrp");
			return (Criteria) this;
		}

		public Criteria andDcrpGreaterThan(String value) {
			addCriterion("DCRP >", value, "dcrp");
			return (Criteria) this;
		}

		public Criteria andDcrpGreaterThanOrEqualTo(String value) {
			addCriterion("DCRP >=", value, "dcrp");
			return (Criteria) this;
		}

		public Criteria andDcrpLessThan(String value) {
			addCriterion("DCRP <", value, "dcrp");
			return (Criteria) this;
		}

		public Criteria andDcrpLessThanOrEqualTo(String value) {
			addCriterion("DCRP <=", value, "dcrp");
			return (Criteria) this;
		}

		public Criteria andDcrpLike(String value) {
			addCriterion("DCRP like", value, "dcrp");
			return (Criteria) this;
		}

		public Criteria andDcrpNotLike(String value) {
			addCriterion("DCRP not like", value, "dcrp");
			return (Criteria) this;
		}

		public Criteria andDcrpIn(List<String> values) {
			addCriterion("DCRP in", values, "dcrp");
			return (Criteria) this;
		}

		public Criteria andDcrpNotIn(List<String> values) {
			addCriterion("DCRP not in", values, "dcrp");
			return (Criteria) this;
		}

		public Criteria andDcrpBetween(String value1, String value2) {
			addCriterion("DCRP between", value1, value2, "dcrp");
			return (Criteria) this;
		}

		public Criteria andDcrpNotBetween(String value1, String value2) {
			addCriterion("DCRP not between", value1, value2, "dcrp");
			return (Criteria) this;
		}

		public Criteria andOptTimeIsNull() {
			addCriterion("OPT_TIME is null");
			return (Criteria) this;
		}

		public Criteria andOptTimeIsNotNull() {
			addCriterion("OPT_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andOptTimeEqualTo(Date value) {
			addCriterion("OPT_TIME =", value, "optTime");
			return (Criteria) this;
		}

		public Criteria andOptTimeNotEqualTo(Date value) {
			addCriterion("OPT_TIME <>", value, "optTime");
			return (Criteria) this;
		}

		public Criteria andOptTimeGreaterThan(Date value) {
			addCriterion("OPT_TIME >", value, "optTime");
			return (Criteria) this;
		}

		public Criteria andOptTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("OPT_TIME >=", value, "optTime");
			return (Criteria) this;
		}

		public Criteria andOptTimeLessThan(Date value) {
			addCriterion("OPT_TIME <", value, "optTime");
			return (Criteria) this;
		}

		public Criteria andOptTimeLessThanOrEqualTo(Date value) {
			addCriterion("OPT_TIME <=", value, "optTime");
			return (Criteria) this;
		}

		public Criteria andOptTimeIn(List<Date> values) {
			addCriterion("OPT_TIME in", values, "optTime");
			return (Criteria) this;
		}

		public Criteria andOptTimeNotIn(List<Date> values) {
			addCriterion("OPT_TIME not in", values, "optTime");
			return (Criteria) this;
		}

		public Criteria andOptTimeBetween(Date value1, Date value2) {
			addCriterion("OPT_TIME between", value1, value2, "optTime");
			return (Criteria) this;
		}

		public Criteria andOptTimeNotBetween(Date value1, Date value2) {
			addCriterion("OPT_TIME not between", value1, value2, "optTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table con_deposit_dist_log
	 * @mbggenerated  Fri Apr 15 09:23:38 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table con_deposit_dist_log
     *
     * @mbggenerated do_not_delete_during_merge Mon Dec 14 11:05:12 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}