package com.dlfc.zfgj.entity;

import com.dlfc.admin.common.persistence.MyDataEntity;

import java.io.Serializable;
import java.util.Date;

public class ConDepositLog extends MyDataEntity<ConDepositLog> implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_deposit_log.PINDEX
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	private Integer pindex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_deposit_log.DEPOSIT_ID
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	private String depositId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_deposit_log.CID
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	private String cid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_deposit_log.STATUS
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_deposit_log.DEAL_TIME
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	private Date dealTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_deposit_log.PAY_TIME
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	private Date payTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_deposit_log.VER
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	private String ver;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_deposit_log.DDA_ID
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	private String ddaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_deposit_log.NO
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	private String no;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_deposit_log.EFFECTIVE_TIME
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	private Date effectiveTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_deposit_log.OPERATOR
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	private String operator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_deposit_log.OPT_EVENT
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	private Integer optEvent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_deposit_log.DCRP
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	private String dcrp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column con_deposit_log.OPT_TIME
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	private Date optTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table con_deposit_log
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_deposit_log.PINDEX
	 * @return  the value of con_deposit_log.PINDEX
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	public Integer getPindex() {
		return pindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_deposit_log.PINDEX
	 * @param pindex  the value for con_deposit_log.PINDEX
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	public void setPindex(Integer pindex) {
		this.pindex = pindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_deposit_log.DEPOSIT_ID
	 * @return  the value of con_deposit_log.DEPOSIT_ID
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	public String getDepositId() {
		return depositId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_deposit_log.DEPOSIT_ID
	 * @param depositId  the value for con_deposit_log.DEPOSIT_ID
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	public void setDepositId(String depositId) {
		this.depositId = depositId == null ? null : depositId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_deposit_log.CID
	 * @return  the value of con_deposit_log.CID
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	public String getCid() {
		return cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_deposit_log.CID
	 * @param cid  the value for con_deposit_log.CID
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	public void setCid(String cid) {
		this.cid = cid == null ? null : cid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_deposit_log.STATUS
	 * @return  the value of con_deposit_log.STATUS
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_deposit_log.STATUS
	 * @param status  the value for con_deposit_log.STATUS
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_deposit_log.DEAL_TIME
	 * @return  the value of con_deposit_log.DEAL_TIME
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	public Date getDealTime() {
		return dealTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_deposit_log.DEAL_TIME
	 * @param dealTime  the value for con_deposit_log.DEAL_TIME
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	public void setDealTime(Date dealTime) {
		this.dealTime = dealTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_deposit_log.PAY_TIME
	 * @return  the value of con_deposit_log.PAY_TIME
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	public Date getPayTime() {
		return payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_deposit_log.PAY_TIME
	 * @param payTime  the value for con_deposit_log.PAY_TIME
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_deposit_log.VER
	 * @return  the value of con_deposit_log.VER
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	public String getVer() {
		return ver;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_deposit_log.VER
	 * @param ver  the value for con_deposit_log.VER
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	public void setVer(String ver) {
		this.ver = ver == null ? null : ver.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_deposit_log.DDA_ID
	 * @return  the value of con_deposit_log.DDA_ID
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	public String getDdaId() {
		return ddaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_deposit_log.DDA_ID
	 * @param ddaId  the value for con_deposit_log.DDA_ID
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	public void setDdaId(String ddaId) {
		this.ddaId = ddaId == null ? null : ddaId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_deposit_log.NO
	 * @return  the value of con_deposit_log.NO
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	public String getNo() {
		return no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_deposit_log.NO
	 * @param no  the value for con_deposit_log.NO
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	public void setNo(String no) {
		this.no = no == null ? null : no.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_deposit_log.EFFECTIVE_TIME
	 * @return  the value of con_deposit_log.EFFECTIVE_TIME
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	public Date getEffectiveTime() {
		return effectiveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_deposit_log.EFFECTIVE_TIME
	 * @param effectiveTime  the value for con_deposit_log.EFFECTIVE_TIME
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	public void setEffectiveTime(Date effectiveTime) {
		this.effectiveTime = effectiveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_deposit_log.OPERATOR
	 * @return  the value of con_deposit_log.OPERATOR
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	public String getOperator() {
		return operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_deposit_log.OPERATOR
	 * @param operator  the value for con_deposit_log.OPERATOR
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	public void setOperator(String operator) {
		this.operator = operator == null ? null : operator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_deposit_log.OPT_EVENT
	 * @return  the value of con_deposit_log.OPT_EVENT
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	public Integer getOptEvent() {
		return optEvent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_deposit_log.OPT_EVENT
	 * @param optEvent  the value for con_deposit_log.OPT_EVENT
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	public void setOptEvent(Integer optEvent) {
		this.optEvent = optEvent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_deposit_log.DCRP
	 * @return  the value of con_deposit_log.DCRP
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	public String getDcrp() {
		return dcrp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_deposit_log.DCRP
	 * @param dcrp  the value for con_deposit_log.DCRP
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	public void setDcrp(String dcrp) {
		this.dcrp = dcrp == null ? null : dcrp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column con_deposit_log.OPT_TIME
	 * @return  the value of con_deposit_log.OPT_TIME
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	public Date getOptTime() {
		return optTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column con_deposit_log.OPT_TIME
	 * @param optTime  the value for con_deposit_log.OPT_TIME
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	public void setOptTime(Date optTime) {
		this.optTime = optTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table con_deposit_log
	 * @mbggenerated  Mon Oct 24 16:44:11 CST 2016
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", pindex=").append(pindex);
		sb.append(", depositId=").append(depositId);
		sb.append(", cid=").append(cid);
		sb.append(", status=").append(status);
		sb.append(", dealTime=").append(dealTime);
		sb.append(", payTime=").append(payTime);
		sb.append(", ver=").append(ver);
		sb.append(", ddaId=").append(ddaId);
		sb.append(", no=").append(no);
		sb.append(", effectiveTime=").append(effectiveTime);
		sb.append(", operator=").append(operator);
		sb.append(", optEvent=").append(optEvent);
		sb.append(", dcrp=").append(dcrp);
		sb.append(", optTime=").append(optTime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}