package com.dlfc.zfgj.entity;

import com.dlfc.admin.common.persistence.MyDataEntity;

import java.io.Serializable;
import java.util.Date;

public class HouCoOwnerTempLog extends MyDataEntity<HouCoOwnerTempLog> implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hou_co_owner_temp_log.PINDEX
     *
     * @mbggenerated Thu Feb 25 15:23:11 CST 2016
     */
    private Integer pindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hou_co_owner_temp_log.OPERATOR
     *
     * @mbggenerated Thu Feb 25 15:23:11 CST 2016
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hou_co_owner_temp_log.OPT_TIME
     *
     * @mbggenerated Thu Feb 25 15:23:11 CST 2016
     */
    private Date optTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hou_co_owner_temp_log.OPT_EVENT
     *
     * @mbggenerated Thu Feb 25 15:23:11 CST 2016
     */
    private Integer optEvent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hou_co_owner_temp_log.DCRP
     *
     * @mbggenerated Thu Feb 25 15:23:11 CST 2016
     */
    private String dcrp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hou_co_owner_temp_log.HOU_INFO_LOG_ID
     *
     * @mbggenerated Thu Feb 25 15:23:11 CST 2016
     */
    private String houInfoLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hou_co_owner_temp_log.CO_PID
     *
     * @mbggenerated Thu Feb 25 15:23:11 CST 2016
     */
    private String coPid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hou_co_owner_temp_log.HID
     *
     * @mbggenerated Thu Feb 25 15:23:11 CST 2016
     */
    private String hid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hou_co_owner_temp_log
     *
     * @mbggenerated Thu Feb 25 15:23:11 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hou_co_owner_temp_log.PINDEX
     *
     * @return the value of hou_co_owner_temp_log.PINDEX
     *
     * @mbggenerated Thu Feb 25 15:23:11 CST 2016
     */
    public Integer getPindex() {
        return pindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hou_co_owner_temp_log.PINDEX
     *
     * @param pindex the value for hou_co_owner_temp_log.PINDEX
     *
     * @mbggenerated Thu Feb 25 15:23:11 CST 2016
     */
    public void setPindex(Integer pindex) {
        this.pindex = pindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hou_co_owner_temp_log.OPERATOR
     *
     * @return the value of hou_co_owner_temp_log.OPERATOR
     *
     * @mbggenerated Thu Feb 25 15:23:11 CST 2016
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hou_co_owner_temp_log.OPERATOR
     *
     * @param operator the value for hou_co_owner_temp_log.OPERATOR
     *
     * @mbggenerated Thu Feb 25 15:23:11 CST 2016
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hou_co_owner_temp_log.OPT_TIME
     *
     * @return the value of hou_co_owner_temp_log.OPT_TIME
     *
     * @mbggenerated Thu Feb 25 15:23:11 CST 2016
     */
    public Date getOptTime() {
        return optTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hou_co_owner_temp_log.OPT_TIME
     *
     * @param optTime the value for hou_co_owner_temp_log.OPT_TIME
     *
     * @mbggenerated Thu Feb 25 15:23:11 CST 2016
     */
    public void setOptTime(Date optTime) {
        this.optTime = optTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hou_co_owner_temp_log.OPT_EVENT
     *
     * @return the value of hou_co_owner_temp_log.OPT_EVENT
     *
     * @mbggenerated Thu Feb 25 15:23:11 CST 2016
     */
    public Integer getOptEvent() {
        return optEvent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hou_co_owner_temp_log.OPT_EVENT
     *
     * @param optEvent the value for hou_co_owner_temp_log.OPT_EVENT
     *
     * @mbggenerated Thu Feb 25 15:23:11 CST 2016
     */
    public void setOptEvent(Integer optEvent) {
        this.optEvent = optEvent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hou_co_owner_temp_log.DCRP
     *
     * @return the value of hou_co_owner_temp_log.DCRP
     *
     * @mbggenerated Thu Feb 25 15:23:11 CST 2016
     */
    public String getDcrp() {
        return dcrp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hou_co_owner_temp_log.DCRP
     *
     * @param dcrp the value for hou_co_owner_temp_log.DCRP
     *
     * @mbggenerated Thu Feb 25 15:23:11 CST 2016
     */
    public void setDcrp(String dcrp) {
        this.dcrp = dcrp == null ? null : dcrp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hou_co_owner_temp_log.HOU_INFO_LOG_ID
     *
     * @return the value of hou_co_owner_temp_log.HOU_INFO_LOG_ID
     *
     * @mbggenerated Thu Feb 25 15:23:11 CST 2016
     */
    public String getHouInfoLogId() {
        return houInfoLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hou_co_owner_temp_log.HOU_INFO_LOG_ID
     *
     * @param houInfoLogId the value for hou_co_owner_temp_log.HOU_INFO_LOG_ID
     *
     * @mbggenerated Thu Feb 25 15:23:11 CST 2016
     */
    public void setHouInfoLogId(String houInfoLogId) {
        this.houInfoLogId = houInfoLogId == null ? null : houInfoLogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hou_co_owner_temp_log.CO_PID
     *
     * @return the value of hou_co_owner_temp_log.CO_PID
     *
     * @mbggenerated Thu Feb 25 15:23:11 CST 2016
     */
    public String getCoPid() {
        return coPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hou_co_owner_temp_log.CO_PID
     *
     * @param coPid the value for hou_co_owner_temp_log.CO_PID
     *
     * @mbggenerated Thu Feb 25 15:23:11 CST 2016
     */
    public void setCoPid(String coPid) {
        this.coPid = coPid == null ? null : coPid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hou_co_owner_temp_log.HID
     *
     * @return the value of hou_co_owner_temp_log.HID
     *
     * @mbggenerated Thu Feb 25 15:23:11 CST 2016
     */
    public String getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hou_co_owner_temp_log.HID
     *
     * @param hid the value for hou_co_owner_temp_log.HID
     *
     * @mbggenerated Thu Feb 25 15:23:11 CST 2016
     */
    public void setHid(String hid) {
        this.hid = hid == null ? null : hid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hou_co_owner_temp_log
     *
     * @mbggenerated Thu Feb 25 15:23:11 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pindex=").append(pindex);
        sb.append(", operator=").append(operator);
        sb.append(", optTime=").append(optTime);
        sb.append(", optEvent=").append(optEvent);
        sb.append(", dcrp=").append(dcrp);
        sb.append(", houInfoLogId=").append(houInfoLogId);
        sb.append(", coPid=").append(coPid);
        sb.append(", hid=").append(hid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
    
    private String id;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
}