package com.dlfc.zfgj.entity;

import com.dlfc.admin.common.persistence.MyDataEntity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class HouLeaseInfo extends MyDataEntity<HouLeaseInfo> implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.PINDEX
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private Integer pindex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.LNO
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String lno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.PREFERENTIAL
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String preferential;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.ONLINE_PAYMENT
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String onlinePayment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.AUDIT_STATUS
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private Integer auditStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.LOCK_USERID
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String lockUserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.LOCK_TIME
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private Date lockTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.RELEASE_TIME
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private Date releaseTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.SOURCE_TYPE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private Integer sourceType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.REJECT_TYPE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private Integer rejectType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.REJECT_REASON
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String rejectReason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.RELEASE_STATUS
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private Integer releaseStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.SHELF_TYPE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private Integer shelfType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.SHELF_REASON
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String shelfReason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.HID
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String hid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.HOUSE_TYPE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private Integer houseType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.STATIONID
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String stationid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.CHECKIN_TIME
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private Date checkinTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.RENT_TYPE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String rentType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.LEASE_MODE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private Integer leaseMode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.RENT
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private BigDecimal rent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.VILLAGE_NAME
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String villageName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.DISTRICT
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String district;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.DISTRICT_NAME
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String districtName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.NO
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String no;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.FLOOR
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String floor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.BUILD_TIME
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String buildTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.APARTMENT_LAYOUT
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String apartmentLayout;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.ORIENTATION
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String orientation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.DECOR
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String decor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.DECOR_TIME
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String decorTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.FACILITIES
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String facilities;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.ELECTRIC
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String electric;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.FEATURE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String feature;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.ENVIRONMENT
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String environment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.REQUIREMENT
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String requirement;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.TITLE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.TEL
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String tel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.CONTACT
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String contact;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.OWNER_COST_ITEMS
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String ownerCostItems;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.OWNER_COST
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String ownerCost;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.FRESH_TIME
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private Date freshTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.TO_SPECIAL
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private Integer toSpecial;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.LONGITUDE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String longitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.LATITUDE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String latitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.STAGES
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String stages;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.DESCRIPTION
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_info.DCRP_TXT
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private String dcrpTxt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hou_lease_info
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.PINDEX
	 * @return  the value of hou_lease_info.PINDEX
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public Integer getPindex() {
		return pindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.PINDEX
	 * @param pindex  the value for hou_lease_info.PINDEX
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setPindex(Integer pindex) {
		this.pindex = pindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.LNO
	 * @return  the value of hou_lease_info.LNO
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getLno() {
		return lno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.LNO
	 * @param lno  the value for hou_lease_info.LNO
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setLno(String lno) {
		this.lno = lno == null ? null : lno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.PREFERENTIAL
	 * @return  the value of hou_lease_info.PREFERENTIAL
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getPreferential() {
		return preferential;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.PREFERENTIAL
	 * @param preferential  the value for hou_lease_info.PREFERENTIAL
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setPreferential(String preferential) {
		this.preferential = preferential == null ? null : preferential.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.ONLINE_PAYMENT
	 * @return  the value of hou_lease_info.ONLINE_PAYMENT
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getOnlinePayment() {
		return onlinePayment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.ONLINE_PAYMENT
	 * @param onlinePayment  the value for hou_lease_info.ONLINE_PAYMENT
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setOnlinePayment(String onlinePayment) {
		this.onlinePayment = onlinePayment == null ? null
				: onlinePayment.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.AUDIT_STATUS
	 * @return  the value of hou_lease_info.AUDIT_STATUS
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public Integer getAuditStatus() {
		return auditStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.AUDIT_STATUS
	 * @param auditStatus  the value for hou_lease_info.AUDIT_STATUS
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setAuditStatus(Integer auditStatus) {
		this.auditStatus = auditStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.LOCK_USERID
	 * @return  the value of hou_lease_info.LOCK_USERID
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getLockUserid() {
		return lockUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.LOCK_USERID
	 * @param lockUserid  the value for hou_lease_info.LOCK_USERID
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setLockUserid(String lockUserid) {
		this.lockUserid = lockUserid == null ? null : lockUserid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.LOCK_TIME
	 * @return  the value of hou_lease_info.LOCK_TIME
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public Date getLockTime() {
		return lockTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.LOCK_TIME
	 * @param lockTime  the value for hou_lease_info.LOCK_TIME
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setLockTime(Date lockTime) {
		this.lockTime = lockTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.RELEASE_TIME
	 * @return  the value of hou_lease_info.RELEASE_TIME
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public Date getReleaseTime() {
		return releaseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.RELEASE_TIME
	 * @param releaseTime  the value for hou_lease_info.RELEASE_TIME
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setReleaseTime(Date releaseTime) {
		this.releaseTime = releaseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.SOURCE_TYPE
	 * @return  the value of hou_lease_info.SOURCE_TYPE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public Integer getSourceType() {
		return sourceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.SOURCE_TYPE
	 * @param sourceType  the value for hou_lease_info.SOURCE_TYPE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setSourceType(Integer sourceType) {
		this.sourceType = sourceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.REJECT_TYPE
	 * @return  the value of hou_lease_info.REJECT_TYPE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public Integer getRejectType() {
		return rejectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.REJECT_TYPE
	 * @param rejectType  the value for hou_lease_info.REJECT_TYPE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setRejectType(Integer rejectType) {
		this.rejectType = rejectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.REJECT_REASON
	 * @return  the value of hou_lease_info.REJECT_REASON
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getRejectReason() {
		return rejectReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.REJECT_REASON
	 * @param rejectReason  the value for hou_lease_info.REJECT_REASON
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setRejectReason(String rejectReason) {
		this.rejectReason = rejectReason == null ? null : rejectReason.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.RELEASE_STATUS
	 * @return  the value of hou_lease_info.RELEASE_STATUS
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public Integer getReleaseStatus() {
		return releaseStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.RELEASE_STATUS
	 * @param releaseStatus  the value for hou_lease_info.RELEASE_STATUS
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setReleaseStatus(Integer releaseStatus) {
		this.releaseStatus = releaseStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.SHELF_TYPE
	 * @return  the value of hou_lease_info.SHELF_TYPE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public Integer getShelfType() {
		return shelfType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.SHELF_TYPE
	 * @param shelfType  the value for hou_lease_info.SHELF_TYPE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setShelfType(Integer shelfType) {
		this.shelfType = shelfType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.SHELF_REASON
	 * @return  the value of hou_lease_info.SHELF_REASON
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getShelfReason() {
		return shelfReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.SHELF_REASON
	 * @param shelfReason  the value for hou_lease_info.SHELF_REASON
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setShelfReason(String shelfReason) {
		this.shelfReason = shelfReason == null ? null : shelfReason.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.HID
	 * @return  the value of hou_lease_info.HID
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getHid() {
		return hid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.HID
	 * @param hid  the value for hou_lease_info.HID
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setHid(String hid) {
		this.hid = hid == null ? null : hid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.HOUSE_TYPE
	 * @return  the value of hou_lease_info.HOUSE_TYPE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public Integer getHouseType() {
		return houseType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.HOUSE_TYPE
	 * @param houseType  the value for hou_lease_info.HOUSE_TYPE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setHouseType(Integer houseType) {
		this.houseType = houseType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.STATIONID
	 * @return  the value of hou_lease_info.STATIONID
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getStationid() {
		return stationid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.STATIONID
	 * @param stationid  the value for hou_lease_info.STATIONID
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setStationid(String stationid) {
		this.stationid = stationid == null ? null : stationid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.CHECKIN_TIME
	 * @return  the value of hou_lease_info.CHECKIN_TIME
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public Date getCheckinTime() {
		return checkinTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.CHECKIN_TIME
	 * @param checkinTime  the value for hou_lease_info.CHECKIN_TIME
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setCheckinTime(Date checkinTime) {
		this.checkinTime = checkinTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.RENT_TYPE
	 * @return  the value of hou_lease_info.RENT_TYPE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getRentType() {
		return rentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.RENT_TYPE
	 * @param rentType  the value for hou_lease_info.RENT_TYPE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setRentType(String rentType) {
		this.rentType = rentType == null ? null : rentType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.LEASE_MODE
	 * @return  the value of hou_lease_info.LEASE_MODE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public Integer getLeaseMode() {
		return leaseMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.LEASE_MODE
	 * @param leaseMode  the value for hou_lease_info.LEASE_MODE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setLeaseMode(Integer leaseMode) {
		this.leaseMode = leaseMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.RENT
	 * @return  the value of hou_lease_info.RENT
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public BigDecimal getRent() {
		return rent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.RENT
	 * @param rent  the value for hou_lease_info.RENT
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setRent(BigDecimal rent) {
		this.rent = rent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.VILLAGE_NAME
	 * @return  the value of hou_lease_info.VILLAGE_NAME
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getVillageName() {
		return villageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.VILLAGE_NAME
	 * @param villageName  the value for hou_lease_info.VILLAGE_NAME
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setVillageName(String villageName) {
		this.villageName = villageName == null ? null : villageName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.DISTRICT
	 * @return  the value of hou_lease_info.DISTRICT
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getDistrict() {
		return district;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.DISTRICT
	 * @param district  the value for hou_lease_info.DISTRICT
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setDistrict(String district) {
		this.district = district == null ? null : district.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.DISTRICT_NAME
	 * @return  the value of hou_lease_info.DISTRICT_NAME
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getDistrictName() {
		return districtName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.DISTRICT_NAME
	 * @param districtName  the value for hou_lease_info.DISTRICT_NAME
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setDistrictName(String districtName) {
		this.districtName = districtName == null ? null : districtName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.NO
	 * @return  the value of hou_lease_info.NO
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getNo() {
		return no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.NO
	 * @param no  the value for hou_lease_info.NO
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setNo(String no) {
		this.no = no == null ? null : no.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.FLOOR
	 * @return  the value of hou_lease_info.FLOOR
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getFloor() {
		return floor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.FLOOR
	 * @param floor  the value for hou_lease_info.FLOOR
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setFloor(String floor) {
		this.floor = floor == null ? null : floor.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.BUILD_TIME
	 * @return  the value of hou_lease_info.BUILD_TIME
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getBuildTime() {
		return buildTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.BUILD_TIME
	 * @param buildTime  the value for hou_lease_info.BUILD_TIME
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setBuildTime(String buildTime) {
		this.buildTime = buildTime == null ? null : buildTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.APARTMENT_LAYOUT
	 * @return  the value of hou_lease_info.APARTMENT_LAYOUT
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getApartmentLayout() {
		return apartmentLayout;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.APARTMENT_LAYOUT
	 * @param apartmentLayout  the value for hou_lease_info.APARTMENT_LAYOUT
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setApartmentLayout(String apartmentLayout) {
		this.apartmentLayout = apartmentLayout == null ? null
				: apartmentLayout.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.ORIENTATION
	 * @return  the value of hou_lease_info.ORIENTATION
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getOrientation() {
		return orientation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.ORIENTATION
	 * @param orientation  the value for hou_lease_info.ORIENTATION
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setOrientation(String orientation) {
		this.orientation = orientation == null ? null : orientation.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.DECOR
	 * @return  the value of hou_lease_info.DECOR
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getDecor() {
		return decor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.DECOR
	 * @param decor  the value for hou_lease_info.DECOR
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setDecor(String decor) {
		this.decor = decor == null ? null : decor.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.DECOR_TIME
	 * @return  the value of hou_lease_info.DECOR_TIME
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getDecorTime() {
		return decorTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.DECOR_TIME
	 * @param decorTime  the value for hou_lease_info.DECOR_TIME
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setDecorTime(String decorTime) {
		this.decorTime = decorTime == null ? null : decorTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.FACILITIES
	 * @param facilities  the value for hou_lease_info.FACILITIES
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setFacilities(String facilities) {
		this.facilities = facilities == null ? null : facilities.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.ELECTRIC
	 * @param electric  the value for hou_lease_info.ELECTRIC
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setElectric(String electric) {
		this.electric = electric == null ? null : electric.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.FEATURE
	 * @param feature  the value for hou_lease_info.FEATURE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setFeature(String feature) {
		this.feature = feature == null ? null : feature.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.ENVIRONMENT
	 * @param environment  the value for hou_lease_info.ENVIRONMENT
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setEnvironment(String environment) {
		this.environment = environment == null ? null : environment.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.REQUIREMENT
	 * @param requirement  the value for hou_lease_info.REQUIREMENT
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setRequirement(String requirement) {
		this.requirement = requirement == null ? null : requirement.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.TITLE
	 * @return  the value of hou_lease_info.TITLE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.TITLE
	 * @param title  the value for hou_lease_info.TITLE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.TEL
	 * @return  the value of hou_lease_info.TEL
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.TEL
	 * @param tel  the value for hou_lease_info.TEL
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setTel(String tel) {
		this.tel = tel == null ? null : tel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.CONTACT
	 * @return  the value of hou_lease_info.CONTACT
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getContact() {
		return contact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.CONTACT
	 * @param contact  the value for hou_lease_info.CONTACT
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setContact(String contact) {
		this.contact = contact == null ? null : contact.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.OWNER_COST_ITEMS
	 * @return  the value of hou_lease_info.OWNER_COST_ITEMS
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getOwnerCostItems() {
		return ownerCostItems;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.OWNER_COST_ITEMS
	 * @param ownerCostItems  the value for hou_lease_info.OWNER_COST_ITEMS
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setOwnerCostItems(String ownerCostItems) {
		this.ownerCostItems = ownerCostItems == null ? null
				: ownerCostItems.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.OWNER_COST
	 * @return  the value of hou_lease_info.OWNER_COST
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getOwnerCost() {
		return ownerCost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.OWNER_COST
	 * @param ownerCost  the value for hou_lease_info.OWNER_COST
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setOwnerCost(String ownerCost) {
		this.ownerCost = ownerCost == null ? null : ownerCost.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.FRESH_TIME
	 * @return  the value of hou_lease_info.FRESH_TIME
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public Date getFreshTime() {
		return freshTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.FRESH_TIME
	 * @param freshTime  the value for hou_lease_info.FRESH_TIME
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setFreshTime(Date freshTime) {
		this.freshTime = freshTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.TO_SPECIAL
	 * @return  the value of hou_lease_info.TO_SPECIAL
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public Integer getToSpecial() {
		return toSpecial;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.TO_SPECIAL
	 * @param toSpecial  the value for hou_lease_info.TO_SPECIAL
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setToSpecial(Integer toSpecial) {
		this.toSpecial = toSpecial;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.LONGITUDE
	 * @return  the value of hou_lease_info.LONGITUDE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getLongitude() {
		return longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.LONGITUDE
	 * @param longitude  the value for hou_lease_info.LONGITUDE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setLongitude(String longitude) {
		this.longitude = longitude == null ? null : longitude.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.LATITUDE
	 * @return  the value of hou_lease_info.LATITUDE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getLatitude() {
		return latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.LATITUDE
	 * @param latitude  the value for hou_lease_info.LATITUDE
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setLatitude(String latitude) {
		this.latitude = latitude == null ? null : latitude.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.STAGES
	 * @return  the value of hou_lease_info.STAGES
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getStages() {
		return stages;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.STAGES
	 * @param stages  the value for hou_lease_info.STAGES
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setStages(String stages) {
		this.stages = stages == null ? null : stages.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.DESCRIPTION
	 * @return  the value of hou_lease_info.DESCRIPTION
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.DESCRIPTION
	 * @param description  the value for hou_lease_info.DESCRIPTION
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_info.DCRP_TXT
	 * @return  the value of hou_lease_info.DCRP_TXT
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public String getDcrpTxt() {
		return dcrpTxt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_info.DCRP_TXT
	 * @param dcrpTxt  the value for hou_lease_info.DCRP_TXT
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	public void setDcrpTxt(String dcrpTxt) {
		this.dcrpTxt = dcrpTxt == null ? null : dcrpTxt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_lease_info
	 * @mbggenerated  Tue Jan 03 11:37:53 CST 2017
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", pindex=").append(pindex);
		sb.append(", lno=").append(lno);
		sb.append(", preferential=").append(preferential);
		sb.append(", onlinePayment=").append(onlinePayment);
		sb.append(", auditStatus=").append(auditStatus);
		sb.append(", lockUserid=").append(lockUserid);
		sb.append(", lockTime=").append(lockTime);
		sb.append(", releaseTime=").append(releaseTime);
		sb.append(", sourceType=").append(sourceType);
		sb.append(", rejectType=").append(rejectType);
		sb.append(", rejectReason=").append(rejectReason);
		sb.append(", releaseStatus=").append(releaseStatus);
		sb.append(", shelfType=").append(shelfType);
		sb.append(", shelfReason=").append(shelfReason);
		sb.append(", hid=").append(hid);
		sb.append(", houseType=").append(houseType);
		sb.append(", stationid=").append(stationid);
		sb.append(", checkinTime=").append(checkinTime);
		sb.append(", rentType=").append(rentType);
		sb.append(", leaseMode=").append(leaseMode);
		sb.append(", rent=").append(rent);
		sb.append(", villageName=").append(villageName);
		sb.append(", district=").append(district);
		sb.append(", districtName=").append(districtName);
		sb.append(", no=").append(no);
		sb.append(", floor=").append(floor);
		sb.append(", buildTime=").append(buildTime);
		sb.append(", apartmentLayout=").append(apartmentLayout);
		sb.append(", orientation=").append(orientation);
		sb.append(", decor=").append(decor);
		sb.append(", decorTime=").append(decorTime);
		sb.append(", facilities=").append(facilities);
		sb.append(", electric=").append(electric);
		sb.append(", feature=").append(feature);
		sb.append(", environment=").append(environment);
		sb.append(", requirement=").append(requirement);
		sb.append(", title=").append(title);
		sb.append(", tel=").append(tel);
		sb.append(", contact=").append(contact);
		sb.append(", ownerCostItems=").append(ownerCostItems);
		sb.append(", ownerCost=").append(ownerCost);
		sb.append(", freshTime=").append(freshTime);
		sb.append(", toSpecial=").append(toSpecial);
		sb.append(", longitude=").append(longitude);
		sb.append(", latitude=").append(latitude);
		sb.append(", stages=").append(stages);
		sb.append(", description=").append(description);
		sb.append(", dcrpTxt=").append(dcrpTxt);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	public String getFacilities() {
		if (facilitiesArr != null && facilitiesArr.length > 0) {
			facilities = facilitiesArr[0];
			for (int i = 1; i < facilitiesArr.length; i++) {
				facilities = facilities + "," + facilitiesArr[i];
			}
		}
		return facilities;
	}

	public String getElectric() {
		if (electricArr != null && electricArr.length > 0) {
			electric = electricArr[0];
			for (int i = 1; i < electricArr.length; i++) {
				electric = electric + "," + electricArr[i];
			}
		}
		return electric;
	}

	public String getFeature() {
		if (featureArr != null && featureArr.length > 0) {
			feature = featureArr[0];
			for (int i = 1; i < featureArr.length; i++) {
				feature = feature + "," + featureArr[i];
			}
		}
		return feature;
	}

	public String getEnvironment() {
		if (environmentArr != null && environmentArr.length > 0) {
			environment = environmentArr[0];
			for (int i = 1; i < environmentArr.length; i++) {
				environment = environment + "," + environmentArr[i];
			}
		}
		return environment;
	}

	public String getRequirement() {
		if (requirementArr != null && requirementArr.length > 0) {
			requirement = requirementArr[0];
			for (int i = 1; i < requirementArr.length; i++) {
				requirement = requirement + "," + requirementArr[i];
			}
		}
		return requirement;
	}

	private String noBuildingNo;//楼号
	private String noUnit;
	private String noRoom;//楼号
	
	private String floorNo;//楼层
	private String floorNum;
	
	private String aparmentRoom;//户型
	private String aparmentHall;
	private String aparmentToilet;
	
	private String districtArea;
	private String districtDist;
	
	private String districtAreaName;
	private String districtDistName;
	
	private String[] facilitiesArr;
	private String[] electricArr;
	private String[] featureArr;
	private String[] environmentArr;
	private String[] requirementArr;
	private String[] ownerCostItemsArr;//房主承担费用
	
	private String rentDeposit;//�?
	private String rentPayment;//�?
	private String inputValue;
	
	private String pay1;
	private String pay2;
	/** 房源审核 */
	private String houseAuditStatus;
	
	public String getPay1() {
		return pay1;
	}

	public void setPay1(String pay1) {
		this.pay1 = pay1;
	}

	public String getPay2() {
		return pay2;
	}

	public void setPay2(String pay2) {
		this.pay2 = pay2;
	}

	public String getRentDeposit() {
		if (rentType != null) {
			rentDeposit = rentType.split(",")[0];
		}
		return rentDeposit;
	}

	public void setRentDeposit(String rentDeposit) {
		this.rentDeposit = rentDeposit;
	}

	public String getRentPayment() {
		if (rentType != null) {
			rentPayment = rentType.split(",")[1];
		}
		return rentPayment;
	}

	public void setRentPayment(String rentPayment) {
		this.rentPayment = rentPayment;
	}

	public String[] getOwnerCostItemsArr() {
		if (ownerCostItems != null) {
			ownerCostItemsArr = ownerCostItems.split(",");
		}
		return ownerCostItemsArr;
	}

	public void setOwnerCostItemsArr(String[] ownerCostItemsArr) {
		this.ownerCostItemsArr = ownerCostItemsArr;
	}

	private Integer startRent;
	private Integer endRent;
	
	private String content;//用于head筛�?
	
	private String certStatus;//房源认证标识
	
	private String collectFlg;//推荐标识
	
	private String eid;//经纪人ID
	
	public String getEid() {
		return eid;
	}

	public void setEid(String eid) {
		this.eid = eid;
	}

	public String getCollectFlg() {
		return collectFlg;
	}

	public void setCollectFlg(String collectFlg) {
		this.collectFlg = collectFlg;
	}

	public String getCertStatus() {
		return certStatus;
	}

	public void setCertStatus(String certStatus) {
		this.certStatus = certStatus;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getStartRent() {
		return startRent;
	}

	public void setStartRent(Integer startRent) {
		this.startRent = startRent;
	}

	public Integer getEndRent() {
		return endRent;
	}

	public void setEndRent(Integer endRent) {
		this.endRent = endRent;
	}

	public String getNoBuildingNo() {
		if (no != null) {
			try {
				noBuildingNo = no.split(",")[0];
			} catch (Exception e) {

			}
		}
		return noBuildingNo;
	}

	public void setNoBuildingNo(String noBuildingNo) {
		this.noBuildingNo = noBuildingNo;
	}

	public String getNoUnit() {
		if (no != null) {
			try {
				noUnit = no.split(",")[1];
			} catch (Exception e) {
			}
		}
		return noUnit;
	}

	public void setNoUnit(String noUnit) {
		this.noUnit = noUnit;
	}

	public String getNoRoom() {
		if (no != null) {
			try {
				noRoom = no.split(",")[2];
			} catch (Exception e) {
			}
		}
		return noRoom;
	}

	public void setNoRoom(String noRoom) {
		this.noRoom = noRoom;
	}

	public String getFloorNo() {
		if (floor != null) {
			try {
				floorNo = floor.split(",")[0];
			} catch (Exception e) {

			}
		}
		return floorNo;
	}

	public void setFloorNo(String floorNo) {
		this.floorNo = floorNo;
	}

	public String getFloorNum() {
		if (floor != null) {
			try {
				floorNum = floor.split(",")[1];
			} catch (Exception e) {

			}
		}
		return floorNum;
	}

	public void setFloorNum(String floorNum) {
		this.floorNum = floorNum;
	}

	public String getAparmentRoom() {
		if (apartmentLayout != null) {
			aparmentRoom = apartmentLayout.split(",")[0];
		}
		return aparmentRoom;
	}

	public void setAparmentRoom(String aparmentRoom) {
		this.aparmentRoom = aparmentRoom;
	}

	public String getAparmentHall() {
		if (apartmentLayout != null) {
			aparmentHall = apartmentLayout.split(",")[1];
		}
		return aparmentHall;
	}

	public void setAparmentHall(String aparmentHall) {
		this.aparmentHall = aparmentHall;
	}

	public String getAparmentToilet() {
		if (apartmentLayout != null) {
			aparmentToilet = apartmentLayout.split(",")[2];
		}
		return aparmentToilet;
	}

	public void setAparmentToilet(String aparmentToilet) {
		this.aparmentToilet = aparmentToilet;
	}

	public String getDistrictArea() {
		if (district != null) {
			districtArea = district.split(",")[0];
		}
		return districtArea;
	}

	public void setDistrictArea(String districtArea) {
		this.districtArea = districtArea;
	}

	public String getDistrictDist() {
		if (district != null) {
			districtDist = district.split(",")[1];
		}
		return districtDist;
	}

	public void setDistrictDist(String districtDist) {
		this.districtDist = districtDist;
	}
	
	public String[] getFacilitiesArr() {
		if (facilities != null) {
			facilitiesArr = facilities.split(",");
		}
		return facilitiesArr;
	}

	public void setFacilitiesArr(String[] facilitiesArr) {
		this.facilitiesArr = facilitiesArr;
	}

	public String[] getElectricArr() {
		if (electric != null) {
			electricArr = electric.split(",");
		}
		return electricArr;
	}

	public void setElectricArr(String[] electricArr) {
		this.electricArr = electricArr;
	}

	public String[] getFeatureArr() {
		if (feature != null) {
			featureArr = feature.split(",");
		}
		return featureArr;
	}

	public void setFeatureArr(String[] featureArr) {
		this.featureArr = featureArr;
	}

	public String[] getEnvironmentArr() {
		if (environment != null) {
			environmentArr = environment.split(",");
		}
		return environmentArr;
	}

	public void setEnvironmentArr(String[] environmentArr) {
		this.environmentArr = environmentArr;
	}

	public String[] getRequirementArr() {
		if (requirement != null) {
			requirementArr = requirement.split(",");
		}
		return requirementArr;
	}

	public void setRequirementArr(String[] requirementArr) {
		this.requirementArr = requirementArr;
	}
	
	
	private String leaseModeName;

	public String getLeaseModeName() {
		return leaseModeName;
	}

	public void setLeaseModeName(String leaseModeName) {
		this.leaseModeName = leaseModeName;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	
	private String decorName;

	public String getDecorName() {
		return decorName;
	}

	public void setDecorName(String decorName) {
		this.decorName = decorName;
	}

	public String getDistrictAreaName() {
		return districtAreaName;
	}

	public void setDistrictAreaName(String districtAreaName) {
		this.districtAreaName = districtAreaName;
	}

	public String getDistrictDistName() {
		return districtDistName;
	}

	public void setDistrictDistName(String districtDistName) {
		this.districtDistName = districtDistName;
	}
	
	private List<HouHouseInfoAtt> houHouseInfoAtt;

	public List<HouHouseInfoAtt> getHouHouseInfoAtt() {
		return houHouseInfoAtt;
	}

	public void setHouHouseInfoAtt(List<HouHouseInfoAtt> houHouseInfoAtt) {
		this.houHouseInfoAtt = houHouseInfoAtt;
	}
	
	private List<HouLeaseRoomInfo> houLeaseRoomInfo;
	
	private String rentalModeName;
	private List<SysInfoAtt> sysInfoAtt;
	private String isCollect;//是否已经收藏过该房源
	private String collectCount;//房源收藏�?
	
	public String getIsCollect() {
		return isCollect;
	}

	public void setIsCollect(String isCollect) {
		this.isCollect = isCollect;
	}

	public String getCollectCount() {
		return collectCount;
	}

	public void setCollectCount(String collectCount) {
		this.collectCount = collectCount;
	}

	public List<HouLeaseRoomInfo> getHouLeaseRoomInfo() {
		return houLeaseRoomInfo;
	}

	public void setHouLeaseRoomInfo(List<HouLeaseRoomInfo> houLeaseRoomInfo) {
		this.houLeaseRoomInfo = houLeaseRoomInfo;
	}

	public List<SysInfoAtt> getSysInfoAtt() {
		return sysInfoAtt;
	}

	public void setSysInfoAtt(List<SysInfoAtt> sysInfoAtt) {
		this.sysInfoAtt = sysInfoAtt;
	}

	public String getRentalModeName() {
		return rentalModeName;
	}

	public void setRentalModeName(String rentalModeName) {
		this.rentalModeName = rentalModeName;
	}
	
	private String buildingArea;//面积
	private String area;//商圈
	private String uid;//房主用户ID
	@SuppressWarnings("unused")
	private Integer rentInt;//租金，用于显�?
	
	private String lines;//线路-地铁找房
	private String line;//线路-地铁找房
	private String station;//站名-地铁找房
	/** 房源地址 */
	private String houseAddr;
	/** 前台高低中层显示 */
	private String layer;
	
	public String getLines() {
		return lines;
	}

	public void setLines(String lines) {
		this.lines = lines;
	}

	public String getLine() {
		return line;
	}

	public void setLine(String line) {
		this.line = line;
	}

	public String getStation() {
		return station;
	}

	public void setStation(String station) {
		this.station = station;
	}

	public Integer getRentInt() {
		if (rent != null) {
			return rent.intValue();
		}
		return 0;
	}

	public void setRentInt(Integer rentInt) {
		this.rentInt = rentInt;
	}

	public String getUid() {
		return uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getBuildingArea() {
		return buildingArea;
	}

	public void setBuildingArea(String buildingArea) {
		this.buildingArea = buildingArea;
	}

	public String getInputValue() {
		return inputValue;
	}

	public void setInputValue(String inputValue) {
		this.inputValue = inputValue;
	}

	/**
	 * @return the 房源地址
	 */
	public String getHouseAddr() {
		return houseAddr;
	}

	/**
	 * @param 房源地址 the houseAddr to set
	 */
	public void setHouseAddr(String houseAddr) {
		this.houseAddr = houseAddr;
	}

	/**
	 * @return the 房源审核
	 */
	public String getHouseAuditStatus() {
		return houseAuditStatus;
	}
	

	/**
	 * @param 房源审核 the houseAuditStatus to set
	 */
	public void setHouseAuditStatus(String houseAuditStatus) {
		this.houseAuditStatus = houseAuditStatus;
	}

	/**
	 * @return the 前台高低中层显示
	 */
	public String getLayer() {
		return layer;
	}
	

	/**
	 * @param 前台高低中层显示 the layer to set
	 */
	public void setLayer(String layer) {
		this.layer = layer;
	}
	
	private String activeStatus; //无效状�?
	private String lockStatus; //锁定状�?

	public String getActiveStatus() {
		return activeStatus;
	}

	public void setActiveStatus(String activeStatus) {
		this.activeStatus = activeStatus;
	}

	public String getLockStatus() {
		return lockStatus;
	}

	public void setLockStatus(String lockStatus) {
		this.lockStatus = lockStatus;
	}
	
	private int certFlag;//认证状�?

	public int getCertFlag() {
		return certFlag;
	}

	public void setCertFlag(int certFlag) {
		this.certFlag = certFlag;
	}
	
}