package com.dlfc.zfgj.entity;

import com.dlfc.admin.common.persistence.MyDataEntity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class HouLeaseRoomInfo extends MyDataEntity<HouLeaseRoomInfo> implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_room_info.PINDEX
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	private Integer pindex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_room_info.STATUS
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_room_info.LEASEID
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	private String leaseid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_room_info.ROOM
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	private String room;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_room_info.RENT
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	private BigDecimal rent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_room_info.RENT_TYPE
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	private String rentType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_room_info.CHECKIN_TIME
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	private Date checkinTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_room_info.AREA
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	private String area;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_room_info.FEATURE
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	private String feature;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_room_info.DESCRIPTION
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hou_lease_room_info.DCRP_TXT
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	private String dcrpTxt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hou_lease_room_info
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_room_info.PINDEX
	 * @return  the value of hou_lease_room_info.PINDEX
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	public Integer getPindex() {
		return pindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_room_info.PINDEX
	 * @param pindex  the value for hou_lease_room_info.PINDEX
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	public void setPindex(Integer pindex) {
		this.pindex = pindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_room_info.STATUS
	 * @return  the value of hou_lease_room_info.STATUS
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_room_info.STATUS
	 * @param status  the value for hou_lease_room_info.STATUS
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_room_info.LEASEID
	 * @return  the value of hou_lease_room_info.LEASEID
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	public String getLeaseid() {
		return leaseid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_room_info.LEASEID
	 * @param leaseid  the value for hou_lease_room_info.LEASEID
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	public void setLeaseid(String leaseid) {
		this.leaseid = leaseid == null ? null : leaseid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_room_info.ROOM
	 * @return  the value of hou_lease_room_info.ROOM
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	public String getRoom() {
		return room;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_room_info.ROOM
	 * @param room  the value for hou_lease_room_info.ROOM
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	public void setRoom(String room) {
		this.room = room == null ? null : room.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_room_info.RENT
	 * @return  the value of hou_lease_room_info.RENT
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	public BigDecimal getRent() {
		return rent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_room_info.RENT
	 * @param rent  the value for hou_lease_room_info.RENT
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	public void setRent(BigDecimal rent) {
		this.rent = rent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_room_info.RENT_TYPE
	 * @return  the value of hou_lease_room_info.RENT_TYPE
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	public String getRentType() {
		return rentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_room_info.RENT_TYPE
	 * @param rentType  the value for hou_lease_room_info.RENT_TYPE
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	public void setRentType(String rentType) {
		this.rentType = rentType == null ? null : rentType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_room_info.CHECKIN_TIME
	 * @return  the value of hou_lease_room_info.CHECKIN_TIME
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	public Date getCheckinTime() {
		return checkinTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_room_info.CHECKIN_TIME
	 * @param checkinTime  the value for hou_lease_room_info.CHECKIN_TIME
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	public void setCheckinTime(Date checkinTime) {
		this.checkinTime = checkinTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_room_info.AREA
	 * @return  the value of hou_lease_room_info.AREA
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	public String getArea() {
		return area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_room_info.AREA
	 * @param area  the value for hou_lease_room_info.AREA
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	public void setArea(String area) {
		this.area = area == null ? null : area.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_room_info.FEATURE
	 * @return  the value of hou_lease_room_info.FEATURE
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	public String getFeature() {
		return feature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_room_info.FEATURE
	 * @param feature  the value for hou_lease_room_info.FEATURE
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	public void setFeature(String feature) {
		this.feature = feature == null ? null : feature.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_room_info.DESCRIPTION
	 * @return  the value of hou_lease_room_info.DESCRIPTION
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_room_info.DESCRIPTION
	 * @param description  the value for hou_lease_room_info.DESCRIPTION
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hou_lease_room_info.DCRP_TXT
	 * @return  the value of hou_lease_room_info.DCRP_TXT
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	public String getDcrpTxt() {
		return dcrpTxt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hou_lease_room_info.DCRP_TXT
	 * @param dcrpTxt  the value for hou_lease_room_info.DCRP_TXT
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	public void setDcrpTxt(String dcrpTxt) {
		this.dcrpTxt = dcrpTxt == null ? null : dcrpTxt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hou_lease_room_info
	 * @mbggenerated  Thu Nov 03 16:47:17 CST 2016
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", pindex=").append(pindex);
		sb.append(", status=").append(status);
		sb.append(", leaseid=").append(leaseid);
		sb.append(", room=").append(room);
		sb.append(", rent=").append(rent);
		sb.append(", rentType=").append(rentType);
		sb.append(", checkinTime=").append(checkinTime);
		sb.append(", area=").append(area);
		sb.append(", feature=").append(feature);
		sb.append(", description=").append(description);
		sb.append(", dcrpTxt=").append(dcrpTxt);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	private String id;
	private List<SysInfoAtt> atts;
	private String rentDeposit;//�?
	private String rentPayment;//�?
	
	public String getRentDeposit() {
		if (rentType != null) {
			rentDeposit = rentType.split(",")[0];
		}
		return rentDeposit;
	}

	public void setRentDeposit(String rentDeposit) {
		this.rentDeposit = rentDeposit;
	}

	public String getRentPayment() {
		if (rentType != null) {
			rentPayment = rentType.split(",")[1];
		}
		return rentPayment;
	}

	public void setRentPayment(String rentPayment) {
		this.rentPayment = rentPayment;
	}
	
	public List<SysInfoAtt> getAtts() {
		return atts;
	}

	public void setAtts(List<SysInfoAtt> atts) {
		this.atts = atts;
	}
	

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
}