package com.dlfc.zfgj.entity;

import com.dlfc.admin.common.persistence.MyDataEntity;

import java.io.Serializable;
import java.util.Date;

public class SssResultInfo extends MyDataEntity<SssResultInfo> implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sss_result_info.PINDEX
	 *
	 * @mbggenerated Tue Oct 25 16:40:15 CST 2016
	 */
	private Integer pindex;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sss_result_info.UID
	 *
	 * @mbggenerated Tue Oct 25 16:40:15 CST 2016
	 */
	private String uid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sss_result_info.UNAME
	 *
	 * @mbggenerated Tue Oct 25 16:40:15 CST 2016
	 */
	private String uname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sss_result_info.WID
	 *
	 * @mbggenerated Tue Oct 25 16:40:15 CST 2016
	 */
	private String wid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sss_result_info.DETAIL_INFO
	 *
	 * @mbggenerated Tue Oct 25 16:40:15 CST 2016
	 */
	private String detailInfo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sss_result_info.WDATETIME
	 *
	 * @mbggenerated Tue Oct 25 16:40:15 CST 2016
	 */
	private Date wdatetime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table sss_result_info
	 *
	 * @mbggenerated Tue Oct 25 16:40:15 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sss_result_info.PINDEX
	 *
	 * @return the value of sss_result_info.PINDEX
	 *
	 * @mbggenerated Tue Oct 25 16:40:15 CST 2016
	 */
	public Integer getPindex() {
		return pindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sss_result_info.PINDEX
	 *
	 * @param pindex
	 *            the value for sss_result_info.PINDEX
	 *
	 * @mbggenerated Tue Oct 25 16:40:15 CST 2016
	 */
	public void setPindex(Integer pindex) {
		this.pindex = pindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sss_result_info.UID
	 *
	 * @return the value of sss_result_info.UID
	 *
	 * @mbggenerated Tue Oct 25 16:40:15 CST 2016
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sss_result_info.UID
	 *
	 * @param uid
	 *            the value for sss_result_info.UID
	 *
	 * @mbggenerated Tue Oct 25 16:40:15 CST 2016
	 */
	public void setUid(String uid) {
		this.uid = uid == null ? null : uid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sss_result_info.UNAME
	 *
	 * @return the value of sss_result_info.UNAME
	 *
	 * @mbggenerated Tue Oct 25 16:40:15 CST 2016
	 */
	public String getUname() {
		return uname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sss_result_info.UNAME
	 *
	 * @param uname
	 *            the value for sss_result_info.UNAME
	 *
	 * @mbggenerated Tue Oct 25 16:40:15 CST 2016
	 */
	public void setUname(String uname) {
		this.uname = uname == null ? null : uname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sss_result_info.WID
	 *
	 * @return the value of sss_result_info.WID
	 *
	 * @mbggenerated Tue Oct 25 16:40:15 CST 2016
	 */
	public String getWid() {
		return wid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sss_result_info.WID
	 *
	 * @param wid
	 *            the value for sss_result_info.WID
	 *
	 * @mbggenerated Tue Oct 25 16:40:15 CST 2016
	 */
	public void setWid(String wid) {
		this.wid = wid == null ? null : wid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sss_result_info.DETAIL_INFO
	 *
	 * @return the value of sss_result_info.DETAIL_INFO
	 *
	 * @mbggenerated Tue Oct 25 16:40:15 CST 2016
	 */
	public String getDetailInfo() {
		return detailInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sss_result_info.DETAIL_INFO
	 *
	 * @param detailInfo
	 *            the value for sss_result_info.DETAIL_INFO
	 *
	 * @mbggenerated Tue Oct 25 16:40:15 CST 2016
	 */
	public void setDetailInfo(String detailInfo) {
		this.detailInfo = detailInfo == null ? null : detailInfo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sss_result_info.WDATETIME
	 *
	 * @return the value of sss_result_info.WDATETIME
	 *
	 * @mbggenerated Tue Oct 25 16:40:15 CST 2016
	 */
	public Date getWdatetime() {
		return wdatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sss_result_info.WDATETIME
	 *
	 * @param wdatetime
	 *            the value for sss_result_info.WDATETIME
	 *
	 * @mbggenerated Tue Oct 25 16:40:15 CST 2016
	 */
	public void setWdatetime(Date wdatetime) {
		this.wdatetime = wdatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sss_result_info
	 *
	 * @mbggenerated Tue Oct 25 16:40:15 CST 2016
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", pindex=").append(pindex);
		sb.append(", uid=").append(uid);
		sb.append(", uname=").append(uname);
		sb.append(", wid=").append(wid);
		sb.append(", detailInfo=").append(detailInfo);
		sb.append(", wdatetime=").append(wdatetime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * 奖品对象
	 */
	private SssPrizeInfo sssPrizeInfo;

	public SssPrizeInfo getSssPrizeInfo() {
		return sssPrizeInfo;
	}

	public void setSssPrizeInfo(SssPrizeInfo sssPrizeInfo) {
		this.sssPrizeInfo = sssPrizeInfo;
	}
}