package com.dlfc.zfgj.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysInsuranceExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_insurance
	 * @mbggenerated  Wed Sep 14 09:27:26 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_insurance
	 * @mbggenerated  Wed Sep 14 09:27:26 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_insurance
	 * @mbggenerated  Wed Sep 14 09:27:26 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_insurance
	 * @mbggenerated  Wed Sep 14 09:27:26 CST 2016
	 */
	public SysInsuranceExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_insurance
	 * @mbggenerated  Wed Sep 14 09:27:26 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_insurance
	 * @mbggenerated  Wed Sep 14 09:27:26 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_insurance
	 * @mbggenerated  Wed Sep 14 09:27:26 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_insurance
	 * @mbggenerated  Wed Sep 14 09:27:26 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_insurance
	 * @mbggenerated  Wed Sep 14 09:27:26 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_insurance
	 * @mbggenerated  Wed Sep 14 09:27:26 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_insurance
	 * @mbggenerated  Wed Sep 14 09:27:26 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_insurance
	 * @mbggenerated  Wed Sep 14 09:27:26 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_insurance
	 * @mbggenerated  Wed Sep 14 09:27:26 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_insurance
	 * @mbggenerated  Wed Sep 14 09:27:26 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_insurance
	 * @mbggenerated  Wed Sep 14 09:27:26 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andPindexIsNull() {
			addCriterion("PINDEX is null");
			return (Criteria) this;
		}

		public Criteria andPindexIsNotNull() {
			addCriterion("PINDEX is not null");
			return (Criteria) this;
		}

		public Criteria andPindexEqualTo(Integer value) {
			addCriterion("PINDEX =", value, "pindex");
			return (Criteria) this;
		}

		public Criteria andPindexNotEqualTo(Integer value) {
			addCriterion("PINDEX <>", value, "pindex");
			return (Criteria) this;
		}

		public Criteria andPindexGreaterThan(Integer value) {
			addCriterion("PINDEX >", value, "pindex");
			return (Criteria) this;
		}

		public Criteria andPindexGreaterThanOrEqualTo(Integer value) {
			addCriterion("PINDEX >=", value, "pindex");
			return (Criteria) this;
		}

		public Criteria andPindexLessThan(Integer value) {
			addCriterion("PINDEX <", value, "pindex");
			return (Criteria) this;
		}

		public Criteria andPindexLessThanOrEqualTo(Integer value) {
			addCriterion("PINDEX <=", value, "pindex");
			return (Criteria) this;
		}

		public Criteria andPindexIn(List<Integer> values) {
			addCriterion("PINDEX in", values, "pindex");
			return (Criteria) this;
		}

		public Criteria andPindexNotIn(List<Integer> values) {
			addCriterion("PINDEX not in", values, "pindex");
			return (Criteria) this;
		}

		public Criteria andPindexBetween(Integer value1, Integer value2) {
			addCriterion("PINDEX between", value1, value2, "pindex");
			return (Criteria) this;
		}

		public Criteria andPindexNotBetween(Integer value1, Integer value2) {
			addCriterion("PINDEX not between", value1, value2, "pindex");
			return (Criteria) this;
		}

		public Criteria andCidIsNull() {
			addCriterion("CID is null");
			return (Criteria) this;
		}

		public Criteria andCidIsNotNull() {
			addCriterion("CID is not null");
			return (Criteria) this;
		}

		public Criteria andCidEqualTo(String value) {
			addCriterion("CID =", value, "cid");
			return (Criteria) this;
		}

		public Criteria andCidNotEqualTo(String value) {
			addCriterion("CID <>", value, "cid");
			return (Criteria) this;
		}

		public Criteria andCidGreaterThan(String value) {
			addCriterion("CID >", value, "cid");
			return (Criteria) this;
		}

		public Criteria andCidGreaterThanOrEqualTo(String value) {
			addCriterion("CID >=", value, "cid");
			return (Criteria) this;
		}

		public Criteria andCidLessThan(String value) {
			addCriterion("CID <", value, "cid");
			return (Criteria) this;
		}

		public Criteria andCidLessThanOrEqualTo(String value) {
			addCriterion("CID <=", value, "cid");
			return (Criteria) this;
		}

		public Criteria andCidLike(String value) {
			addCriterion("CID like", value, "cid");
			return (Criteria) this;
		}

		public Criteria andCidNotLike(String value) {
			addCriterion("CID not like", value, "cid");
			return (Criteria) this;
		}

		public Criteria andCidIn(List<String> values) {
			addCriterion("CID in", values, "cid");
			return (Criteria) this;
		}

		public Criteria andCidNotIn(List<String> values) {
			addCriterion("CID not in", values, "cid");
			return (Criteria) this;
		}

		public Criteria andCidBetween(String value1, String value2) {
			addCriterion("CID between", value1, value2, "cid");
			return (Criteria) this;
		}

		public Criteria andCidNotBetween(String value1, String value2) {
			addCriterion("CID not between", value1, value2, "cid");
			return (Criteria) this;
		}

		public Criteria andHidIsNull() {
			addCriterion("HID is null");
			return (Criteria) this;
		}

		public Criteria andHidIsNotNull() {
			addCriterion("HID is not null");
			return (Criteria) this;
		}

		public Criteria andHidEqualTo(String value) {
			addCriterion("HID =", value, "hid");
			return (Criteria) this;
		}

		public Criteria andHidNotEqualTo(String value) {
			addCriterion("HID <>", value, "hid");
			return (Criteria) this;
		}

		public Criteria andHidGreaterThan(String value) {
			addCriterion("HID >", value, "hid");
			return (Criteria) this;
		}

		public Criteria andHidGreaterThanOrEqualTo(String value) {
			addCriterion("HID >=", value, "hid");
			return (Criteria) this;
		}

		public Criteria andHidLessThan(String value) {
			addCriterion("HID <", value, "hid");
			return (Criteria) this;
		}

		public Criteria andHidLessThanOrEqualTo(String value) {
			addCriterion("HID <=", value, "hid");
			return (Criteria) this;
		}

		public Criteria andHidLike(String value) {
			addCriterion("HID like", value, "hid");
			return (Criteria) this;
		}

		public Criteria andHidNotLike(String value) {
			addCriterion("HID not like", value, "hid");
			return (Criteria) this;
		}

		public Criteria andHidIn(List<String> values) {
			addCriterion("HID in", values, "hid");
			return (Criteria) this;
		}

		public Criteria andHidNotIn(List<String> values) {
			addCriterion("HID not in", values, "hid");
			return (Criteria) this;
		}

		public Criteria andHidBetween(String value1, String value2) {
			addCriterion("HID between", value1, value2, "hid");
			return (Criteria) this;
		}

		public Criteria andHidNotBetween(String value1, String value2) {
			addCriterion("HID not between", value1, value2, "hid");
			return (Criteria) this;
		}

		public Criteria andUidIsNull() {
			addCriterion("UID is null");
			return (Criteria) this;
		}

		public Criteria andUidIsNotNull() {
			addCriterion("UID is not null");
			return (Criteria) this;
		}

		public Criteria andUidEqualTo(String value) {
			addCriterion("UID =", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotEqualTo(String value) {
			addCriterion("UID <>", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidGreaterThan(String value) {
			addCriterion("UID >", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidGreaterThanOrEqualTo(String value) {
			addCriterion("UID >=", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidLessThan(String value) {
			addCriterion("UID <", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidLessThanOrEqualTo(String value) {
			addCriterion("UID <=", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidLike(String value) {
			addCriterion("UID like", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotLike(String value) {
			addCriterion("UID not like", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidIn(List<String> values) {
			addCriterion("UID in", values, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotIn(List<String> values) {
			addCriterion("UID not in", values, "uid");
			return (Criteria) this;
		}

		public Criteria andUidBetween(String value1, String value2) {
			addCriterion("UID between", value1, value2, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotBetween(String value1, String value2) {
			addCriterion("UID not between", value1, value2, "uid");
			return (Criteria) this;
		}

		public Criteria andPidIsNull() {
			addCriterion("PID is null");
			return (Criteria) this;
		}

		public Criteria andPidIsNotNull() {
			addCriterion("PID is not null");
			return (Criteria) this;
		}

		public Criteria andPidEqualTo(String value) {
			addCriterion("PID =", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidNotEqualTo(String value) {
			addCriterion("PID <>", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidGreaterThan(String value) {
			addCriterion("PID >", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidGreaterThanOrEqualTo(String value) {
			addCriterion("PID >=", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidLessThan(String value) {
			addCriterion("PID <", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidLessThanOrEqualTo(String value) {
			addCriterion("PID <=", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidLike(String value) {
			addCriterion("PID like", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidNotLike(String value) {
			addCriterion("PID not like", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidIn(List<String> values) {
			addCriterion("PID in", values, "pid");
			return (Criteria) this;
		}

		public Criteria andPidNotIn(List<String> values) {
			addCriterion("PID not in", values, "pid");
			return (Criteria) this;
		}

		public Criteria andPidBetween(String value1, String value2) {
			addCriterion("PID between", value1, value2, "pid");
			return (Criteria) this;
		}

		public Criteria andPidNotBetween(String value1, String value2) {
			addCriterion("PID not between", value1, value2, "pid");
			return (Criteria) this;
		}

		public Criteria andAmountIsNull() {
			addCriterion("AMOUNT is null");
			return (Criteria) this;
		}

		public Criteria andAmountIsNotNull() {
			addCriterion("AMOUNT is not null");
			return (Criteria) this;
		}

		public Criteria andAmountEqualTo(BigDecimal value) {
			addCriterion("AMOUNT =", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotEqualTo(BigDecimal value) {
			addCriterion("AMOUNT <>", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThan(BigDecimal value) {
			addCriterion("AMOUNT >", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("AMOUNT >=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThan(BigDecimal value) {
			addCriterion("AMOUNT <", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThanOrEqualTo(BigDecimal value) {
			addCriterion("AMOUNT <=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountIn(List<BigDecimal> values) {
			addCriterion("AMOUNT in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotIn(List<BigDecimal> values) {
			addCriterion("AMOUNT not in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("AMOUNT between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("AMOUNT not between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andSignedDtIsNull() {
			addCriterion("SIGNED_DT is null");
			return (Criteria) this;
		}

		public Criteria andSignedDtIsNotNull() {
			addCriterion("SIGNED_DT is not null");
			return (Criteria) this;
		}

		public Criteria andSignedDtEqualTo(Date value) {
			addCriterion("SIGNED_DT =", value, "signedDt");
			return (Criteria) this;
		}

		public Criteria andSignedDtNotEqualTo(Date value) {
			addCriterion("SIGNED_DT <>", value, "signedDt");
			return (Criteria) this;
		}

		public Criteria andSignedDtGreaterThan(Date value) {
			addCriterion("SIGNED_DT >", value, "signedDt");
			return (Criteria) this;
		}

		public Criteria andSignedDtGreaterThanOrEqualTo(Date value) {
			addCriterion("SIGNED_DT >=", value, "signedDt");
			return (Criteria) this;
		}

		public Criteria andSignedDtLessThan(Date value) {
			addCriterion("SIGNED_DT <", value, "signedDt");
			return (Criteria) this;
		}

		public Criteria andSignedDtLessThanOrEqualTo(Date value) {
			addCriterion("SIGNED_DT <=", value, "signedDt");
			return (Criteria) this;
		}

		public Criteria andSignedDtIn(List<Date> values) {
			addCriterion("SIGNED_DT in", values, "signedDt");
			return (Criteria) this;
		}

		public Criteria andSignedDtNotIn(List<Date> values) {
			addCriterion("SIGNED_DT not in", values, "signedDt");
			return (Criteria) this;
		}

		public Criteria andSignedDtBetween(Date value1, Date value2) {
			addCriterion("SIGNED_DT between", value1, value2, "signedDt");
			return (Criteria) this;
		}

		public Criteria andSignedDtNotBetween(Date value1, Date value2) {
			addCriterion("SIGNED_DT not between", value1, value2, "signedDt");
			return (Criteria) this;
		}

		public Criteria andExpireDtIsNull() {
			addCriterion("EXPIRE_DT is null");
			return (Criteria) this;
		}

		public Criteria andExpireDtIsNotNull() {
			addCriterion("EXPIRE_DT is not null");
			return (Criteria) this;
		}

		public Criteria andExpireDtEqualTo(Date value) {
			addCriterion("EXPIRE_DT =", value, "expireDt");
			return (Criteria) this;
		}

		public Criteria andExpireDtNotEqualTo(Date value) {
			addCriterion("EXPIRE_DT <>", value, "expireDt");
			return (Criteria) this;
		}

		public Criteria andExpireDtGreaterThan(Date value) {
			addCriterion("EXPIRE_DT >", value, "expireDt");
			return (Criteria) this;
		}

		public Criteria andExpireDtGreaterThanOrEqualTo(Date value) {
			addCriterion("EXPIRE_DT >=", value, "expireDt");
			return (Criteria) this;
		}

		public Criteria andExpireDtLessThan(Date value) {
			addCriterion("EXPIRE_DT <", value, "expireDt");
			return (Criteria) this;
		}

		public Criteria andExpireDtLessThanOrEqualTo(Date value) {
			addCriterion("EXPIRE_DT <=", value, "expireDt");
			return (Criteria) this;
		}

		public Criteria andExpireDtIn(List<Date> values) {
			addCriterion("EXPIRE_DT in", values, "expireDt");
			return (Criteria) this;
		}

		public Criteria andExpireDtNotIn(List<Date> values) {
			addCriterion("EXPIRE_DT not in", values, "expireDt");
			return (Criteria) this;
		}

		public Criteria andExpireDtBetween(Date value1, Date value2) {
			addCriterion("EXPIRE_DT between", value1, value2, "expireDt");
			return (Criteria) this;
		}

		public Criteria andExpireDtNotBetween(Date value1, Date value2) {
			addCriterion("EXPIRE_DT not between", value1, value2, "expireDt");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("NAME is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("NAME is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("NAME =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("NAME <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("NAME >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("NAME >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("NAME <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("NAME <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("NAME like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("NAME not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("NAME in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("NAME not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("NAME between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("NAME not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andIdnoIsNull() {
			addCriterion("IDNO is null");
			return (Criteria) this;
		}

		public Criteria andIdnoIsNotNull() {
			addCriterion("IDNO is not null");
			return (Criteria) this;
		}

		public Criteria andIdnoEqualTo(String value) {
			addCriterion("IDNO =", value, "idno");
			return (Criteria) this;
		}

		public Criteria andIdnoNotEqualTo(String value) {
			addCriterion("IDNO <>", value, "idno");
			return (Criteria) this;
		}

		public Criteria andIdnoGreaterThan(String value) {
			addCriterion("IDNO >", value, "idno");
			return (Criteria) this;
		}

		public Criteria andIdnoGreaterThanOrEqualTo(String value) {
			addCriterion("IDNO >=", value, "idno");
			return (Criteria) this;
		}

		public Criteria andIdnoLessThan(String value) {
			addCriterion("IDNO <", value, "idno");
			return (Criteria) this;
		}

		public Criteria andIdnoLessThanOrEqualTo(String value) {
			addCriterion("IDNO <=", value, "idno");
			return (Criteria) this;
		}

		public Criteria andIdnoLike(String value) {
			addCriterion("IDNO like", value, "idno");
			return (Criteria) this;
		}

		public Criteria andIdnoNotLike(String value) {
			addCriterion("IDNO not like", value, "idno");
			return (Criteria) this;
		}

		public Criteria andIdnoIn(List<String> values) {
			addCriterion("IDNO in", values, "idno");
			return (Criteria) this;
		}

		public Criteria andIdnoNotIn(List<String> values) {
			addCriterion("IDNO not in", values, "idno");
			return (Criteria) this;
		}

		public Criteria andIdnoBetween(String value1, String value2) {
			addCriterion("IDNO between", value1, value2, "idno");
			return (Criteria) this;
		}

		public Criteria andIdnoNotBetween(String value1, String value2) {
			addCriterion("IDNO not between", value1, value2, "idno");
			return (Criteria) this;
		}

		public Criteria andHnoIsNull() {
			addCriterion("HNO is null");
			return (Criteria) this;
		}

		public Criteria andHnoIsNotNull() {
			addCriterion("HNO is not null");
			return (Criteria) this;
		}

		public Criteria andHnoEqualTo(String value) {
			addCriterion("HNO =", value, "hno");
			return (Criteria) this;
		}

		public Criteria andHnoNotEqualTo(String value) {
			addCriterion("HNO <>", value, "hno");
			return (Criteria) this;
		}

		public Criteria andHnoGreaterThan(String value) {
			addCriterion("HNO >", value, "hno");
			return (Criteria) this;
		}

		public Criteria andHnoGreaterThanOrEqualTo(String value) {
			addCriterion("HNO >=", value, "hno");
			return (Criteria) this;
		}

		public Criteria andHnoLessThan(String value) {
			addCriterion("HNO <", value, "hno");
			return (Criteria) this;
		}

		public Criteria andHnoLessThanOrEqualTo(String value) {
			addCriterion("HNO <=", value, "hno");
			return (Criteria) this;
		}

		public Criteria andHnoLike(String value) {
			addCriterion("HNO like", value, "hno");
			return (Criteria) this;
		}

		public Criteria andHnoNotLike(String value) {
			addCriterion("HNO not like", value, "hno");
			return (Criteria) this;
		}

		public Criteria andHnoIn(List<String> values) {
			addCriterion("HNO in", values, "hno");
			return (Criteria) this;
		}

		public Criteria andHnoNotIn(List<String> values) {
			addCriterion("HNO not in", values, "hno");
			return (Criteria) this;
		}

		public Criteria andHnoBetween(String value1, String value2) {
			addCriterion("HNO between", value1, value2, "hno");
			return (Criteria) this;
		}

		public Criteria andHnoNotBetween(String value1, String value2) {
			addCriterion("HNO not between", value1, value2, "hno");
			return (Criteria) this;
		}

		public Criteria andCnoIsNull() {
			addCriterion("CNO is null");
			return (Criteria) this;
		}

		public Criteria andCnoIsNotNull() {
			addCriterion("CNO is not null");
			return (Criteria) this;
		}

		public Criteria andCnoEqualTo(String value) {
			addCriterion("CNO =", value, "cno");
			return (Criteria) this;
		}

		public Criteria andCnoNotEqualTo(String value) {
			addCriterion("CNO <>", value, "cno");
			return (Criteria) this;
		}

		public Criteria andCnoGreaterThan(String value) {
			addCriterion("CNO >", value, "cno");
			return (Criteria) this;
		}

		public Criteria andCnoGreaterThanOrEqualTo(String value) {
			addCriterion("CNO >=", value, "cno");
			return (Criteria) this;
		}

		public Criteria andCnoLessThan(String value) {
			addCriterion("CNO <", value, "cno");
			return (Criteria) this;
		}

		public Criteria andCnoLessThanOrEqualTo(String value) {
			addCriterion("CNO <=", value, "cno");
			return (Criteria) this;
		}

		public Criteria andCnoLike(String value) {
			addCriterion("CNO like", value, "cno");
			return (Criteria) this;
		}

		public Criteria andCnoNotLike(String value) {
			addCriterion("CNO not like", value, "cno");
			return (Criteria) this;
		}

		public Criteria andCnoIn(List<String> values) {
			addCriterion("CNO in", values, "cno");
			return (Criteria) this;
		}

		public Criteria andCnoNotIn(List<String> values) {
			addCriterion("CNO not in", values, "cno");
			return (Criteria) this;
		}

		public Criteria andCnoBetween(String value1, String value2) {
			addCriterion("CNO between", value1, value2, "cno");
			return (Criteria) this;
		}

		public Criteria andCnoNotBetween(String value1, String value2) {
			addCriterion("CNO not between", value1, value2, "cno");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNull() {
			addCriterion("PHONE is null");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNotNull() {
			addCriterion("PHONE is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneEqualTo(String value) {
			addCriterion("PHONE =", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotEqualTo(String value) {
			addCriterion("PHONE <>", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThan(String value) {
			addCriterion("PHONE >", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("PHONE >=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThan(String value) {
			addCriterion("PHONE <", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThanOrEqualTo(String value) {
			addCriterion("PHONE <=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLike(String value) {
			addCriterion("PHONE like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotLike(String value) {
			addCriterion("PHONE not like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneIn(List<String> values) {
			addCriterion("PHONE in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotIn(List<String> values) {
			addCriterion("PHONE not in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneBetween(String value1, String value2) {
			addCriterion("PHONE between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotBetween(String value1, String value2) {
			addCriterion("PHONE not between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andBankNoIsNull() {
			addCriterion("BANK_NO is null");
			return (Criteria) this;
		}

		public Criteria andBankNoIsNotNull() {
			addCriterion("BANK_NO is not null");
			return (Criteria) this;
		}

		public Criteria andBankNoEqualTo(String value) {
			addCriterion("BANK_NO =", value, "bankNo");
			return (Criteria) this;
		}

		public Criteria andBankNoNotEqualTo(String value) {
			addCriterion("BANK_NO <>", value, "bankNo");
			return (Criteria) this;
		}

		public Criteria andBankNoGreaterThan(String value) {
			addCriterion("BANK_NO >", value, "bankNo");
			return (Criteria) this;
		}

		public Criteria andBankNoGreaterThanOrEqualTo(String value) {
			addCriterion("BANK_NO >=", value, "bankNo");
			return (Criteria) this;
		}

		public Criteria andBankNoLessThan(String value) {
			addCriterion("BANK_NO <", value, "bankNo");
			return (Criteria) this;
		}

		public Criteria andBankNoLessThanOrEqualTo(String value) {
			addCriterion("BANK_NO <=", value, "bankNo");
			return (Criteria) this;
		}

		public Criteria andBankNoLike(String value) {
			addCriterion("BANK_NO like", value, "bankNo");
			return (Criteria) this;
		}

		public Criteria andBankNoNotLike(String value) {
			addCriterion("BANK_NO not like", value, "bankNo");
			return (Criteria) this;
		}

		public Criteria andBankNoIn(List<String> values) {
			addCriterion("BANK_NO in", values, "bankNo");
			return (Criteria) this;
		}

		public Criteria andBankNoNotIn(List<String> values) {
			addCriterion("BANK_NO not in", values, "bankNo");
			return (Criteria) this;
		}

		public Criteria andBankNoBetween(String value1, String value2) {
			addCriterion("BANK_NO between", value1, value2, "bankNo");
			return (Criteria) this;
		}

		public Criteria andBankNoNotBetween(String value1, String value2) {
			addCriterion("BANK_NO not between", value1, value2, "bankNo");
			return (Criteria) this;
		}

		public Criteria andNoIsNull() {
			addCriterion("NO is null");
			return (Criteria) this;
		}

		public Criteria andNoIsNotNull() {
			addCriterion("NO is not null");
			return (Criteria) this;
		}

		public Criteria andNoEqualTo(String value) {
			addCriterion("NO =", value, "no");
			return (Criteria) this;
		}

		public Criteria andNoNotEqualTo(String value) {
			addCriterion("NO <>", value, "no");
			return (Criteria) this;
		}

		public Criteria andNoGreaterThan(String value) {
			addCriterion("NO >", value, "no");
			return (Criteria) this;
		}

		public Criteria andNoGreaterThanOrEqualTo(String value) {
			addCriterion("NO >=", value, "no");
			return (Criteria) this;
		}

		public Criteria andNoLessThan(String value) {
			addCriterion("NO <", value, "no");
			return (Criteria) this;
		}

		public Criteria andNoLessThanOrEqualTo(String value) {
			addCriterion("NO <=", value, "no");
			return (Criteria) this;
		}

		public Criteria andNoLike(String value) {
			addCriterion("NO like", value, "no");
			return (Criteria) this;
		}

		public Criteria andNoNotLike(String value) {
			addCriterion("NO not like", value, "no");
			return (Criteria) this;
		}

		public Criteria andNoIn(List<String> values) {
			addCriterion("NO in", values, "no");
			return (Criteria) this;
		}

		public Criteria andNoNotIn(List<String> values) {
			addCriterion("NO not in", values, "no");
			return (Criteria) this;
		}

		public Criteria andNoBetween(String value1, String value2) {
			addCriterion("NO between", value1, value2, "no");
			return (Criteria) this;
		}

		public Criteria andNoNotBetween(String value1, String value2) {
			addCriterion("NO not between", value1, value2, "no");
			return (Criteria) this;
		}

		public Criteria andInoIsNull() {
			addCriterion("INO is null");
			return (Criteria) this;
		}

		public Criteria andInoIsNotNull() {
			addCriterion("INO is not null");
			return (Criteria) this;
		}

		public Criteria andInoEqualTo(String value) {
			addCriterion("INO =", value, "ino");
			return (Criteria) this;
		}

		public Criteria andInoNotEqualTo(String value) {
			addCriterion("INO <>", value, "ino");
			return (Criteria) this;
		}

		public Criteria andInoGreaterThan(String value) {
			addCriterion("INO >", value, "ino");
			return (Criteria) this;
		}

		public Criteria andInoGreaterThanOrEqualTo(String value) {
			addCriterion("INO >=", value, "ino");
			return (Criteria) this;
		}

		public Criteria andInoLessThan(String value) {
			addCriterion("INO <", value, "ino");
			return (Criteria) this;
		}

		public Criteria andInoLessThanOrEqualTo(String value) {
			addCriterion("INO <=", value, "ino");
			return (Criteria) this;
		}

		public Criteria andInoLike(String value) {
			addCriterion("INO like", value, "ino");
			return (Criteria) this;
		}

		public Criteria andInoNotLike(String value) {
			addCriterion("INO not like", value, "ino");
			return (Criteria) this;
		}

		public Criteria andInoIn(List<String> values) {
			addCriterion("INO in", values, "ino");
			return (Criteria) this;
		}

		public Criteria andInoNotIn(List<String> values) {
			addCriterion("INO not in", values, "ino");
			return (Criteria) this;
		}

		public Criteria andInoBetween(String value1, String value2) {
			addCriterion("INO between", value1, value2, "ino");
			return (Criteria) this;
		}

		public Criteria andInoNotBetween(String value1, String value2) {
			addCriterion("INO not between", value1, value2, "ino");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("STATUS like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("STATUS not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNull() {
			addCriterion("CREATE_USER is null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNotNull() {
			addCriterion("CREATE_USER is not null");
			return (Criteria) this;
		}

		public Criteria andCreateUserEqualTo(String value) {
			addCriterion("CREATE_USER =", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotEqualTo(String value) {
			addCriterion("CREATE_USER <>", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThan(String value) {
			addCriterion("CREATE_USER >", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
			addCriterion("CREATE_USER >=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThan(String value) {
			addCriterion("CREATE_USER <", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThanOrEqualTo(String value) {
			addCriterion("CREATE_USER <=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLike(String value) {
			addCriterion("CREATE_USER like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotLike(String value) {
			addCriterion("CREATE_USER not like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserIn(List<String> values) {
			addCriterion("CREATE_USER in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotIn(List<String> values) {
			addCriterion("CREATE_USER not in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserBetween(String value1, String value2) {
			addCriterion("CREATE_USER between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotBetween(String value1, String value2) {
			addCriterion("CREATE_USER not between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityIsNull() {
			addCriterion("CREATE_USER_IDENTITY is null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityIsNotNull() {
			addCriterion("CREATE_USER_IDENTITY is not null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityEqualTo(Short value) {
			addCriterion("CREATE_USER_IDENTITY =", value, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityNotEqualTo(Short value) {
			addCriterion("CREATE_USER_IDENTITY <>", value, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityGreaterThan(Short value) {
			addCriterion("CREATE_USER_IDENTITY >", value, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityGreaterThanOrEqualTo(Short value) {
			addCriterion("CREATE_USER_IDENTITY >=", value, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityLessThan(Short value) {
			addCriterion("CREATE_USER_IDENTITY <", value, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityLessThanOrEqualTo(Short value) {
			addCriterion("CREATE_USER_IDENTITY <=", value, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityIn(List<Short> values) {
			addCriterion("CREATE_USER_IDENTITY in", values, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityNotIn(List<Short> values) {
			addCriterion("CREATE_USER_IDENTITY not in", values, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityBetween(Short value1, Short value2) {
			addCriterion("CREATE_USER_IDENTITY between", value1, value2, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdentityNotBetween(Short value1, Short value2) {
			addCriterion("CREATE_USER_IDENTITY not between", value1, value2, "createUserIdentity");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifyUserIsNull() {
			addCriterion("MODIFY_USER is null");
			return (Criteria) this;
		}

		public Criteria andModifyUserIsNotNull() {
			addCriterion("MODIFY_USER is not null");
			return (Criteria) this;
		}

		public Criteria andModifyUserEqualTo(String value) {
			addCriterion("MODIFY_USER =", value, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserNotEqualTo(String value) {
			addCriterion("MODIFY_USER <>", value, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserGreaterThan(String value) {
			addCriterion("MODIFY_USER >", value, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserGreaterThanOrEqualTo(String value) {
			addCriterion("MODIFY_USER >=", value, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserLessThan(String value) {
			addCriterion("MODIFY_USER <", value, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserLessThanOrEqualTo(String value) {
			addCriterion("MODIFY_USER <=", value, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserLike(String value) {
			addCriterion("MODIFY_USER like", value, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserNotLike(String value) {
			addCriterion("MODIFY_USER not like", value, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserIn(List<String> values) {
			addCriterion("MODIFY_USER in", values, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserNotIn(List<String> values) {
			addCriterion("MODIFY_USER not in", values, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserBetween(String value1, String value2) {
			addCriterion("MODIFY_USER between", value1, value2, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserNotBetween(String value1, String value2) {
			addCriterion("MODIFY_USER not between", value1, value2, "modifyUser");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityIsNull() {
			addCriterion("MODIFY_USER_IDENTITY is null");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityIsNotNull() {
			addCriterion("MODIFY_USER_IDENTITY is not null");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityEqualTo(Short value) {
			addCriterion("MODIFY_USER_IDENTITY =", value, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityNotEqualTo(Short value) {
			addCriterion("MODIFY_USER_IDENTITY <>", value, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityGreaterThan(Short value) {
			addCriterion("MODIFY_USER_IDENTITY >", value, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityGreaterThanOrEqualTo(Short value) {
			addCriterion("MODIFY_USER_IDENTITY >=", value, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityLessThan(Short value) {
			addCriterion("MODIFY_USER_IDENTITY <", value, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityLessThanOrEqualTo(Short value) {
			addCriterion("MODIFY_USER_IDENTITY <=", value, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityIn(List<Short> values) {
			addCriterion("MODIFY_USER_IDENTITY in", values, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityNotIn(List<Short> values) {
			addCriterion("MODIFY_USER_IDENTITY not in", values, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityBetween(Short value1, Short value2) {
			addCriterion("MODIFY_USER_IDENTITY between", value1, value2, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyUserIdentityNotBetween(Short value1, Short value2) {
			addCriterion("MODIFY_USER_IDENTITY not between", value1, value2, "modifyUserIdentity");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNull() {
			addCriterion("MODIFY_TIME is null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNotNull() {
			addCriterion("MODIFY_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeEqualTo(Date value) {
			addCriterion("MODIFY_TIME =", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotEqualTo(Date value) {
			addCriterion("MODIFY_TIME <>", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThan(Date value) {
			addCriterion("MODIFY_TIME >", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("MODIFY_TIME >=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThan(Date value) {
			addCriterion("MODIFY_TIME <", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
			addCriterion("MODIFY_TIME <=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIn(List<Date> values) {
			addCriterion("MODIFY_TIME in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotIn(List<Date> values) {
			addCriterion("MODIFY_TIME not in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeBetween(Date value1, Date value2) {
			addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
			addCriterion("MODIFY_TIME not between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIsNull() {
			addCriterion("DELETE_FLG is null");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIsNotNull() {
			addCriterion("DELETE_FLG is not null");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgEqualTo(Short value) {
			addCriterion("DELETE_FLG =", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotEqualTo(Short value) {
			addCriterion("DELETE_FLG <>", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgGreaterThan(Short value) {
			addCriterion("DELETE_FLG >", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgGreaterThanOrEqualTo(Short value) {
			addCriterion("DELETE_FLG >=", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgLessThan(Short value) {
			addCriterion("DELETE_FLG <", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgLessThanOrEqualTo(Short value) {
			addCriterion("DELETE_FLG <=", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIn(List<Short> values) {
			addCriterion("DELETE_FLG in", values, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotIn(List<Short> values) {
			addCriterion("DELETE_FLG not in", values, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgBetween(Short value1, Short value2) {
			addCriterion("DELETE_FLG between", value1, value2, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotBetween(Short value1, Short value2) {
			addCriterion("DELETE_FLG not between", value1, value2, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andVersionIsNull() {
			addCriterion("VERSION is null");
			return (Criteria) this;
		}

		public Criteria andVersionIsNotNull() {
			addCriterion("VERSION is not null");
			return (Criteria) this;
		}

		public Criteria andVersionEqualTo(Integer value) {
			addCriterion("VERSION =", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotEqualTo(Integer value) {
			addCriterion("VERSION <>", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThan(Integer value) {
			addCriterion("VERSION >", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
			addCriterion("VERSION >=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThan(Integer value) {
			addCriterion("VERSION <", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThanOrEqualTo(Integer value) {
			addCriterion("VERSION <=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionIn(List<Integer> values) {
			addCriterion("VERSION in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotIn(List<Integer> values) {
			addCriterion("VERSION not in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionBetween(Integer value1, Integer value2) {
			addCriterion("VERSION between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotBetween(Integer value1, Integer value2) {
			addCriterion("VERSION not between", value1, value2, "version");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_insurance
	 * @mbggenerated  Wed Sep 14 09:27:26 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_insurance
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 07 15:23:46 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}