package com.dlfc.zfgj.entity;

import com.dlfc.admin.common.persistence.MyDataEntity;

import java.io.Serializable;

public class SysUserRole extends MyDataEntity<SysUserRole> implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_role.user_id
	 * @mbggenerated  Mon Nov 09 16:01:06 CST 2015
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_role.role_id
	 * @mbggenerated  Mon Nov 09 16:01:06 CST 2015
	 */
	private String roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_user_role
	 * @mbggenerated  Mon Nov 09 16:01:06 CST 2015
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_role.user_id
	 * @return  the value of sys_user_role.user_id
	 * @mbggenerated  Mon Nov 09 16:01:06 CST 2015
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_role.user_id
	 * @param userId  the value for sys_user_role.user_id
	 * @mbggenerated  Mon Nov 09 16:01:06 CST 2015
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_role.role_id
	 * @return  the value of sys_user_role.role_id
	 * @mbggenerated  Mon Nov 09 16:01:06 CST 2015
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_role.role_id
	 * @param roleId  the value for sys_user_role.role_id
	 * @mbggenerated  Mon Nov 09 16:01:06 CST 2015
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId == null ? null : roleId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_role
	 * @mbggenerated  Mon Nov 09 16:01:06 CST 2015
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", userId=").append(userId);
		sb.append(", roleId=").append(roleId);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}