package com.dlfc.zfgj.entity;

import com.dlfc.admin.common.persistence.MyDataEntity;

import java.io.Serializable;
import java.util.Date;

public class UsrHouseviewHistory extends MyDataEntity<UsrHouseviewHistory> implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usr_houseview_history.PINDEX
	 * @mbggenerated  Fri Feb 19 20:08:45 CST 2016
	 */
	private Integer pindex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usr_houseview_history.UID
	 * @mbggenerated  Fri Feb 19 20:08:45 CST 2016
	 */
	private String uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usr_houseview_history.HID
	 * @mbggenerated  Fri Feb 19 20:08:45 CST 2016
	 */
	private String hid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usr_houseview_history.DTIME
	 * @mbggenerated  Fri Feb 19 20:08:45 CST 2016
	 */
	private Date dtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table usr_houseview_history
	 * @mbggenerated  Fri Feb 19 20:08:45 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usr_houseview_history.PINDEX
	 * @return  the value of usr_houseview_history.PINDEX
	 * @mbggenerated  Fri Feb 19 20:08:45 CST 2016
	 */
	public Integer getPindex() {
		return pindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usr_houseview_history.PINDEX
	 * @param pindex  the value for usr_houseview_history.PINDEX
	 * @mbggenerated  Fri Feb 19 20:08:45 CST 2016
	 */
	public void setPindex(Integer pindex) {
		this.pindex = pindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usr_houseview_history.UID
	 * @return  the value of usr_houseview_history.UID
	 * @mbggenerated  Fri Feb 19 20:08:45 CST 2016
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usr_houseview_history.UID
	 * @param uid  the value for usr_houseview_history.UID
	 * @mbggenerated  Fri Feb 19 20:08:45 CST 2016
	 */
	public void setUid(String uid) {
		this.uid = uid == null ? null : uid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usr_houseview_history.HID
	 * @return  the value of usr_houseview_history.HID
	 * @mbggenerated  Fri Feb 19 20:08:45 CST 2016
	 */
	public String getHid() {
		return hid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usr_houseview_history.HID
	 * @param hid  the value for usr_houseview_history.HID
	 * @mbggenerated  Fri Feb 19 20:08:45 CST 2016
	 */
	public void setHid(String hid) {
		this.hid = hid == null ? null : hid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usr_houseview_history.DTIME
	 * @return  the value of usr_houseview_history.DTIME
	 * @mbggenerated  Fri Feb 19 20:08:45 CST 2016
	 */
	public Date getDtime() {
		return dtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usr_houseview_history.DTIME
	 * @param dtime  the value for usr_houseview_history.DTIME
	 * @mbggenerated  Fri Feb 19 20:08:45 CST 2016
	 */
	public void setDtime(Date dtime) {
		this.dtime = dtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr_houseview_history
	 * @mbggenerated  Fri Feb 19 20:08:45 CST 2016
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", pindex=").append(pindex);
		sb.append(", uid=").append(uid);
		sb.append(", hid=").append(hid);
		sb.append(", dtime=").append(dtime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}