package com.dlfc.zfgj.entity;

import com.dlfc.admin.common.persistence.MyDataEntity;

import java.io.Serializable;

public class UsrUserBankcard extends MyDataEntity<UsrUserBankcard> implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usr_user_bankcard.PINDEX
	 * @mbggenerated  Wed Feb 24 15:12:23 CST 2016
	 */
	private Integer pindex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usr_user_bankcard.USER_ID
	 * @mbggenerated  Wed Feb 24 15:12:23 CST 2016
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usr_user_bankcard.BANK_TYPE
	 * @mbggenerated  Wed Feb 24 15:12:23 CST 2016
	 */
	private String bankType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usr_user_bankcard.BANK_NUM
	 * @mbggenerated  Wed Feb 24 15:12:23 CST 2016
	 */
	private String bankNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usr_user_bankcard.BANK_MOBILE
	 * @mbggenerated  Wed Feb 24 15:12:23 CST 2016
	 */
	private String bankMobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usr_user_bankcard.IS_DEFAULT
	 * @mbggenerated  Wed Feb 24 15:12:23 CST 2016
	 */
	private Short isDefault;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table usr_user_bankcard
	 * @mbggenerated  Wed Feb 24 15:12:23 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usr_user_bankcard.PINDEX
	 * @return  the value of usr_user_bankcard.PINDEX
	 * @mbggenerated  Wed Feb 24 15:12:23 CST 2016
	 */
	public Integer getPindex() {
		return pindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usr_user_bankcard.PINDEX
	 * @param pindex  the value for usr_user_bankcard.PINDEX
	 * @mbggenerated  Wed Feb 24 15:12:23 CST 2016
	 */
	public void setPindex(Integer pindex) {
		this.pindex = pindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usr_user_bankcard.USER_ID
	 * @return  the value of usr_user_bankcard.USER_ID
	 * @mbggenerated  Wed Feb 24 15:12:23 CST 2016
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usr_user_bankcard.USER_ID
	 * @param userId  the value for usr_user_bankcard.USER_ID
	 * @mbggenerated  Wed Feb 24 15:12:23 CST 2016
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usr_user_bankcard.BANK_TYPE
	 * @return  the value of usr_user_bankcard.BANK_TYPE
	 * @mbggenerated  Wed Feb 24 15:12:23 CST 2016
	 */
	public String getBankType() {
		return bankType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usr_user_bankcard.BANK_TYPE
	 * @param bankType  the value for usr_user_bankcard.BANK_TYPE
	 * @mbggenerated  Wed Feb 24 15:12:23 CST 2016
	 */
	public void setBankType(String bankType) {
		this.bankType = bankType == null ? null : bankType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usr_user_bankcard.BANK_NUM
	 * @return  the value of usr_user_bankcard.BANK_NUM
	 * @mbggenerated  Wed Feb 24 15:12:23 CST 2016
	 */
	public String getBankNum() {
		return bankNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usr_user_bankcard.BANK_NUM
	 * @param bankNum  the value for usr_user_bankcard.BANK_NUM
	 * @mbggenerated  Wed Feb 24 15:12:23 CST 2016
	 */
	public void setBankNum(String bankNum) {
		this.bankNum = bankNum == null ? null : bankNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usr_user_bankcard.BANK_MOBILE
	 * @return  the value of usr_user_bankcard.BANK_MOBILE
	 * @mbggenerated  Wed Feb 24 15:12:23 CST 2016
	 */
	public String getBankMobile() {
		return bankMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usr_user_bankcard.BANK_MOBILE
	 * @param bankMobile  the value for usr_user_bankcard.BANK_MOBILE
	 * @mbggenerated  Wed Feb 24 15:12:23 CST 2016
	 */
	public void setBankMobile(String bankMobile) {
		this.bankMobile = bankMobile == null ? null : bankMobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usr_user_bankcard.IS_DEFAULT
	 * @return  the value of usr_user_bankcard.IS_DEFAULT
	 * @mbggenerated  Wed Feb 24 15:12:23 CST 2016
	 */
	public Short getIsDefault() {
		return isDefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usr_user_bankcard.IS_DEFAULT
	 * @param isDefault  the value for usr_user_bankcard.IS_DEFAULT
	 * @mbggenerated  Wed Feb 24 15:12:23 CST 2016
	 */
	public void setIsDefault(Short isDefault) {
		this.isDefault = isDefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr_user_bankcard
	 * @mbggenerated  Wed Feb 24 15:12:23 CST 2016
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", pindex=").append(pindex);
		sb.append(", userId=").append(userId);
		sb.append(", bankType=").append(bankType);
		sb.append(", bankNum=").append(bankNum);
		sb.append(", bankMobile=").append(bankMobile);
		sb.append(", isDefault=").append(isDefault);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	private SysBank sysBank;

	public SysBank getSysBank() {
		return sysBank;
	}

	public void setSysBank(SysBank sysBank) {
		this.sysBank = sysBank;
	}
    
}